/* Generated by           cobc 3.2.0 */
/* Generated from         attack.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */


/* Module path */
static const char        *cob_module_path = NULL;

/* Number of call parameters */
static int        cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =    {0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_2 =    {0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_3 =    {0x11,   4,   0, 0x0041, NULL};
static const cob_field_attr a_4 =    {0x10,   2,   0, 0x0007, NULL};
static const cob_field_attr a_5 =    {0x10,   1,   0, 0x0007, NULL};


/* Constants */
static const cob_field c_1    = {2, (cob_u8_ptr)"15", &a_1};
static const cob_field c_2    = {2, (cob_u8_ptr)"17", &a_1};
static const cob_field c_3    = {1, (cob_u8_ptr)"1", &a_2};
static const cob_field c_4    = {1, (cob_u8_ptr)"0", &a_2};
static const cob_field c_5    = {2, (cob_u8_ptr)"16", &a_1};
static const cob_field c_6    = {3, (cob_u8_ptr)"-33", &a_4};
static const cob_field c_7    = {3, (cob_u8_ptr)"-31", &a_4};
static const cob_field c_8    = {3, (cob_u8_ptr)"-18", &a_4};
static const cob_field c_9    = {3, (cob_u8_ptr)"-14", &a_4};
static const cob_field c_10    = {2, (cob_u8_ptr)"14", &a_1};
static const cob_field c_11    = {2, (cob_u8_ptr)"18", &a_1};
static const cob_field c_12    = {2, (cob_u8_ptr)"31", &a_1};
static const cob_field c_13    = {2, (cob_u8_ptr)"33", &a_1};
static const cob_field c_14    = {3, (cob_u8_ptr)"-17", &a_4};
static const cob_field c_15    = {3, (cob_u8_ptr)"-16", &a_4};
static const cob_field c_16    = {3, (cob_u8_ptr)"-15", &a_4};
static const cob_field c_17    = {2, (cob_u8_ptr)"-1", &a_5};


static COB_INLINE COB_A_INLINE int
cob_cmp_s16 (const void *p, const cob_s64_t n)
{
    short    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 2);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_add_s16 (void *p, const int val)
{
    void    *x;
    short    n;
    x = &n;
    optim_memcpy (x, p, 2);
    n += val;
    optim_memcpy (p, x, 2);
}


/* Decimal constants */
static    cob_decimal    kc_1;
static    cob_decimal    *dc_1 = NULL;
static    cob_decimal    kc_2;
static    cob_decimal    *dc_2 = NULL;
static    cob_decimal    kc_3;
static    cob_decimal    *dc_3 = NULL;

