/* Generated by           cobc 3.2.0 */
/* Generated from         attack.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'ATTACK' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */
static unsigned char    *b_88 = NULL;  /* MOVE-REC */
static unsigned char    *b_94 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_66;
static unsigned char    *last_b_102;
static unsigned char    *last_b_103;
static unsigned char    *last_b_104;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_55[48] __attribute__((aligned));    /* OFFSETS */
static cob_u8_t    b_60[2] __attribute__((aligned));    /* OFFSETS-INIT */
static cob_u8_t    b_61[2] __attribute__((aligned));    /* I */
static cob_u8_t    b_62[2] __attribute__((aligned));    /* DIR */
static cob_u8_t    b_63[2] __attribute__((aligned));    /* SQ */
static cob_u8_t    b_64[2] __attribute__((aligned));    /* IDX */
static cob_u8_t    b_65[2] __attribute__((aligned));    /* P */

/* End of local data storage */


/* Fields (local) */
static cob_field f_60    = {2, b_60, &a_3};    /* OFFSETS-INIT */
static cob_field f_61    = {2, b_61, &a_3};    /* I */
static cob_field f_63    = {2, b_63, &a_3};    /* SQ */
static cob_field f_64    = {2, b_64, &a_3};    /* IDX */
static cob_field f_102    = {2, NULL, &a_3};    /* L-TARGET-SQ */
static cob_field f_104    = {2, NULL, &a_3};    /* L-ATTACKED */

/* End of fields */

