/* Generated by           cobc 3.2.0 */
/* Generated from         attack.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE        "attack.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 05:30:21"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        53021

/* Global variables */
#include "attack.c.h"

/* Function prototypes */

COB_EXT_EXPORT int        ATTACK (cob_u8_t *, cob_u8_t *, cob_u8_t *, cob_u8_t *);
static int        ATTACK_ (const int, cob_u8_t *, cob_u8_t *, cob_u8_t *, cob_u8_t *);
static void        ATTACK_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'ATTACK' */

/* ENTRY 'ATTACK' */

int
ATTACK (cob_u8_t *b_66, cob_u8_t *b_102, cob_u8_t *b_103, cob_u8_t *b_104)
{
  cob_u8_t *cob_parm_66 = NULL;    /* linkage for GAME-STATE */
  cob_u8_t *cob_parm_102 = NULL;    /* linkage for L-TARGET-SQ */
  cob_u8_t *cob_parm_103 = NULL;    /* linkage for L-BY-SIDE */
  cob_u8_t *cob_parm_104 = NULL;    /* linkage for L-ATTACKED */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
      cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
      cob_call_params = 4;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_66 = b_66;
  }
  if (cob_call_params > 1) {
    cob_parm_102 = b_102;
  }
  if (cob_call_params > 2) {
    cob_parm_103 = b_103;
  }
  if (cob_call_params > 3) {
    cob_parm_104 = b_104;
  }

  return ATTACK_ (0, cob_parm_66, cob_parm_102, cob_parm_103, cob_parm_104);
}

static int
ATTACK_ (const int entry, cob_u8_t *b_66, cob_u8_t *b_102, 
    cob_u8_t *b_103, cob_u8_t *b_104)
{
  /* Program local variables */
  #include "attack.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_66 = b_66;
  last_b_102 = b_102;
  last_b_103 = b_103;
  last_b_104 = b_104;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 24        : Entry     ATTACK                  : attack.cob */
  l_2:;

  /* Line: 24        : IF                 : attack.cob */
  if (((int)cob_cmp_s16 (b_60, 0LL) == 0))
  {

    /* Line: 25        : PERFORM            : attack.cob */
    /* PERFORM INIT-OFFSETS */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_13;
    goto l_11;
    l_13:
    frame_ptr--;

    /* Line: 26        : MOVE               : attack.cob */
    cob_move ((cob_field *)&c_3, &f_60);
  }

  /* Line: 29        : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_4, COB_SET_DATA (f_104, b_104));

  /* Line: 32        : IF                 : attack.cob */
  if (((int)cob_cmp_s16 (b_103, 0LL) == 0))
  {

    /* Line: 33        : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_102, b_102)));
    cob_decimal_sub (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_63, 0);

    /* Line: 34        : PERFORM            : attack.cob */
    /* PERFORM CHECK-WP */
    frame_ptr++;
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_7;
    l_14:
    frame_ptr--;

    /* Line: 35        : IF                 : attack.cob */
    if (((int)cob_cmp_s16 (b_104, 1LL) == 0))
    {

      /* Line: 35        : GOBACK             : attack.cob */
      goto exit_program;
    }

    /* Line: 36        : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_102, b_102)));
    cob_decimal_sub (d_0, dc_2);
    cob_decimal_get_field (d_0, &f_63, 0);

    /* Line: 37        : PERFORM            : attack.cob */
    /* PERFORM CHECK-WP */
    frame_ptr++;
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_7;
    l_15:
    frame_ptr--;

    /* Line: 38        : IF                 : attack.cob */
    if (((int)cob_cmp_s16 (b_104, 1LL) == 0))
    {

      /* Line: 38        : GOBACK             : attack.cob */
      goto exit_program;
    }
  }
  else
  {
    /* ELSE */

    /* Line: 40        : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_102, b_102)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_63, 0);

    /* Line: 41        : PERFORM            : attack.cob */
    /* PERFORM CHECK-BP */
    frame_ptr++;
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_9;
    l_16:
    frame_ptr--;

    /* Line: 42        : IF                 : attack.cob */
    if (((int)cob_cmp_s16 (b_104, 1LL) == 0))
    {

      /* Line: 42        : GOBACK             : attack.cob */
      goto exit_program;
    }

    /* Line: 43        : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_102, b_102)));
    cob_decimal_add (d_0, dc_2);
    cob_decimal_get_field (d_0, &f_63, 0);

    /* Line: 44        : PERFORM            : attack.cob */
    /* PERFORM CHECK-BP */
    frame_ptr++;
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_17;
    goto l_9;
    l_17:
    frame_ptr--;

    /* Line: 45        : IF                 : attack.cob */
    if (((int)cob_cmp_s16 (b_104, 1LL) == 0))
    {

      /* Line: 45        : GOBACK             : attack.cob */
      goto exit_program;
    }
  }

  /* Line: 49        : PERFORM            : attack.cob */
  cob_move ((cob_field *)&c_3, &f_61);
  for (;;)
  {
    /* Line: 49        : UNTIL              : attack.cob */
    if ((((int)cob_cmp_s16 (b_61, 8LL) > 0) || 
        ((int)cob_cmp_s16 (b_104, 1LL) == 0)))
      break;

    /* Line: 50        : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_102, b_102)));
    cob_decimal_set_llint (d_1, cob_get_llint (COB_SET_FLD (f0, 2, b_55 + 2LL * ((cob_s64_t)((*(short *)(b_61))) - 1), &a_3)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_63, 0);

    /* Line: 51        : IF                 : attack.cob */
    if (((((int)cob_cmp_s16 (b_63, 0LL) >= 0) && 
        ((int)cob_cmp_s16 (b_63, 127LL) <= 0)) && 
        ((int)cob_cmp_llint (cob_intr_mod (&f_63, (cob_field *)&c_5), 7LL) <= 0)))
    {

      /* Line: 52        : COMPUTE            : attack.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_add (d_0, dc_3);
      cob_decimal_get_field (d_0, &f_64, 0);

      /* Line: 53        : MOVE               : attack.cob */
      memmove (b_65, b_66 + 2LL * ((cob_s64_t)((*(short *)(b_64))) - 1), 2);

      /* Line: 54        : IF                 : attack.cob */
      if (((int)cob_cmp_s16 (b_103, 0LL) == 0))
      {

        /* Line: 55        : IF                 : attack.cob */
        if (((int)cob_cmp_s16 (b_65, 2LL) == 0))
        {

          /* Line: 55        : MOVE               : attack.cob */
          cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
        }
      }
      else
      {
        /* ELSE */

        /* Line: 57        : IF                 : attack.cob */
        if (((int)cob_cmp_s16 (b_65, 8LL) == 0))
        {

          /* Line: 57        : MOVE               : attack.cob */
          cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
        }
      }
    }
    /* Line: 49        : VARYING            : attack.cob */
    cob_add_s16 (b_61, 1);
  }

  /* Line: 61        : IF                 : attack.cob */
  if (((int)cob_cmp_s16 (b_104, 1LL) == 0))
  {

    /* Line: 61        : GOBACK             : attack.cob */
    goto exit_program;
  }

  /* Line: 64        : PERFORM            : attack.cob */
  cob_move ((cob_field *)&c_3, &f_61);
  for (;;)
  {
    /* Line: 64        : UNTIL              : attack.cob */
    if ((((int)cob_cmp_s16 (b_61, 8LL) > 0) || 
        ((int)cob_cmp_s16 (b_104, 1LL) == 0)))
      break;

    /* Line: 65        : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_102, b_102)));
    cob_decimal_set_llint (d_1, cob_get_llint (COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * ((cob_s64_t)((*(short *)(b_61))) - 1), &a_3)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_63, 0);

    /* Line: 66        : IF                 : attack.cob */
    if (((((int)cob_cmp_s16 (b_63, 0LL) >= 0) && 
        ((int)cob_cmp_s16 (b_63, 127LL) <= 0)) && 
        ((int)cob_cmp_llint (cob_intr_mod (&f_63, (cob_field *)&c_5), 7LL) <= 0)))
    {

      /* Line: 67        : COMPUTE            : attack.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_add (d_0, dc_3);
      cob_decimal_get_field (d_0, &f_64, 0);

      /* Line: 68        : MOVE               : attack.cob */
      memmove (b_65, b_66 + 2LL * ((cob_s64_t)((*(short *)(b_64))) - 1), 2);

      /* Line: 69        : IF                 : attack.cob */
      if (((int)cob_cmp_s16 (b_103, 0LL) == 0))
      {

        /* Line: 70        : IF                 : attack.cob */
        if (((int)cob_cmp_s16 (b_65, 6LL) == 0))
        {

          /* Line: 70        : MOVE               : attack.cob */
          cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
        }
      }
      else
      {
        /* ELSE */

        /* Line: 72        : IF                 : attack.cob */
        if (((int)cob_cmp_s16 (b_65, 12LL) == 0))
        {

          /* Line: 72        : MOVE               : attack.cob */
          cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
        }
      }
    }
    /* Line: 64        : VARYING            : attack.cob */
    cob_add_s16 (b_61, 1);
  }

  /* Line: 76        : IF                 : attack.cob */
  if (((int)cob_cmp_s16 (b_104, 1LL) == 0))
  {

    /* Line: 76        : GOBACK             : attack.cob */
    goto exit_program;
  }

  /* Line: 79        : PERFORM            : attack.cob */
  cob_move ((cob_field *)&c_3, &f_61);
  for (;;)
  {
    /* Line: 79        : UNTIL              : attack.cob */
    if ((((int)cob_cmp_s16 (b_61, 4LL) > 0) || 
        ((int)cob_cmp_s16 (b_104, 1LL) == 0)))
      break;

    /* Line: 80        : MOVE               : attack.cob */
    memcpy (b_62, b_55 + 32 + 2LL * ((cob_s64_t)((*(short *)(b_61))) - 1), 2);

    /* Line: 81        : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_102, b_102)));
    cob_decimal_set_llint (d_1, (*(short *)(b_62)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_63, 0);

    /* Line: 82        : PERFORM            : attack.cob */
    for (;;)
    {
      /* Line: 82        : UNTIL              : attack.cob */
      if ((((((int)cob_cmp_s16 (b_63, 0LL) < 0) || 
          ((int)cob_cmp_s16 (b_63, 127LL) > 0)) || 
          ((int)cob_cmp_llint (cob_intr_mod (&f_63, (cob_field *)&c_5), 7LL) > 0)) || 
          ((int)cob_cmp_s16 (b_104, 1LL) == 0)))
        break;

      /* Line: 83        : COMPUTE            : attack.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_add (d_0, dc_3);
      cob_decimal_get_field (d_0, &f_64, 0);

      /* Line: 84        : MOVE               : attack.cob */
      memmove (b_65, b_66 + 2LL * ((cob_s64_t)((*(short *)(b_64))) - 1), 2);

      /* Line: 85        : IF                 : attack.cob */
      if (((int)cob_cmp_s16 (b_65, 0LL) != 0))
      {

        /* Line: 86        : IF                 : attack.cob */
        if (((int)cob_cmp_s16 (b_103, 0LL) == 0))
        {

          /* Line: 87        : IF                 : attack.cob */
          if ((((int)cob_cmp_s16 (b_65, 3LL) == 0) || 
              ((int)cob_cmp_s16 (b_65, 5LL) == 0)))
          {

            /* Line: 87        : MOVE               : attack.cob */
            cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
          }
        }
        else
        {
          /* ELSE */

          /* Line: 89        : IF                 : attack.cob */
          if ((((int)cob_cmp_s16 (b_65, 9LL) == 0) || 
              ((int)cob_cmp_s16 (b_65, 11LL) == 0)))
          {

            /* Line: 89        : MOVE               : attack.cob */
            cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
          }
        }

        /* Line: 91        : EXIT PERFORM       : attack.cob */
        goto l_5;
      }

      /* Line: 93        : COMPUTE            : attack.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_set_llint (d_1, (*(short *)(b_62)));
      cob_decimal_add (d_0, d_1);
      cob_decimal_get_field (d_0, &f_63, 0);
    }

    /* Implicit EXIT label */
    l_5:;
    /* Line: 79        : VARYING            : attack.cob */
    cob_add_s16 (b_61, 1);
  }

  /* Line: 96        : IF                 : attack.cob */
  if (((int)cob_cmp_s16 (b_104, 1LL) == 0))
  {

    /* Line: 96        : GOBACK             : attack.cob */
    goto exit_program;
  }

  /* Line: 99        : PERFORM            : attack.cob */
  cob_move ((cob_field *)&c_3, &f_61);
  for (;;)
  {
    /* Line: 99        : UNTIL              : attack.cob */
    if ((((int)cob_cmp_s16 (b_61, 4LL) > 0) || 
        ((int)cob_cmp_s16 (b_104, 1LL) == 0)))
      break;

    /* Line: 100       : MOVE               : attack.cob */
    memcpy (b_62, b_55 + 40 + 2LL * ((cob_s64_t)((*(short *)(b_61))) - 1), 2);

    /* Line: 101       : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_102, b_102)));
    cob_decimal_set_llint (d_1, (*(short *)(b_62)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_63, 0);

    /* Line: 102       : PERFORM            : attack.cob */
    for (;;)
    {
      /* Line: 102       : UNTIL              : attack.cob */
      if ((((((int)cob_cmp_s16 (b_63, 0LL) < 0) || 
          ((int)cob_cmp_s16 (b_63, 127LL) > 0)) || 
          ((int)cob_cmp_llint (cob_intr_mod (&f_63, (cob_field *)&c_5), 7LL) > 0)) || 
          ((int)cob_cmp_s16 (b_104, 1LL) == 0)))
        break;

      /* Line: 103       : COMPUTE            : attack.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_add (d_0, dc_3);
      cob_decimal_get_field (d_0, &f_64, 0);

      /* Line: 104       : MOVE               : attack.cob */
      memmove (b_65, b_66 + 2LL * ((cob_s64_t)((*(short *)(b_64))) - 1), 2);

      /* Line: 105       : IF                 : attack.cob */
      if (((int)cob_cmp_s16 (b_65, 0LL) != 0))
      {

        /* Line: 106       : IF                 : attack.cob */
        if (((int)cob_cmp_s16 (b_103, 0LL) == 0))
        {

          /* Line: 107       : IF                 : attack.cob */
          if ((((int)cob_cmp_s16 (b_65, 4LL) == 0) || 
              ((int)cob_cmp_s16 (b_65, 5LL) == 0)))
          {

            /* Line: 107       : MOVE               : attack.cob */
            cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
          }
        }
        else
        {
          /* ELSE */

          /* Line: 109       : IF                 : attack.cob */
          if ((((int)cob_cmp_s16 (b_65, 10LL) == 0) || 
              ((int)cob_cmp_s16 (b_65, 11LL) == 0)))
          {

            /* Line: 109       : MOVE               : attack.cob */
            cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
          }
        }

        /* Line: 111       : EXIT PERFORM       : attack.cob */
        goto l_6;
      }

      /* Line: 113       : COMPUTE            : attack.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_set_llint (d_1, (*(short *)(b_62)));
      cob_decimal_add (d_0, d_1);
      cob_decimal_get_field (d_0, &f_63, 0);
    }

    /* Implicit EXIT label */
    l_6:;
    /* Line: 99        : VARYING            : attack.cob */
    cob_add_s16 (b_61, 1);
  }

  /* Line: 117       : GOBACK             : attack.cob */
  goto exit_program;

  /* Line: 119       : Paragraph CHECK-WP                : attack.cob */
  l_7:;

  /* Line: 120       : IF                 : attack.cob */
  if (((((int)cob_cmp_s16 (b_63, 0LL) >= 0) && 
      ((int)cob_cmp_s16 (b_63, 127LL) <= 0)) && 
      ((int)cob_cmp_llint (cob_intr_mod (&f_63, (cob_field *)&c_5), 7LL) <= 0)))
  {

    /* Line: 121       : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_63)));
    cob_decimal_add (d_0, dc_3);
    cob_decimal_get_field (d_0, &f_64, 0);

    /* Line: 122       : IF                 : attack.cob */
    if (((int)cob_cmp_s16 (b_66 + 2LL * ((cob_s64_t)((*(short *)(b_64))) - 1), 1LL) == 0))
    {

      /* Line: 122       : MOVE               : attack.cob */
      cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
    }
  }

  /* Line: 124       : EXIT PARAGRAPH     : attack.cob */
  goto l_8;

  /* Implicit EXIT label */
  l_8:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 126       : Paragraph CHECK-BP                : attack.cob */
  l_9:;

  /* Line: 127       : IF                 : attack.cob */
  if (((((int)cob_cmp_s16 (b_63, 0LL) >= 0) && 
      ((int)cob_cmp_s16 (b_63, 127LL) <= 0)) && 
      ((int)cob_cmp_llint (cob_intr_mod (&f_63, (cob_field *)&c_5), 7LL) <= 0)))
  {

    /* Line: 128       : COMPUTE            : attack.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_63)));
    cob_decimal_add (d_0, dc_3);
    cob_decimal_get_field (d_0, &f_64, 0);

    /* Line: 129       : IF                 : attack.cob */
    if (((int)cob_cmp_s16 (b_66 + 2LL * ((cob_s64_t)((*(short *)(b_64))) - 1), 7LL) == 0))
    {

      /* Line: 129       : MOVE               : attack.cob */
      cob_move ((cob_field *)&c_3, COB_SET_DATA (f_104, b_104));
    }
  }

  /* Line: 131       : EXIT PARAGRAPH     : attack.cob */
  goto l_10;

  /* Implicit EXIT label */
  l_10:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 133       : Paragraph INIT-OFFSETS            : attack.cob */
  l_11:;

  /* Line: 134       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_6, COB_SET_FLD (f0, 2, b_55, &a_3));

  /* Line: 135       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_7, COB_SET_FLD (f0, 2, b_55 + 2LL * 1LL, &a_3));

  /* Line: 136       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_8, COB_SET_FLD (f0, 2, b_55 + 2LL * 2LL, &a_3));

  /* Line: 137       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_9, COB_SET_FLD (f0, 2, b_55 + 2LL * 3LL, &a_3));

  /* Line: 138       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_10, COB_SET_FLD (f0, 2, b_55 + 2LL * 4LL, &a_3));

  /* Line: 139       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_11, COB_SET_FLD (f0, 2, b_55 + 2LL * 5LL, &a_3));

  /* Line: 140       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_12, COB_SET_FLD (f0, 2, b_55 + 2LL * 6LL, &a_3));

  /* Line: 141       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_13, COB_SET_FLD (f0, 2, b_55 + 2LL * 7LL, &a_3));

  /* Line: 143       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_14, COB_SET_FLD (f0, 2, b_55 + 16, &a_3));

  /* Line: 144       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_15, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 1LL, &a_3));

  /* Line: 145       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_16, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 2LL, &a_3));

  /* Line: 146       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_17, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 3LL, &a_3));

  /* Line: 147       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_3, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 4LL, &a_3));

  /* Line: 148       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_1, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 5LL, &a_3));

  /* Line: 149       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_5, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 6LL, &a_3));

  /* Line: 150       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_2, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 7LL, &a_3));

  /* Line: 152       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_14, COB_SET_FLD (f0, 2, b_55 + 32, &a_3));

  /* Line: 153       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_16, COB_SET_FLD (f0, 2, b_55 + 32 + 2LL * 1LL, &a_3));

  /* Line: 154       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_1, COB_SET_FLD (f0, 2, b_55 + 32 + 2LL * 2LL, &a_3));

  /* Line: 155       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_2, COB_SET_FLD (f0, 2, b_55 + 32 + 2LL * 3LL, &a_3));

  /* Line: 157       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_15, COB_SET_FLD (f0, 2, b_55 + 40, &a_3));

  /* Line: 158       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_17, COB_SET_FLD (f0, 2, b_55 + 40 + 2LL * 1LL, &a_3));

  /* Line: 159       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_3, COB_SET_FLD (f0, 2, b_55 + 40 + 2LL * 2LL, &a_3));

  /* Line: 160       : MOVE               : attack.cob */
  cob_move ((cob_field *)&c_5, COB_SET_FLD (f0, 2, b_55 + 40 + 2LL * 3LL, &a_3));

  /* Line: 161       : EXIT PARAGRAPH     : attack.cob */
  goto l_12;

  /* Implicit EXIT label */
  l_12:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  ATTACK_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize KNIGHT-OFF: init first record */
  {
    /* initialize field KNIGHT-OFF */
    cob_move ((cob_field *)&c_4, COB_SET_FLD (f0, 2, b_55, &a_3));
    /* initialize KNIGHT-OFF: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_55;
      memcpy (b_ptr +      2, b_ptr,      2);    /* KNIGHT-OFF:     2 thru 2 */
      memcpy (b_ptr +      4, b_ptr,      4);    /* KNIGHT-OFF:     3 thru 4 */
      memcpy (b_ptr +      8, b_ptr,      8);    /* KNIGHT-OFF:     5 thru 8 */
    }
  }
  /* initialize KING-OFF: init first record */
  {
    /* initialize field KING-OFF */
    cob_move ((cob_field *)&c_4, COB_SET_FLD (f0, 2, b_55 + 16, &a_3));
    /* initialize KING-OFF: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_55 + 16;
      memcpy (b_ptr +      2, b_ptr,      2);    /* KING-OFF:     2 thru 2 */
      memcpy (b_ptr +      4, b_ptr,      4);    /* KING-OFF:     3 thru 4 */
      memcpy (b_ptr +      8, b_ptr,      8);    /* KING-OFF:     5 thru 8 */
    }
  }
  /* initialize BISHOP-OFF: init first record */
  {
    /* initialize field BISHOP-OFF */
    cob_move ((cob_field *)&c_4, COB_SET_FLD (f0, 2, b_55 + 32, &a_3));
    /* initialize BISHOP-OFF: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_55 + 32;
      memcpy (b_ptr +      2, b_ptr,      2);    /* BISHOP-OFF:     2 thru 2 */
      memcpy (b_ptr +      4, b_ptr,      4);    /* BISHOP-OFF:     3 thru 4 */
    }
  }
  /* initialize ROOK-OFF: init first record */
  {
    /* initialize field ROOK-OFF */
    cob_move ((cob_field *)&c_4, COB_SET_FLD (f0, 2, b_55 + 40, &a_3));
    /* initialize ROOK-OFF: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_55 + 40;
      memcpy (b_ptr +      2, b_ptr,      2);    /* ROOK-OFF:     2 thru 2 */
      memcpy (b_ptr +      4, b_ptr,      4);    /* ROOK-OFF:     3 thru 4 */
    }
  }

  /* initialize field OFFSETS-INIT */
  cob_move ((cob_field *)&c_4, &f_60);

  /* initialize field I */
  memset (b_61, 0x0, 2);

  /* initialize field DIR */
  memset (b_62, 0x0, 2);

  /* initialize field SQ */
  memset (b_63, 0x0, 2);

  /* initialize field IDX */
  memset (b_64, 0x0, 2);

  /* initialize field P */
  memset (b_65, 0x0, 2);


  /* Set Decimal Constant values */
  dc_3 = &kc_3;
  cob_decimal_init (dc_3);
  cob_decimal_set_field (dc_3, (cob_field *)&c_3);

  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_3);
  dc_3 = NULL;
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'ATTACK' */

/* Initialize module structure for ATTACK */
static void ATTACK_module_init (cob_module *module)
{
  module->module_name = "ATTACK";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())ATTACK;
  module->module_cancel.funcptr = (void *(*)())ATTACK_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 4;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

