/* Generated by           cobc 3.2.0 */
/* Generated from         board.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE        "board.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 05:30:21"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        53021

/* Global variables */
#include "board.c.h"

/* Function prototypes */

COB_EXT_EXPORT int        BOARD (cob_u8_t *);
static int        BOARD_ (const int, cob_u8_t *);
static void        BOARD_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'BOARD' */

/* ENTRY 'BOARD' */

int
BOARD (cob_u8_t *b_56)
{
  cob_u8_t *cob_parm_56 = NULL;    /* linkage for GAME-STATE */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
      cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
      cob_call_params = 1;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_56 = b_56;
  }

  return BOARD_ (0, cob_parm_56);
}

static int
BOARD_ (const int entry, cob_u8_t *b_56)
{
  /* Program local variables */
  #include "board.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_56 = b_56;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 14        : Entry     BOARD                   : board.cob */
  l_2:;

  /* Line: 14        : PERFORM            : board.cob */
  cob_move ((cob_field *)&c_1, &f_55);
  for (;;)
  {
    /* Line: 14        : UNTIL              : board.cob */
    if (((int)cob_cmp_s16 (b_55, 128LL) > 0))
      break;

    /* Line: 15        : MOVE               : board.cob */
    cob_move ((cob_field *)&c_2, COB_SET_FLD (f0, 2, b_56 + 2LL * ((cob_s64_t)((*(short *)(b_55))) - 1), &a_2));
    /* Line: 14        : VARYING            : board.cob */
    cob_add_s16 (b_55, 1);
  }

  /* Line: 18        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_2, COB_SET_DATA (f_59, b_56 + 256));

  /* Line: 19        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_2, COB_SET_DATA (f_60, b_56 + 258));

  /* Line: 20        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_3, COB_SET_DATA (f_61, b_56 + 260));

  /* Line: 21        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_2, COB_SET_DATA (f_62, b_56 + 262));

  /* Line: 22        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_1, COB_SET_DATA (f_63, b_56 + 264));

  /* Line: 23        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_3, COB_SET_FLD (f0, 2, b_56 + 266, &a_2));

  /* Line: 24        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_3, COB_SET_FLD (f0, 2, b_56 + 266 + 2LL * 1LL, &a_2));

  /* Line: 25        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_2, COB_SET_DATA (f_66, b_56 + 270));

  /* Line: 26        : MOVE               : board.cob */
  cob_move ((cob_field *)&c_2, COB_SET_DATA (f_67, b_56 + 272));

  /* Line: 28        : GOBACK             : board.cob */
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  BOARD_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field I */
  memset (b_55, 0x0, 2);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'BOARD' */

/* Initialize module structure for BOARD */
static void BOARD_module_init (cob_module *module)
{
  module->module_name = "BOARD";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())BOARD;
  module->module_cancel.funcptr = (void *(*)())BOARD_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

