/* Generated by           cobc 3.2.0 */
/* Generated from         board.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'BOARD' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */
static unsigned char    *b_78 = NULL;  /* MOVE-REC */
static unsigned char    *b_84 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_56;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_55[2] __attribute__((aligned));    /* I */

/* End of local data storage */


/* Fields (local) */
static cob_field f_55    = {2, b_55, &a_2};    /* I */
static cob_field f_59    = {2, NULL, &a_2};    /* GS-SIDE-TO-MOVE */
static cob_field f_60    = {2, NULL, &a_2};    /* GS-CASTLING */
static cob_field f_61    = {2, NULL, &a_2};    /* GS-EP-SQ */
static cob_field f_62    = {2, NULL, &a_2};    /* GS-HALFMOVE */
static cob_field f_63    = {2, NULL, &a_2};    /* GS-FULLMOVE */
static cob_field f_66    = {2, NULL, &a_2};    /* GS-PLY */
static cob_field f_67    = {8, NULL, &a_4};    /* GS-KEY */

/* End of fields */

