/* Generated by           cobc 3.2.0 */
/* Generated from         fen.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */


/* Module path */
static const char        *cob_module_path = NULL;

/* Number of call parameters */
static int        cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =    {0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_2 =    {0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_3 =    {0x10,  10,   0, 0x1000, NULL};
static const cob_field_attr a_4 =    {0x10,   5,   0, 0x1000, NULL};
static const cob_field_attr a_5 =    {0x11,   4,   0, 0x0041, NULL};
static const cob_field_attr a_6 =    {0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_7 =    {0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_8 =    {0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_9 =    {0x10,   1,   0, 0x0007, NULL};
static const cob_field_attr a_10 =    {0x11,  18,   0, 0x0041, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1    = {2, (cob_u8_ptr)"16", &a_1};
static const cob_field c_2    = {1, (cob_u8_ptr)"1", &a_2};
static const cob_field c_3    = {10, (cob_u8_ptr)"1103515245", &a_3};
static const cob_field c_4    = {5, (cob_u8_ptr)"12345", &a_4};
static const cob_field c_5    = {1, (cob_u8_ptr)"0", &a_2};
static const cob_field c_6    = {1, (cob_u8_ptr)"7", &a_2};
static const cob_field c_7    = {3, (cob_u8_ptr)"128", &a_8};
static const cob_field c_8    = {2, (cob_u8_ptr)"-1", &a_9};
static const cob_field c_9    = {1, (cob_u8_ptr)"2", &a_2};
static const cob_field c_10    = {1, (cob_u8_ptr)"3", &a_2};
static const cob_field c_11    = {1, (cob_u8_ptr)"4", &a_2};
static const cob_field c_12    = {1, (cob_u8_ptr)"5", &a_2};
static const cob_field c_13    = {1, (cob_u8_ptr)"6", &a_2};
static const cob_field c_14    = {10, (cob_u8_ptr)"2147483647", &a_3};
static const cob_field c_15    = {1, (cob_u8_ptr)"8", &a_2};
static const cob_field c_16    = {1, (cob_u8_ptr)"9", &a_2};
static const cob_field c_17    = {2, (cob_u8_ptr)"10", &a_1};
static const cob_field c_18    = {2, (cob_u8_ptr)"11", &a_1};
static const cob_field c_19    = {2, (cob_u8_ptr)"12", &a_1};

static cob_field cob_all_space    = {1, (cob_u8_ptr)" ", &cob_all_attr};


static COB_INLINE COB_A_INLINE int
cob_cmp_s16 (const void *p, const cob_s64_t n)
{
    short    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 2);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE int
cob_cmp_s64 (const void *p, const cob_s64_t n)
{
    cob_s64_t    val;
    void        *x;
    x = &val;
    optim_memcpy (x, p, 8);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_add_s16 (void *p, const int val)
{
    void    *x;
    short    n;
    x = &n;
    optim_memcpy (x, p, 2);
    n += val;
    optim_memcpy (p, x, 2);
}


static COB_INLINE COB_A_INLINE void
cob_add_s64 (void *p, const int val)
{
    void        *x;
    cob_s64_t    n;
    x = &n;
    optim_memcpy (x, p, 8);
    n += val;
    optim_memcpy (p, x, 8);
}


static COB_INLINE COB_A_INLINE void
cob_sub_s16 (void *p, const int val)
{
    void    *x;
    short    n;
    x = &n;
    optim_memcpy (x, p, 2);
    n -= val;
    optim_memcpy (p, x, 2);
}


static COB_INLINE COB_A_INLINE void
cob_sub_s64 (void *p, const int val)
{
    void        *x;
    cob_s64_t    n;
    x = &n;
    optim_memcpy (x, p, 8);
    n -= val;
    optim_memcpy (p, x, 8);
}


/* Decimal constants */
static    cob_decimal    kc_1;
static    cob_decimal    *dc_1 = NULL;
static    cob_decimal    kc_2;
static    cob_decimal    *dc_2 = NULL;
static    cob_decimal    kc_3;
static    cob_decimal    *dc_3 = NULL;
static    cob_decimal    kc_4;
static    cob_decimal    *dc_4 = NULL;

