/* Generated by           cobc 3.2.0 */
/* Generated from         fen.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'FEN' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;

/* EXTERNAL items */
static unsigned char    *b_58 = NULL;  /* HASH-STATE */


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */
static unsigned char    *b_112 = NULL;  /* MOVE-REC */
static unsigned char    *b_118 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_90;
static unsigned char    *last_b_126;
static unsigned char    *last_b_127;

/* Call pointers */
static cob_call_union    call_BOARD;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_66[128] __attribute__((aligned));    /* WS-FIELD1 */
static cob_u8_t    b_67[8] __attribute__((aligned));    /* WS-FIELD2 */
static cob_u8_t    b_68[16] __attribute__((aligned));    /* WS-FIELD3 */
static cob_u8_t    b_69[8] __attribute__((aligned));    /* WS-FIELD4 */
static cob_u8_t    b_70[16] __attribute__((aligned));    /* WS-FIELD5 */
static cob_u8_t    b_71[16] __attribute__((aligned));    /* WS-FIELD6 */
static cob_u8_t    b_72[2] __attribute__((aligned));    /* WS-POS */
static cob_u8_t    b_73[2] __attribute__((aligned));    /* WS-RANK */
static cob_u8_t    b_74[2] __attribute__((aligned));    /* WS-FILE */
static cob_u8_t    b_75[2] __attribute__((aligned));    /* WS-SQ */
static cob_u8_t    b_76[2] __attribute__((aligned));    /* WS-IDX */
static cob_u8_t    b_77[2] __attribute__((aligned));    /* WS-N */
static cob_u8_t    b_78[1] __attribute__((aligned));    /* WS-CH */
static cob_u8_t    b_79[2] __attribute__((aligned));    /* WS-PIECE */
static cob_u8_t    b_80[2] __attribute__((aligned));    /* WS-LEN */
static cob_u8_t    b_81[16] __attribute__((aligned));    /* WS-TMP */
static cob_u8_t    b_82[2] __attribute__((aligned));    /* WS-I */
static cob_u8_t    b_83[2] __attribute__((aligned));    /* WS-LEN2 */
static cob_u8_t    b_84[2] __attribute__((aligned));    /* H-P */
static cob_u8_t    b_85[2] __attribute__((aligned));    /* H-S */
static cob_u8_t    b_86[8] __attribute__((aligned));    /* H-TMP */
static cob_u8_t    b_87[8] __attribute__((aligned));    /* H-KEY */
static cob_u8_t    b_88[2] __attribute__((aligned));    /* H-CAST-IX */
static cob_u8_t    b_89[2] __attribute__((aligned));    /* H-EP-IX */

/* End of local data storage */


/* Fields (local) */
static cob_field f_59    = {2, NULL, &a_5};    /* HS-INIT */
static cob_field f_60    = {8, NULL, &a_10};    /* HS-SEED */
static cob_field f_63    = {8, NULL, &a_10};    /* HS-SIDEKEY */
static cob_field f_66    = {128, b_66, &a_7};    /* WS-FIELD1 */
static cob_field f_67    = {8, b_67, &a_7};    /* WS-FIELD2 */
static cob_field f_68    = {16, b_68, &a_7};    /* WS-FIELD3 */
static cob_field f_69    = {8, b_69, &a_7};    /* WS-FIELD4 */
static cob_field f_70    = {16, b_70, &a_7};    /* WS-FIELD5 */
static cob_field f_71    = {16, b_71, &a_7};    /* WS-FIELD6 */
static cob_field f_72    = {2, b_72, &a_5};    /* WS-POS */
static cob_field f_73    = {2, b_73, &a_5};    /* WS-RANK */
static cob_field f_74    = {2, b_74, &a_5};    /* WS-FILE */
static cob_field f_75    = {2, b_75, &a_5};    /* WS-SQ */
static cob_field f_76    = {2, b_76, &a_5};    /* WS-IDX */
static cob_field f_77    = {2, b_77, &a_5};    /* WS-N */
static cob_field f_78    = {1, b_78, &a_7};    /* WS-CH */
static cob_field f_79    = {2, b_79, &a_5};    /* WS-PIECE */
static cob_field f_80    = {2, b_80, &a_5};    /* WS-LEN */
static cob_field f_82    = {2, b_82, &a_5};    /* WS-I */
static cob_field f_83    = {2, b_83, &a_5};    /* WS-LEN2 */
static cob_field f_84    = {2, b_84, &a_5};    /* H-P */
static cob_field f_85    = {2, b_85, &a_5};    /* H-S */
static cob_field f_86    = {8, b_86, &a_10};    /* H-TMP */
static cob_field f_87    = {8, b_87, &a_10};    /* H-KEY */
static cob_field f_88    = {2, b_88, &a_5};    /* H-CAST-IX */
static cob_field f_89    = {2, b_89, &a_5};    /* H-EP-IX */
static cob_field f_90    = {5912, NULL, &a_6};    /* GAME-STATE */
static cob_field f_93    = {2, NULL, &a_5};    /* GS-SIDE-TO-MOVE */
static cob_field f_94    = {2, NULL, &a_5};    /* GS-CASTLING */
static cob_field f_95    = {2, NULL, &a_5};    /* GS-EP-SQ */
static cob_field f_96    = {2, NULL, &a_5};    /* GS-HALFMOVE */
static cob_field f_97    = {2, NULL, &a_5};    /* GS-FULLMOVE */
static cob_field f_100    = {2, NULL, &a_5};    /* GS-PLY */
static cob_field f_126    = {256, NULL, &a_7};    /* L-FEN */
static cob_field f_127    = {2, NULL, &a_5};    /* L-STATUS */

/* End of fields */

