/* Generated by           cobc 3.2.0 */
/* Generated from         main.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'COBOCHESS' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union    call_BOARD;
static cob_call_union    call_FEN;
static cob_call_union    call_PERFT;
static cob_call_union    call_SEARCH;
static cob_call_union    call_MOVEGEN;
static cob_call_union    call_MOVE2UCI;
static cob_call_union    call_MAKEMOVE;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[6];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_55[5912] __attribute__((aligned));    /* GAME-STATE */
static cob_u8_t    b_77[12] __attribute__((aligned));    /* MOVE-REC */
static cob_u8_t    b_83[3074] __attribute__((aligned));    /* MOVE-LIST */
static cob_u8_t    b_91[80] __attribute__((aligned));    /* STARTPOS-FEN */
static cob_u8_t    b_92[2] __attribute__((aligned));    /* ARG-COUNT */
static cob_u8_t    b_93[2] __attribute__((aligned));    /* ARG-I */
static cob_u8_t    b_94[256] __attribute__((aligned));    /* ARG1 */
static cob_u8_t    b_95[256] __attribute__((aligned));    /* ARG2 */
static cob_u8_t    b_96[256] __attribute__((aligned));    /* ARG3 */
static cob_u8_t    b_97[2] __attribute__((aligned));    /* FEN-STATUS */
static cob_u8_t    b_98[2] __attribute__((aligned));    /* DEPTH */
static cob_u8_t    b_99[8] __attribute__((aligned));    /* NODES */
static cob_u8_t    b_100[18] __attribute__((aligned));    /* NODES-DISP */
static cob_u8_t    b_101[2] __attribute__((aligned));    /* QUIT-FLAG */
static cob_u8_t    b_102[4096] __attribute__((aligned));    /* IN-LINE */
static cob_u8_t    b_103[2] __attribute__((aligned));    /* LINE-LEN */
static cob_u8_t    b_104[2] __attribute__((aligned));    /* POS-MOVES */
static cob_u8_t    b_105[2] __attribute__((aligned));    /* MOVES-START */
static cob_u8_t    b_106[2] __attribute__((aligned));    /* FEN-START */
static cob_u8_t    b_107[4096] __attribute__((aligned));    /* POS-TMP */
static cob_u8_t    b_108[256] __attribute__((aligned));    /* FEN-BUF */
static cob_u8_t    b_109[2] __attribute__((aligned));    /* PTR */
static cob_u8_t    b_110[8] __attribute__((aligned));    /* MOVE-TOK */
static cob_u8_t    b_111[2] __attribute__((aligned));    /* MOVE-TOK-LEN */
static cob_u8_t    b_112[256] __attribute__((aligned));    /* TOK */
static cob_u8_t    b_113[2] __attribute__((aligned));    /* TOK-LEN */
static cob_u8_t    b_114[128] __attribute__((aligned));    /* FEN-F1 */
static cob_u8_t    b_115[16] __attribute__((aligned));    /* FEN-F2 */
static cob_u8_t    b_116[16] __attribute__((aligned));    /* FEN-F3 */
static cob_u8_t    b_117[16] __attribute__((aligned));    /* FEN-F4 */
static cob_u8_t    b_118[16] __attribute__((aligned));    /* FEN-F5 */
static cob_u8_t    b_119[16] __attribute__((aligned));    /* FEN-F6 */
static cob_u8_t    b_120[2] __attribute__((aligned));    /* FOUND */
static cob_u8_t    b_121[2] __attribute__((aligned));    /* OK */
static cob_u8_t    b_122[2] __attribute__((aligned));    /* I */
static cob_u8_t    b_123[2] __attribute__((aligned));    /* CAP-ONLY */
static cob_u8_t    b_124[8] __attribute__((aligned));    /* UCI-BUF */
static cob_u8_t    b_125[1280] __attribute__((aligned));    /* GO-TOKENS */
static cob_u8_t    b_127[2] __attribute__((aligned));    /* DEPTH-SET */
static cob_u8_t    b_128[2] __attribute__((aligned));    /* MOVETIME-SET */
static cob_u8_t    b_129[2] __attribute__((aligned));    /* MAX-DEPTH */
static cob_u8_t    b_130[4] __attribute__((aligned));    /* MOVETIME-MS */
static cob_u8_t    b_131[8] __attribute__((aligned));    /* TIME-LIMIT-CS */
static cob_u8_t    b_132[4] __attribute__((aligned));    /* WTIME */
static cob_u8_t    b_133[4] __attribute__((aligned));    /* BTIME */
static cob_u8_t    b_134[4] __attribute__((aligned));    /* WINC */
static cob_u8_t    b_135[4] __attribute__((aligned));    /* BINC */
static cob_u8_t    b_136[4] __attribute__((aligned));    /* MOVESTOGO */
static cob_u8_t    b_137[8] __attribute__((aligned));    /* REMAINING */
static cob_u8_t    b_138[8] __attribute__((aligned));    /* INC */
static cob_u8_t    b_139[4] __attribute__((aligned));    /* MTS */
static cob_u8_t    b_140[8] __attribute__((aligned));    /* THINK-MS */
static cob_u8_t    b_141[8] __attribute__((aligned));    /* CAP-MS */
static cob_u8_t    b_142[8] __attribute__((aligned));    /* SAFE-REM */
static cob_u8_t    b_143[4] __attribute__((aligned));    /* OUT-SCORE */
static cob_u8_t    b_144[8] __attribute__((aligned));    /* OUT-NODES */

/* End of local data storage */


/* Fields (local) */
static cob_field f_55    = {5912, b_55, &a_3};    /* GAME-STATE */
static cob_field f_77    = {12, b_77, &a_3};    /* MOVE-REC */
static cob_field f_82    = {4, b_77 + 8, &a_10};    /* M-SCORE */
static cob_field f_83    = {3074, b_83, &a_3};    /* MOVE-LIST */
static cob_field f_91    = {80, b_91, &a_5};    /* STARTPOS-FEN */
static cob_field f_92    = {2, b_92, &a_4};    /* ARG-COUNT */
static cob_field f_94    = {256, b_94, &a_5};    /* ARG1 */
static cob_field f_95    = {256, b_95, &a_5};    /* ARG2 */
static cob_field f_96    = {256, b_96, &a_5};    /* ARG3 */
static cob_field f_97    = {2, b_97, &a_7};    /* FEN-STATUS */
static cob_field f_98    = {2, b_98, &a_7};    /* DEPTH */
static cob_field f_99    = {8, b_99, &a_8};    /* NODES */
static cob_field f_100    = {18, b_100, &a_9};    /* NODES-DISP */
static cob_field f_101    = {2, b_101, &a_7};    /* QUIT-FLAG */
static cob_field f_102    = {4096, b_102, &a_5};    /* IN-LINE */
static cob_field f_103    = {2, b_103, &a_7};    /* LINE-LEN */
static cob_field f_108    = {256, b_108, &a_5};    /* FEN-BUF */
static cob_field f_109    = {2, b_109, &a_7};    /* PTR */
static cob_field f_110    = {8, b_110, &a_5};    /* MOVE-TOK */
static cob_field f_112    = {256, b_112, &a_5};    /* TOK */
static cob_field f_113    = {2, b_113, &a_7};    /* TOK-LEN */
static cob_field f_114    = {128, b_114, &a_5};    /* FEN-F1 */
static cob_field f_115    = {16, b_115, &a_5};    /* FEN-F2 */
static cob_field f_116    = {16, b_116, &a_5};    /* FEN-F3 */
static cob_field f_117    = {16, b_117, &a_5};    /* FEN-F4 */
static cob_field f_118    = {16, b_118, &a_5};    /* FEN-F5 */
static cob_field f_119    = {16, b_119, &a_5};    /* FEN-F6 */
static cob_field f_120    = {2, b_120, &a_7};    /* FOUND */
static cob_field f_121    = {2, b_121, &a_7};    /* OK */
static cob_field f_122    = {2, b_122, &a_7};    /* I */
static cob_field f_123    = {2, b_123, &a_7};    /* CAP-ONLY */
static cob_field f_124    = {8, b_124, &a_5};    /* UCI-BUF */
static cob_field f_127    = {2, b_127, &a_7};    /* DEPTH-SET */
static cob_field f_128    = {2, b_128, &a_7};    /* MOVETIME-SET */
static cob_field f_129    = {2, b_129, &a_7};    /* MAX-DEPTH */
static cob_field f_130    = {4, b_130, &a_10};    /* MOVETIME-MS */
static cob_field f_131    = {8, b_131, &a_8};    /* TIME-LIMIT-CS */
static cob_field f_132    = {4, b_132, &a_10};    /* WTIME */
static cob_field f_133    = {4, b_133, &a_10};    /* BTIME */
static cob_field f_134    = {4, b_134, &a_10};    /* WINC */
static cob_field f_135    = {4, b_135, &a_10};    /* BINC */
static cob_field f_136    = {4, b_136, &a_10};    /* MOVESTOGO */
static cob_field f_137    = {8, b_137, &a_8};    /* REMAINING */
static cob_field f_138    = {8, b_138, &a_8};    /* INC */
static cob_field f_139    = {4, b_139, &a_10};    /* MTS */
static cob_field f_140    = {8, b_140, &a_8};    /* THINK-MS */
static cob_field f_141    = {8, b_141, &a_8};    /* CAP-MS */
static cob_field f_142    = {8, b_142, &a_8};    /* SAFE-REM */
static cob_field f_143    = {4, b_143, &a_10};    /* OUT-SCORE */
static cob_field f_144    = {8, b_144, &a_8};    /* OUT-NODES */

/* End of fields */

