/* Generated by           cobc 3.2.0 */
/* Generated from         main.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */


/* Module path */
static const char        *cob_module_path = NULL;

/* Number of call parameters */
static int        cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
    {'Z', 17},
    {'9', 1},
    {'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =    {0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_2 =    {0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_3 =    {0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_4 =    {0x11,   4,   0, 0x0040, NULL};
static const cob_field_attr a_5 =    {0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_6 =    {0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_7 =    {0x11,   4,   0, 0x0041, NULL};
static const cob_field_attr a_8 =    {0x11,  18,   0, 0x0041, NULL};
static const cob_field_attr a_9 =    {0x24,  18,   0, 0x0000, p_1};
static const cob_field_attr a_10 =    {0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_11 =    {0x10,   4,   0, 0x1000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1    = {2, (cob_u8_ptr)"10", &a_1};
static const cob_field c_2    = {1, (cob_u8_ptr)"8", &a_2};
static const cob_field c_3    = {1, (cob_u8_ptr)"2", &a_2};
static const cob_field c_4    = {16, (cob_u8_ptr)"--perft-startpos", &a_6};
static const cob_field c_5    = {6, (cob_u8_ptr)"nodes=", &a_6};
static const cob_field c_6    = {7, (cob_u8_ptr)"--perft", &a_6};
static const cob_field c_7    = {3, (cob_u8_ptr)"uci", &a_6};
static const cob_field c_8    = {17, (cob_u8_ptr)"id name cobochess", &a_6};
static const cob_field c_9    = {13, (cob_u8_ptr)"id author you", &a_6};
static const cob_field c_10    = {52, (cob_u8_ptr)"option name Hash type spin default 16 min 1 max 1024", &a_6};
static const cob_field c_11    = {5, (cob_u8_ptr)"uciok", &a_6};
static const cob_field c_12    = {1, (cob_u8_ptr)"0", &a_2};
static const cob_field c_13    = {7, (cob_u8_ptr)"isready", &a_6};
static const cob_field c_14    = {7, (cob_u8_ptr)"readyok", &a_6};
static const cob_field c_15    = {10, (cob_u8_ptr)"ucinewgame", &a_6};
static const cob_field c_16    = {4, (cob_u8_ptr)"stop", &a_6};
static const cob_field c_17    = {4, (cob_u8_ptr)"quit", &a_6};
static const cob_field c_18    = {1, (cob_u8_ptr)"1", &a_2};
static const cob_field c_19    = {8, (cob_u8_ptr)"position", &a_6};
static const cob_field c_20    = {8, (cob_u8_ptr)"startpos", &a_6};
static const cob_field c_21    = {5, (cob_u8_ptr)"moves", &a_6};
static const cob_field c_22    = {3, (cob_u8_ptr)"fen", &a_6};
static const cob_field c_23    = {1, (cob_u8_ptr)" ", &a_6};
static const cob_field c_24    = {4, (cob_u8_ptr)"4096", &a_11};
static const cob_field c_25    = {2, (cob_u8_ptr)"64", &a_1};
static const cob_field c_26    = {5, (cob_u8_ptr)"depth", &a_6};
static const cob_field c_27    = {8, (cob_u8_ptr)"movetime", &a_6};
static const cob_field c_28    = {5, (cob_u8_ptr)"wtime", &a_6};
static const cob_field c_29    = {5, (cob_u8_ptr)"btime", &a_6};
static const cob_field c_30    = {4, (cob_u8_ptr)"winc", &a_6};
static const cob_field c_31    = {4, (cob_u8_ptr)"binc", &a_6};
static const cob_field c_32    = {9, (cob_u8_ptr)"movestogo", &a_6};
static const cob_field c_33    = {9, (cob_u8_ptr)"bestmove ", &a_6};
static const cob_field c_34    = {2, (cob_u8_ptr)"22", &a_1};
static const cob_field c_35    = {2, (cob_u8_ptr)"60", &a_1};
static const cob_field c_36    = {2, (cob_u8_ptr)"20", &a_1};

static cob_field cob_all_space    = {1, (cob_u8_ptr)" ", &cob_all_attr};
static cob_field cob_all_zero    = {1, (cob_u8_ptr)"0", &cob_all_attr};


static COB_INLINE COB_A_INLINE int
cob_cmp_u16 (const void *p, const cob_s64_t n)
{
    void        *x;
    unsigned short    val;
    if (unlikely(n < 0)) {
        return 1;
    }
    x = &val;
    optim_memcpy (x, p, 2);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE int
cob_cmp_s16 (const void *p, const cob_s64_t n)
{
    short    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 2);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE int
cob_cmp_s32 (const void *p, const cob_s64_t n)
{
    int    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 4);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE int
cob_cmp_s64 (const void *p, const cob_s64_t n)
{
    cob_s64_t    val;
    void        *x;
    x = &val;
    optim_memcpy (x, p, 8);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_add_s16 (void *p, const int val)
{
    void    *x;
    short    n;
    x = &n;
    optim_memcpy (x, p, 2);
    n += val;
    optim_memcpy (p, x, 2);
}


static COB_INLINE COB_A_INLINE void
cob_sub_s16 (void *p, const int val)
{
    void    *x;
    short    n;
    x = &n;
    optim_memcpy (x, p, 2);
    n -= val;
    optim_memcpy (p, x, 2);
}


static COB_INLINE COB_A_INLINE void
cob_sub_s64 (void *p, const int val)
{
    void        *x;
    cob_s64_t    n;
    x = &n;
    optim_memcpy (x, p, 8);
    n -= val;
    optim_memcpy (p, x, 8);
}


/* Decimal constants */
static    cob_decimal    kc_1;
static    cob_decimal    *dc_1 = NULL;
static    cob_decimal    kc_2;
static    cob_decimal    *dc_2 = NULL;
static    cob_decimal    kc_3;
static    cob_decimal    *dc_3 = NULL;

