/* Generated by           cobc 3.2.0 */
/* Generated from         main.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE        "main.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 05:30:21"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        53021

/* Global variables */
#include "main.c.h"

/* Function prototypes */

COB_EXT_EXPORT int        COBOCHESS (void);
static int        COBOCHESS_ (const int);
static void        COBOCHESS_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'COBOCHESS' */

/* ENTRY 'COBOCHESS' */

int
COBOCHESS ()
{
  return COBOCHESS_ (0);
}

static int
COBOCHESS_ (const int entry)
{
  /* Program local variables */
  #include "main.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 77        : Entry     COBOCHESS               : main.cob */
  l_2:;

  /* Line: 77        : CALL               : main.cob */
  cob_procedure_params[0] = &f_55;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_BOARD.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_BOARD.funcvoid = cob_resolve_cobol ("BOARD", 0, 1);
  }
  b_2 = ((int (*)(void *))call_BOARD.funcint) (b_55);

  /* Line: 79        : ACCEPT             : main.cob */
  cob_accept_arg_number (&f_92);

  /* Line: 80        : IF                 : main.cob */
  if (((int)cob_cmp_u16 (b_92, 0LL) > 0))
  {

    /* Line: 81        : ACCEPT             : main.cob */
    cob_accept_arg_value (&f_94);

    /* Line: 82        : IF                 : main.cob */
    if (((int)cob_cmp_u16 (b_92, 1LL) > 0))
    {

      /* Line: 82        : ACCEPT             : main.cob */
      cob_accept_arg_value (&f_95);
    }

    /* Line: 83        : IF                 : main.cob */
    if (((int)cob_cmp_u16 (b_92, 2LL) > 0))
    {

      /* Line: 83        : ACCEPT             : main.cob */
      cob_accept_arg_value (&f_96);
    }

    /* Line: 85        : IF                 : main.cob */
    if (((int)cob_cmp (&f_94, (cob_field *)&c_4) == 0))
    {

      /* Line: 86        : MOVE               : main.cob */
      cob_move (cob_intr_numval (&f_95), &f_98);

      /* Line: 87        : MOVE               : main.cob */
      cob_move (&f_91, &f_108);

      /* Line: 88        : CALL               : main.cob */
      cob_procedure_params[0] = &f_55;
      cob_procedure_params[1] = &f_108;
      cob_procedure_params[2] = &f_97;
      cob_glob_ptr->cob_call_params = 3;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_FEN.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_FEN.funcvoid = cob_resolve_cobol ("FEN", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *))call_FEN.funcint) (b_55, b_108, b_97);

      /* Line: 89        : IF                 : main.cob */
      if (((int)cob_cmp_s16 (b_97, 0LL) != 0))
      {

        /* Line: 90        : MOVE               : main.cob */
        b_2 = 1;

        /* Line: 91        : STOP RUN           : main.cob */
        cob_stop_run (b_2);
      }

      /* Line: 93        : CALL               : main.cob */
      cob_procedure_params[0] = &f_55;
      cob_procedure_params[1] = &f_98;
      cob_procedure_params[2] = &f_99;
      cob_glob_ptr->cob_call_params = 3;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_PERFT.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_PERFT.funcvoid = cob_resolve_cobol ("PERFT", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *))call_PERFT.funcint) (b_55, b_98, b_99);

      /* Line: 94        : MOVE               : main.cob */
      cob_move (&f_99, &f_100);

      /* Line: 95        : DISPLAY            : main.cob */
      cob_display (0, 1, 2, &c_5, cob_intr_trim (0, 0, &f_100, 0));

      /* Line: 96        : STOP RUN           : main.cob */
      cob_stop_run (b_2);
    }

    /* Line: 99        : IF                 : main.cob */
    if (((int)cob_cmp (&f_94, (cob_field *)&c_6) == 0))
    {

      /* Line: 100       : MOVE               : main.cob */
      memcpy (b_108, b_95, 256);

      /* Line: 101       : MOVE               : main.cob */
      cob_move (cob_intr_numval (&f_96), &f_98);

      /* Line: 102       : CALL               : main.cob */
      cob_procedure_params[0] = &f_55;
      cob_procedure_params[1] = &f_108;
      cob_procedure_params[2] = &f_97;
      cob_glob_ptr->cob_call_params = 3;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_FEN.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_FEN.funcvoid = cob_resolve_cobol ("FEN", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *))call_FEN.funcint) (b_55, b_108, b_97);

      /* Line: 103       : IF                 : main.cob */
      if (((int)cob_cmp_s16 (b_97, 0LL) != 0))
      {

        /* Line: 104       : MOVE               : main.cob */
        b_2 = 1;

        /* Line: 105       : STOP RUN           : main.cob */
        cob_stop_run (b_2);
      }

      /* Line: 107       : CALL               : main.cob */
      cob_procedure_params[0] = &f_55;
      cob_procedure_params[1] = &f_98;
      cob_procedure_params[2] = &f_99;
      cob_glob_ptr->cob_call_params = 3;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_PERFT.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_PERFT.funcvoid = cob_resolve_cobol ("PERFT", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *))call_PERFT.funcint) (b_55, b_98, b_99);

      /* Line: 108       : MOVE               : main.cob */
      cob_move (&f_99, &f_100);

      /* Line: 109       : DISPLAY            : main.cob */
      cob_display (0, 1, 2, &c_5, cob_intr_trim (0, 0, &f_100, 0));

      /* Line: 110       : STOP RUN           : main.cob */
      cob_stop_run (b_2);
    }
  }

  /* Line: 115       : PERFORM            : main.cob */
  for (;;)
  {
    /* Line: 115       : UNTIL              : main.cob */
    if (((int)cob_cmp_s16 (b_101, 1LL) == 0))
      break;

    /* Line: 116       : ACCEPT             : main.cob */
    cob_accept (&f_102);

    /* Line: 117       : MOVE               : main.cob */
    cob_move (cob_intr_trim (0, 0, &f_102, 0), &f_102);

    /* Line: 118       : IF                 : main.cob */
    if (((int)cob_cmp (&f_102, &cob_all_space) == 0))
    {

      /* Line: 119       : CONTINUE           : main.cob */
      ;
    }

    /* Line: 122       : EVALUATE           : main.cob */

    /* Line: 123       : WHEN               : main.cob */

    if (((int)cob_cmp (&f_102, (cob_field *)&c_7) == 0))
    {

      /* Line: 124       : DISPLAY            : main.cob */
      cob_display (0, 1, 1, &c_8);

      /* Line: 125       : DISPLAY            : main.cob */
      cob_display (0, 1, 1, &c_9);

      /* Line: 126       : DISPLAY            : main.cob */
      cob_display (0, 1, 1, &c_10);

      /* Line: 127       : DISPLAY            : main.cob */
      cob_display (0, 1, 1, &c_11);

      /* Line: 129       : MOVE               : main.cob */
      cob_move ((cob_field *)&c_12, &f_129);

      /* Line: 130       : MOVE               : main.cob */
      cob_move ((cob_field *)&c_12, &f_131);

      /* Line: 131       : CALL               : main.cob */
      cob_procedure_params[0] = &f_55;
      cob_procedure_params[1] = &f_129;
      cob_procedure_params[2] = &f_131;
      cob_procedure_params[3] = &f_77;
      cob_procedure_params[4] = &f_143;
      cob_procedure_params[5] = &f_144;
      cob_glob_ptr->cob_call_params = 6;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_SEARCH.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_SEARCH.funcvoid = cob_resolve_cobol ("SEARCH", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *, void *, void *, void *))call_SEARCH.funcint) (b_55, b_129, b_131, b_77, b_143, b_144);
      goto l_5;
    }

    /* Line: 132       : WHEN               : main.cob */

    if (((int)cob_cmp (&f_102, (cob_field *)&c_13) == 0))
    {

      /* Line: 133       : DISPLAY            : main.cob */
      cob_display (0, 1, 1, &c_14);
      goto l_5;
    }

    /* Line: 134       : WHEN               : main.cob */

    if (((int)cob_cmp (&f_102, (cob_field *)&c_15) == 0))
    {

      /* Line: 136       : MOVE               : main.cob */
      cob_move ((cob_field *)&c_12, &f_129);

      /* Line: 137       : MOVE               : main.cob */
      cob_move ((cob_field *)&c_12, &f_131);

      /* Line: 138       : CALL               : main.cob */
      cob_procedure_params[0] = &f_55;
      cob_procedure_params[1] = &f_129;
      cob_procedure_params[2] = &f_131;
      cob_procedure_params[3] = &f_77;
      cob_procedure_params[4] = &f_143;
      cob_procedure_params[5] = &f_144;
      cob_glob_ptr->cob_call_params = 6;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_SEARCH.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_SEARCH.funcvoid = cob_resolve_cobol ("SEARCH", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *, void *, void *, void *))call_SEARCH.funcint) (b_55, b_129, b_131, b_77, b_143, b_144);
      goto l_5;
    }

    /* Line: 139       : WHEN               : main.cob */

    if (((int)memcmp (b_102 + 0LL, (cob_u8_ptr)"position", 8) == 0))
    {

      /* Line: 140       : PERFORM            : main.cob */
      /* PERFORM HANDLE-POSITION */
      frame_ptr++;
      frame_ptr->perform_through = 6;
      frame_ptr->return_address_ptr = &&l_21;
      goto l_6;
      l_21:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 141       : WHEN               : main.cob */

    if (((int)memcmp (b_102 + 0LL, (cob_u8_ptr)"go", 2) == 0))
    {

      /* Line: 142       : PERFORM            : main.cob */
      /* PERFORM HANDLE-GO */
      frame_ptr++;
      frame_ptr->perform_through = 16;
      frame_ptr->return_address_ptr = &&l_22;
      goto l_16;
      l_22:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 143       : WHEN               : main.cob */

    if (((int)cob_cmp (&f_102, (cob_field *)&c_16) == 0))
    {

      /* Line: 144       : CONTINUE           : main.cob */
      ;
      goto l_5;
    }

    /* Line: 145       : WHEN               : main.cob */

    if (((int)cob_cmp (&f_102, (cob_field *)&c_17) == 0))
    {

      /* Line: 146       : MOVE               : main.cob */
      cob_move ((cob_field *)&c_18, &f_101);
      goto l_5;
    }

    /* WHEN OTHER */

    /* Line: 148       : CONTINUE           : main.cob */
    ;

    /* End EVALUATE */
    l_5:;
  }

  /* Line: 152       : STOP RUN           : main.cob */
  cob_stop_run (b_2);

  /* Line: 154       : Paragraph HANDLE-POSITION         : main.cob */
  l_6:;

  /* Line: 155       : PERFORM            : main.cob */
  /* PERFORM COMPUTE-LINE-LEN */
  frame_ptr++;
  frame_ptr->perform_through = 10;
  frame_ptr->return_address_ptr = &&l_23;
  goto l_10;
  l_23:
  frame_ptr--;

  /* Line: 156       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_18, &f_109);

  /* Line: 158       : PERFORM            : main.cob */
  /* PERFORM READ-TOKEN */
  frame_ptr++;
  frame_ptr->perform_through = 12;
  frame_ptr->return_address_ptr = &&l_24;
  goto l_12;
  l_24:
  frame_ptr--;

  /* Line: 159       : IF                 : main.cob */
  if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
  {

    /* Line: 159       : EXIT PARAGRAPH     : main.cob */
    goto l_7;
  }

  /* Line: 160       : IF                 : main.cob */
  if (((int)cob_cmp (cob_intr_trim (0, 0, &f_112, 0), (cob_field *)&c_19) != 0))
  {

    /* Line: 160       : EXIT PARAGRAPH     : main.cob */
    goto l_7;
  }

  /* Line: 162       : PERFORM            : main.cob */
  /* PERFORM READ-TOKEN */
  frame_ptr++;
  frame_ptr->perform_through = 12;
  frame_ptr->return_address_ptr = &&l_25;
  goto l_12;
  l_25:
  frame_ptr--;

  /* Line: 163       : IF                 : main.cob */
  if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
  {

    /* Line: 163       : EXIT PARAGRAPH     : main.cob */
    goto l_7;
  }

  /* Line: 165       : IF                 : main.cob */
  if (((int)cob_cmp (cob_intr_trim (0, 0, &f_112, 0), (cob_field *)&c_20) == 0))
  {

    /* Line: 166       : MOVE               : main.cob */
    cob_move (&f_91, &f_108);

    /* Line: 167       : CALL               : main.cob */
    cob_procedure_params[0] = &f_55;
    cob_procedure_params[1] = &f_108;
    cob_procedure_params[2] = &f_97;
    cob_glob_ptr->cob_call_params = 3;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
        if (unlikely(call_FEN.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
    {
      call_FEN.funcvoid = cob_resolve_cobol ("FEN", 0, 1);
    }
    b_2 = ((int (*)(void *, void *, void *))call_FEN.funcint) (b_55, b_108, b_97);

    /* Line: 168       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_97, 0LL) != 0))
    {

      /* Line: 168       : EXIT PARAGRAPH     : main.cob */
      goto l_7;
    }

    /* Line: 170       : PERFORM            : main.cob */
    /* PERFORM READ-TOKEN */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_26;
    goto l_12;
    l_26:
    frame_ptr--;

    /* Line: 171       : IF                 : main.cob */
    if ((((int)cob_cmp_s16 (b_113, 0LL) > 0) && 
        ((int)cob_cmp (cob_intr_trim (0, 0, &f_112, 0), (cob_field *)&c_21) == 0)))
    {

      /* Line: 172       : PERFORM            : main.cob */
      for (;;)
      {

        /* Line: 173       : PERFORM            : main.cob */
        /* PERFORM READ-TOKEN */
        frame_ptr++;
        frame_ptr->perform_through = 12;
        frame_ptr->return_address_ptr = &&l_27;
        goto l_12;
        l_27:
        frame_ptr--;

        /* Line: 174       : IF                 : main.cob */
        if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
        {

          /* Line: 174       : EXIT PERFORM       : main.cob */
          goto l_8;
        }

        /* Line: 175       : MOVE               : main.cob */
        cob_move (cob_intr_trim (0, 0, &f_112, 0), &f_110);

        /* Line: 176       : PERFORM            : main.cob */
        /* PERFORM APPLY-ONE-MOVE */
        frame_ptr++;
        frame_ptr->perform_through = 14;
        frame_ptr->return_address_ptr = &&l_28;
        goto l_14;
        l_28:
        frame_ptr--;
      }

      /* Implicit EXIT label */
      l_8:;
    }

    /* Line: 179       : EXIT PARAGRAPH     : main.cob */
    goto l_7;
  }

  /* Line: 182       : IF                 : main.cob */
  if (((int)cob_cmp (cob_intr_trim (0, 0, &f_112, 0), (cob_field *)&c_22) == 0))
  {

    /* Line: 183       : MOVE               : main.cob */
    memset (b_114, 32, 128);
    memset (b_115, 32, 16);
    memset (b_116, 32, 16);
    memset (b_117, 32, 16);
    memset (b_118, 32, 16);
    memset (b_119, 32, 16);

    /* Line: 185       : PERFORM            : main.cob */
    /* PERFORM READ-TOKEN */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_29;
    goto l_12;
    l_29:
    frame_ptr--;

    /* Line: 186       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
    {

      /* Line: 186       : EXIT PARAGRAPH     : main.cob */
      goto l_7;
    }

    /* Line: 187       : MOVE               : main.cob */
    memcpy (b_114, b_112, 128);

    /* Line: 189       : PERFORM            : main.cob */
    /* PERFORM READ-TOKEN */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_30;
    goto l_12;
    l_30:
    frame_ptr--;

    /* Line: 190       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
    {

      /* Line: 190       : EXIT PARAGRAPH     : main.cob */
      goto l_7;
    }

    /* Line: 191       : MOVE               : main.cob */
    memcpy (b_115, b_112, 16);

    /* Line: 193       : PERFORM            : main.cob */
    /* PERFORM READ-TOKEN */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_31;
    goto l_12;
    l_31:
    frame_ptr--;

    /* Line: 194       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
    {

      /* Line: 194       : EXIT PARAGRAPH     : main.cob */
      goto l_7;
    }

    /* Line: 195       : MOVE               : main.cob */
    memcpy (b_116, b_112, 16);

    /* Line: 197       : PERFORM            : main.cob */
    /* PERFORM READ-TOKEN */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_32;
    goto l_12;
    l_32:
    frame_ptr--;

    /* Line: 198       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
    {

      /* Line: 198       : EXIT PARAGRAPH     : main.cob */
      goto l_7;
    }

    /* Line: 199       : MOVE               : main.cob */
    memcpy (b_117, b_112, 16);

    /* Line: 201       : PERFORM            : main.cob */
    /* PERFORM READ-TOKEN */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_33;
    goto l_12;
    l_33:
    frame_ptr--;

    /* Line: 202       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
    {

      /* Line: 202       : EXIT PARAGRAPH     : main.cob */
      goto l_7;
    }

    /* Line: 203       : MOVE               : main.cob */
    memcpy (b_118, b_112, 16);

    /* Line: 205       : PERFORM            : main.cob */
    /* PERFORM READ-TOKEN */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_34;
    goto l_12;
    l_34:
    frame_ptr--;

    /* Line: 206       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
    {

      /* Line: 206       : EXIT PARAGRAPH     : main.cob */
      goto l_7;
    }

    /* Line: 207       : MOVE               : main.cob */
    memcpy (b_119, b_112, 16);

    /* Line: 209       : MOVE               : main.cob */
    memset (b_108, 32, 256);

    /* Line: 210       : STRING             : main.cob */
    cob_string_init (&f_108, NULL);
    cob_string_delimited (NULL);
    cob_string_append (cob_intr_trim (0, 0, &f_114, 0));
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_23);
    cob_string_delimited (NULL);
    cob_string_append (cob_intr_trim (0, 0, &f_115, 0));
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_23);
    cob_string_delimited (NULL);
    cob_string_append (cob_intr_trim (0, 0, &f_116, 0));
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_23);
    cob_string_delimited (NULL);
    cob_string_append (cob_intr_trim (0, 0, &f_117, 0));
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_23);
    cob_string_delimited (NULL);
    cob_string_append (cob_intr_trim (0, 0, &f_118, 0));
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_23);
    cob_string_delimited (NULL);
    cob_string_append (cob_intr_trim (0, 0, &f_119, 0));
    cob_string_finish ();

    /* Line: 225       : CALL               : main.cob */
    cob_procedure_params[0] = &f_55;
    cob_procedure_params[1] = &f_108;
    cob_procedure_params[2] = &f_97;
    cob_glob_ptr->cob_call_params = 3;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
        if (unlikely(call_FEN.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
    {
      call_FEN.funcvoid = cob_resolve_cobol ("FEN", 0, 1);
    }
    b_2 = ((int (*)(void *, void *, void *))call_FEN.funcint) (b_55, b_108, b_97);

    /* Line: 226       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_97, 0LL) != 0))
    {

      /* Line: 226       : EXIT PARAGRAPH     : main.cob */
      goto l_7;
    }

    /* Line: 228       : PERFORM            : main.cob */
    /* PERFORM READ-TOKEN */
    frame_ptr++;
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_35;
    goto l_12;
    l_35:
    frame_ptr--;

    /* Line: 229       : IF                 : main.cob */
    if ((((int)cob_cmp_s16 (b_113, 0LL) > 0) && 
        ((int)cob_cmp (cob_intr_trim (0, 0, &f_112, 0), (cob_field *)&c_21) == 0)))
    {

      /* Line: 230       : PERFORM            : main.cob */
      for (;;)
      {

        /* Line: 231       : PERFORM            : main.cob */
        /* PERFORM READ-TOKEN */
        frame_ptr++;
        frame_ptr->perform_through = 12;
        frame_ptr->return_address_ptr = &&l_36;
        goto l_12;
        l_36:
        frame_ptr--;

        /* Line: 232       : IF                 : main.cob */
        if (((int)cob_cmp_s16 (b_113, 0LL) == 0))
        {

          /* Line: 232       : EXIT PERFORM       : main.cob */
          goto l_9;
        }

        /* Line: 233       : MOVE               : main.cob */
        cob_move (cob_intr_trim (0, 0, &f_112, 0), &f_110);

        /* Line: 234       : PERFORM            : main.cob */
        /* PERFORM APPLY-ONE-MOVE */
        frame_ptr++;
        frame_ptr->perform_through = 14;
        frame_ptr->return_address_ptr = &&l_37;
        goto l_14;
        l_37:
        frame_ptr--;
      }

      /* Implicit EXIT label */
      l_9:;
    }

    /* Line: 237       : EXIT PARAGRAPH     : main.cob */
    goto l_7;
  }

  /* Line: 240       : EXIT PARAGRAPH     : main.cob */
  goto l_7;

  /* Implicit EXIT label */
  l_7:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 242       : Paragraph COMPUTE-LINE-LEN        : main.cob */
  l_10:;

  /* Line: 243       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_24, &f_103);

  /* Line: 244       : PERFORM            : main.cob */
  for (;;)
  {
    /* Line: 244       : UNTIL              : main.cob */
    if ((((int)cob_cmp_s16 (b_103, 0LL) == 0) || 
        ((int)(int)(*(b_102 + ((cob_s64_t)((*(short *)(b_103))) - 1)) - ' ') != 0)))
      break;

    /* Line: 245       : SUBTRACT           : main.cob */
    cob_sub_s16 (b_103, 1);
  }

  /* Line: 247       : EXIT PARAGRAPH     : main.cob */
  goto l_11;

  /* Implicit EXIT label */
  l_11:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 249       : Paragraph READ-TOKEN              : main.cob */
  l_12:;

  /* Line: 250       : MOVE               : main.cob */
  memset (b_112, 32, 256);

  /* Line: 251       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_12, &f_113);

  /* Line: 253       : PERFORM            : main.cob */
  for (;;)
  {
    /* Line: 253       : UNTIL              : main.cob */
    if ((((int)cob_cmp_s16 (b_109, (*(short *)(b_103))) > 0) || 
        ((int)(int)(*(b_102 + ((cob_s64_t)((*(short *)(b_109))) - 1)) - ' ') != 0)))
      break;

    /* Line: 254       : ADD                : main.cob */
    cob_add_s16 (b_109, 1);
  }

  /* Line: 256       : IF                 : main.cob */
  if (((int)cob_cmp_s16 (b_109, (*(short *)(b_103))) > 0))
  {

    /* Line: 257       : EXIT PARAGRAPH     : main.cob */
    goto l_13;
  }

  /* Line: 260       : PERFORM            : main.cob */
  for (;;)
  {
    /* Line: 260       : UNTIL              : main.cob */
    if ((((int)cob_cmp_s16 (b_109, (*(short *)(b_103))) > 0) || 
        ((int)(int)(*(b_102 + ((cob_s64_t)((*(short *)(b_109))) - 1)) - ' ') == 0)))
      break;

    /* Line: 261       : ADD                : main.cob */
    cob_add_s16 (b_113, 1);

    /* Line: 262       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_113, 256LL) <= 0))
    {

      /* Line: 263       : MOVE               : main.cob */
      *(b_112 + ((cob_s64_t)((*(short *)(b_113))) - 1)) = *(b_102 + ((cob_s64_t)((*(short *)(b_109))) - 1));
    }

    /* Line: 265       : ADD                : main.cob */
    cob_add_s16 (b_109, 1);
  }

  /* Line: 267       : EXIT PARAGRAPH     : main.cob */
  goto l_13;

  /* Implicit EXIT label */
  l_13:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 269       : Paragraph APPLY-ONE-MOVE          : main.cob */
  l_14:;

  /* Line: 270       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_12, &f_120);

  /* Line: 271       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_12, &f_123);

  /* Line: 272       : CALL               : main.cob */
  cob_procedure_params[0] = &f_55;
  cob_procedure_params[1] = &f_83;
  cob_procedure_params[2] = &f_123;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_MOVEGEN.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_MOVEGEN.funcvoid = cob_resolve_cobol ("MOVEGEN", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_MOVEGEN.funcint) (b_55, b_83, b_123);

  /* Line: 274       : PERFORM            : main.cob */
  cob_move ((cob_field *)&c_18, &f_122);
  for (;;)
  {
    /* Line: 274       : UNTIL              : main.cob */
    if ((((int)cob_cmp_s16 (b_122, (*(short *)(b_83))) > 0) || 
        ((int)cob_cmp_s16 (b_120, 1LL) == 0)))
      break;

    /* Line: 275       : MOVE               : main.cob */
    memcpy (b_77, b_83 + 2 + 12LL * ((cob_s64_t)((*(short *)(b_122))) - 1), 2);

    /* Line: 276       : MOVE               : main.cob */
    memcpy (b_77 + 2, b_83 + 4 + 12LL * ((cob_s64_t)((*(short *)(b_122))) - 1), 2);

    /* Line: 277       : MOVE               : main.cob */
    memcpy (b_77 + 4, b_83 + 6 + 12LL * ((cob_s64_t)((*(short *)(b_122))) - 1), 2);

    /* Line: 278       : MOVE               : main.cob */
    memcpy (b_77 + 6, b_83 + 8 + 12LL * ((cob_s64_t)((*(short *)(b_122))) - 1), 2);

    /* Line: 279       : MOVE               : main.cob */
    cob_move ((cob_field *)&c_12, &f_82);

    /* Line: 281       : CALL               : main.cob */
    cob_procedure_params[0] = &f_77;
    cob_procedure_params[1] = &f_124;
    cob_glob_ptr->cob_call_params = 2;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
        if (unlikely(call_MOVE2UCI.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
    {
      call_MOVE2UCI.funcvoid = cob_resolve_cobol ("MOVE2UCI", 0, 1);
    }
    b_2 = ((int (*)(void *, void *))call_MOVE2UCI.funcint) (b_77, b_124);

    /* Line: 282       : IF                 : main.cob */
    if (((int)cob_cmp (cob_intr_trim (0, 0, &f_124, 0), cob_intr_trim (0, 0, &f_110, 0)) == 0))
    {

      /* Line: 283       : CALL               : main.cob */
      cob_procedure_params[0] = &f_55;
      cob_procedure_params[1] = &f_77;
      cob_procedure_params[2] = &f_121;
      cob_glob_ptr->cob_call_params = 3;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_MAKEMOVE.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_MAKEMOVE.funcvoid = cob_resolve_cobol ("MAKEMOVE", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *))call_MAKEMOVE.funcint) (b_55, b_77, b_121);

      /* Line: 284       : IF                 : main.cob */
      if (((int)cob_cmp_s16 (b_121, 1LL) == 0))
      {

        /* Line: 285       : MOVE               : main.cob */
        cob_move ((cob_field *)&c_18, &f_120);
      }
    }
    /* Line: 274       : VARYING            : main.cob */
    cob_add_s16 (b_122, 1);
  }

  /* Line: 289       : EXIT PARAGRAPH     : main.cob */
  goto l_15;

  /* Implicit EXIT label */
  l_15:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address_ptr;

  /* Line: 291       : Paragraph HANDLE-GO               : main.cob */
  l_16:;

  /* Line: 292       : MOVE               : main.cob */
  memset (b_125, 32, 1280);

  /* Line: 294       : UNSTRING           : main.cob */
  cob_unstring_init (&f_102, NULL, 1);
  cob_unstring_delimited (&cob_all_space, 1);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 1LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 2LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 3LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 4LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 5LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 6LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 7LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 8LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 9LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 10LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 11LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 12LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 13LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 14LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 15LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 16LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 17LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 18LL, &a_5), 0, 0);
  cob_unstring_into (COB_SET_FLD (f0, 64, b_125 + 64LL * 19LL, &a_5), 0, 0);
  cob_unstring_finish ();

  /* Line: 301       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_25, &f_129);

  /* Line: 302       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_12, &f_131);

  /* Line: 303       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_12, &f_127);
  cob_move ((cob_field *)&c_12, &f_128);

  /* Line: 304       : MOVE               : main.cob */
  cob_move ((cob_field *)&c_12, &f_132);
  cob_move ((cob_field *)&c_12, &f_133);
  cob_move ((cob_field *)&c_12, &f_134);
  cob_move ((cob_field *)&c_12, &f_135);
  cob_move ((cob_field *)&c_12, &f_136);

  /* Line: 306       : PERFORM            : main.cob */
  cob_move ((cob_field *)&c_3, &f_122);
  for (;;)
  {
    /* Line: 306       : UNTIL              : main.cob */
    if (((int)cob_cmp_s16 (b_122, 19LL) > 0))
      break;

    /* Line: 307       : EVALUATE           : main.cob */

    /* Line: 308       : WHEN               : main.cob */

    if (((int)cob_cmp (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)((*(short *)(b_122))) - 1), &a_5), (cob_field *)&c_26) == 0))
    {

      /* Line: 309       : MOVE               : main.cob */
      cob_move (cob_intr_numval (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)(((*(short *)(b_122)) + 1)) - 1), &a_5)), &f_129);

      /* Line: 310       : MOVE               : main.cob */
      cob_move ((cob_field *)&c_18, &f_127);
      goto l_17;
    }

    /* Line: 311       : WHEN               : main.cob */

    if (((int)cob_cmp (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)((*(short *)(b_122))) - 1), &a_5), (cob_field *)&c_27) == 0))
    {

      /* Line: 312       : MOVE               : main.cob */
      cob_move (cob_intr_numval (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)(((*(short *)(b_122)) + 1)) - 1), &a_5)), &f_130);

      /* Line: 313       : DIVIDE             : main.cob */
      cob_decimal_set_llint (d_0, (*(int *)(b_130)));
      cob_decimal_div (d_0, dc_1);
      cob_decimal_get_field (d_0, &f_131, 0);

      /* Line: 314       : MOVE               : main.cob */
      cob_move ((cob_field *)&c_18, &f_128);
      goto l_17;
    }

    /* Line: 315       : WHEN               : main.cob */

    if (((int)cob_cmp (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)((*(short *)(b_122))) - 1), &a_5), (cob_field *)&c_28) == 0))
    {

      /* Line: 316       : MOVE               : main.cob */
      cob_move (cob_intr_numval (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)(((*(short *)(b_122)) + 1)) - 1), &a_5)), &f_132);
      goto l_17;
    }

    /* Line: 317       : WHEN               : main.cob */

    if (((int)cob_cmp (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)((*(short *)(b_122))) - 1), &a_5), (cob_field *)&c_29) == 0))
    {

      /* Line: 318       : MOVE               : main.cob */
      cob_move (cob_intr_numval (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)(((*(short *)(b_122)) + 1)) - 1), &a_5)), &f_133);
      goto l_17;
    }

    /* Line: 319       : WHEN               : main.cob */

    if (((int)cob_cmp (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)((*(short *)(b_122))) - 1), &a_5), (cob_field *)&c_30) == 0))
    {

      /* Line: 320       : MOVE               : main.cob */
      cob_move (cob_intr_numval (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)(((*(short *)(b_122)) + 1)) - 1), &a_5)), &f_134);
      goto l_17;
    }

    /* Line: 321       : WHEN               : main.cob */

    if (((int)cob_cmp (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)((*(short *)(b_122))) - 1), &a_5), (cob_field *)&c_31) == 0))
    {

      /* Line: 322       : MOVE               : main.cob */
      cob_move (cob_intr_numval (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)(((*(short *)(b_122)) + 1)) - 1), &a_5)), &f_135);
      goto l_17;
    }

    /* Line: 323       : WHEN               : main.cob */

    if (((int)cob_cmp (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)((*(short *)(b_122))) - 1), &a_5), (cob_field *)&c_32) == 0))
    {

      /* Line: 324       : MOVE               : main.cob */
      cob_move (cob_intr_numval (COB_SET_FLD (f0, 64, b_125 + 64LL * ((cob_s64_t)(((*(short *)(b_122)) + 1)) - 1), &a_5)), &f_136);
      goto l_17;
    }

    /* WHEN OTHER */

    /* Line: 326       : CONTINUE           : main.cob */
    ;

    /* End EVALUATE */
    l_17:;
    /* Line: 306       : VARYING            : main.cob */
    cob_add_s16 (b_122, 1);
  }

  /* Line: 330       : IF                 : main.cob */
  if (((int)cob_cmp_s16 (b_127, 1LL) == 0))
  {

    /* Line: 331       : MOVE               : main.cob */
    cob_move ((cob_field *)&c_12, &f_131);
  }
  else
  {
    /* ELSE */

    /* Line: 333       : IF                 : main.cob */
    if (((int)cob_cmp_s16 (b_128, 0LL) == 0))
    {

      /* Line: 334       : PERFORM            : main.cob */
      /* PERFORM COMPUTE-TIME-LIMIT */
      frame_ptr++;
      frame_ptr->perform_through = 19;
      frame_ptr->return_address_ptr = &&l_38;
      goto l_19;
      l_38:
      frame_ptr--;
    }
  }

  /* Line: 338       : CALL               : main.cob */
  cob_procedure_params[0] = &f_55;
  cob_procedure_params[1] = &f_129;
  cob_procedure_params[2] = &f_131;
  cob_procedure_params[3] = &f_77;
  cob_procedure_params[4] = &f_143;
  cob_procedure_params[5] = &f_144;
  cob_glob_ptr->cob_call_params = 6;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_SEARCH.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_SEARCH.funcvoid = cob_resolve_cobol ("SEARCH", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *, void *, void *, void *))call_SEARCH.funcint) (b_55, b_129, b_131, b_77, b_143, b_144);

  /* Line: 339       : CALL               : main.cob */
  cob_procedure_params[0] = &f_77;
  cob_procedure_params[1] = &f_124;
  cob_glob_ptr->cob_call_params = 2;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_MOVE2UCI.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_MOVE2UCI.funcvoid = cob_resolve_cobol ("MOVE2UCI", 0, 1);
  }
  b_2 = ((int (*)(void *, void *))call_MOVE2UCI.funcint) (b_77, b_124);

  /* Line: 340       : DISPLAY            : main.cob */
  cob_display (0, 1, 2, &c_33, cob_intr_trim (0, 0, &f_124, 0));

  /* Line: 341       : EXIT PARAGRAPH     : main.cob */
  goto l_18;

  /* Implicit EXIT label */
  l_18:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Line: 343       : Paragraph COMPUTE-TIME-LIMIT      : main.cob */
  l_19:;

  /* Line: 344       : IF                 : main.cob */
  if (((int)cob_cmp_s16 (b_55 + 256, 0LL) == 0))
  {

    /* Line: 345       : MOVE               : main.cob */
    cob_move (&f_132, &f_137);

    /* Line: 346       : MOVE               : main.cob */
    cob_move (&f_134, &f_138);
  }
  else
  {
    /* ELSE */

    /* Line: 348       : MOVE               : main.cob */
    cob_move (&f_133, &f_137);

    /* Line: 349       : MOVE               : main.cob */
    cob_move (&f_135, &f_138);
  }

  /* Line: 352       : MOVE               : main.cob */
  memcpy (b_139, b_136, 4);

  /* Line: 353       : IF                 : main.cob */
  if (((int)cob_cmp_s32 (b_139, 0LL) <= 0))
  {

    /* Line: 353       : MOVE               : main.cob */
    cob_move ((cob_field *)&c_34, &f_139);
  }

  /* Line: 354       : IF                 : main.cob */
  if (((int)cob_cmp_s32 (b_139, 10LL) < 0))
  {

    /* Line: 354       : MOVE               : main.cob */
    cob_move ((cob_field *)&c_1, &f_139);
  }

  /* Line: 355       : IF                 : main.cob */
  if (((int)cob_cmp_s32 (b_139, 60LL) > 0))
  {

    /* Line: 355       : MOVE               : main.cob */
    cob_move ((cob_field *)&c_35, &f_139);
  }

  /* Line: 358       : MOVE               : main.cob */
  memcpy (b_142, b_137, 8);

  /* Line: 359       : SUBTRACT           : main.cob */
  cob_sub_s64 (b_142, 50);

  /* Line: 360       : IF                 : main.cob */
  if (((int)cob_cmp_s64 (b_142, 0LL) < 0))
  {

    /* Line: 360       : MOVE               : main.cob */
    cob_move ((cob_field *)&c_12, &f_142);
  }

  /* Line: 362       : COMPUTE            : main.cob */
  cob_decimal_set_llint (d_0, (*(cob_s64_ptr)(b_142)));
  cob_decimal_set_llint (d_1, (*(int *)(b_139)));
  cob_decimal_div (d_0, d_1);
  cob_decimal_set_llint (d_1, (*(cob_s64_ptr)(b_138)));
  cob_decimal_mul (d_1, dc_2);
  cob_decimal_div (d_1, dc_1);
  cob_decimal_add (d_0, d_1);
  cob_decimal_get_field (d_0, &f_140, 0);

  /* Line: 363       : COMPUTE            : main.cob */
  cob_decimal_set_llint (d_0, (*(cob_s64_ptr)(b_142)));
  cob_decimal_mul (d_0, dc_3);
  cob_decimal_div (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_141, 0);

  /* Line: 364       : IF                 : main.cob */
  if (((int)cob_cmp_s64 (b_140, (*(cob_s64_ptr)(b_141))) > 0))
  {

    /* Line: 364       : MOVE               : main.cob */
    memcpy (b_140, b_141, 8);
  }

  /* Line: 366       : IF                 : main.cob */
  if (((int)cob_cmp_s64 (b_140, 20LL) < 0))
  {

    /* Line: 367       : IF                 : main.cob */
    if (((int)cob_cmp_s64 (b_142, 20LL) >= 0))
    {

      /* Line: 368       : MOVE               : main.cob */
      cob_move ((cob_field *)&c_36, &f_140);
    }
    else
    {
      /* ELSE */

      /* Line: 370       : MOVE               : main.cob */
      memcpy (b_140, b_142, 8);
    }
  }

  /* Line: 374       : IF                 : main.cob */
  if (((int)cob_cmp_s64 (b_140, (*(cob_s64_ptr)(b_142))) > 0))
  {

    /* Line: 374       : MOVE               : main.cob */
    memcpy (b_140, b_142, 8);
  }

  /* Line: 376       : DIVIDE             : main.cob */
  cob_decimal_set_llint (d_0, (*(cob_s64_ptr)(b_140)));
  cob_decimal_div (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_131, 0);

  /* Line: 377       : IF                 : main.cob */
  if (((int)cob_cmp_s64 (b_131, 1LL) < 0))
  {

    /* Line: 378       : MOVE               : main.cob */
    cob_move ((cob_field *)&c_18, &f_131);
  }

  /* Line: 380       : EXIT PARAGRAPH     : main.cob */
  goto l_20;

  /* Implicit EXIT label */
  l_20:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  COBOCHESS_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field GAME-STATE */
  memset (b_55, 0x0, 5912);

  /* initialize field MOVE-REC */
  memset (b_77, 0x0, 12);

  /* initialize field MOVE-LIST */
  memset (b_83, 0x0, 3074);

  /* initialize field STARTPOS-FEN */
  memcpy (b_91, "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1                        ", 80);

  /* initialize field ARG-COUNT */
  memset (b_92, 0x0, 2);

  /* initialize field ARG-I */
  memset (b_93, 0x0, 2);

  /* initialize field ARG1 */
  memset (b_94, (unsigned char)' ', 256);

  /* initialize field ARG2 */
  memset (b_95, (unsigned char)' ', 256);

  /* initialize field ARG3 */
  memset (b_96, (unsigned char)' ', 256);

  /* initialize field FEN-STATUS */
  memset (b_97, 0x0, 2);

  /* initialize field DEPTH */
  memset (b_98, 0x0, 2);

  /* initialize field NODES */
  memset (b_99, 0x0, 8);

  /* initialize field NODES-DISP */
  cob_move (&cob_all_zero, &f_100);

  /* initialize field QUIT-FLAG */
  cob_move ((cob_field *)&c_12, &f_101);

  /* initialize field IN-LINE */
  memset (b_102, (unsigned char)' ', 4096);

  /* initialize field LINE-LEN */
  memset (b_103, 0x0, 2);

  /* initialize field POS-MOVES */
  memset (b_104, 0x0, 2);

  /* initialize field MOVES-START */
  memset (b_105, 0x0, 2);

  /* initialize field FEN-START */
  memset (b_106, 0x0, 2);

  /* initialize field POS-TMP */
  memset (b_107, (unsigned char)' ', 4096);

  /* initialize field FEN-BUF */
  memset (b_108, (unsigned char)' ', 256);

  /* initialize field PTR */
  memset (b_109, 0x0, 2);

  /* initialize field MOVE-TOK */
  memset (b_110, (unsigned char)' ', 8);

  /* initialize field MOVE-TOK-LEN */
  memset (b_111, 0x0, 2);

  /* initialize field TOK */
  memset (b_112, (unsigned char)' ', 256);

  /* initialize field TOK-LEN */
  memset (b_113, 0x0, 2);

  /* initialize field FEN-F1 */
  memset (b_114, (unsigned char)' ', 128);

  /* initialize field FEN-F2 */
  memset (b_115, (unsigned char)' ', 16);

  /* initialize field FEN-F3 */
  memset (b_116, (unsigned char)' ', 16);

  /* initialize field FEN-F4 */
  memset (b_117, (unsigned char)' ', 16);

  /* initialize field FEN-F5 */
  memset (b_118, (unsigned char)' ', 16);

  /* initialize field FEN-F6 */
  memset (b_119, (unsigned char)' ', 16);

  /* initialize field FOUND */
  memset (b_120, 0x0, 2);

  /* initialize field OK */
  memset (b_121, 0x0, 2);

  /* initialize field I */
  memset (b_122, 0x0, 2);

  /* initialize field CAP-ONLY */
  memset (b_123, 0x0, 2);

  /* initialize field UCI-BUF */
  memset (b_124, (unsigned char)' ', 8);

  /* initialize field GO-TOKENS */
  memset (b_125, (unsigned char)' ', 1280);

  /* initialize field DEPTH-SET */
  memset (b_127, 0x0, 2);

  /* initialize field MOVETIME-SET */
  memset (b_128, 0x0, 2);

  /* initialize field MAX-DEPTH */
  memset (b_129, 0x0, 2);

  /* initialize field MOVETIME-MS */
  memset (b_130, 0x0, 4);

  /* initialize field TIME-LIMIT-CS */
  memset (b_131, 0x0, 8);

  /* initialize field WTIME */
  memset (b_132, 0x0, 4);

  /* initialize field BTIME */
  memset (b_133, 0x0, 4);

  /* initialize field WINC */
  memset (b_134, 0x0, 4);

  /* initialize field BINC */
  memset (b_135, 0x0, 4);

  /* initialize field MOVESTOGO */
  memset (b_136, 0x0, 4);

  /* initialize field REMAINING */
  memset (b_137, 0x0, 8);

  /* initialize field INC */
  memset (b_138, 0x0, 8);

  /* initialize field MTS */
  memset (b_139, 0x0, 4);

  /* initialize field THINK-MS */
  memset (b_140, 0x0, 8);

  /* initialize field CAP-MS */
  memset (b_141, 0x0, 8);

  /* initialize field SAFE-REM */
  memset (b_142, 0x0, 8);

  /* initialize field OUT-SCORE */
  memset (b_143, 0x0, 4);

  /* initialize field OUT-NODES */
  memset (b_144, 0x0, 8);


  /* Set Decimal Constant values */
  dc_3 = &kc_3;
  cob_decimal_init (dc_3);
  cob_decimal_set_field (dc_3, (cob_field *)&c_3);

  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  call_MAKEMOVE.funcvoid = NULL;
  call_MOVE2UCI.funcvoid = NULL;
  call_MOVEGEN.funcvoid = NULL;
  call_SEARCH.funcvoid = NULL;
  call_PERFT.funcvoid = NULL;
  call_FEN.funcvoid = NULL;
  call_BOARD.funcvoid = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_3);
  dc_3 = NULL;
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'COBOCHESS' */

/* Initialize module structure for COBOCHESS */
static void COBOCHESS_module_init (cob_module *module)
{
  module->module_name = "COBOCHESS";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())COBOCHESS;
  module->module_cancel.funcptr = (void *(*)())COBOCHESS_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */


int
main (int argc, char **argv)
{
  int rc;

  cob_init (argc, argv);
  rc = COBOCHESS ();
  cob_tidy ();
  return rc;
}
