/* Generated by           cobc 3.2.0 */
/* Generated from         makemove.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE        "makemove.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 05:30:21"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        53021

/* Global variables */
#include "makemove.c.h"

/* Function prototypes */

COB_EXT_EXPORT int        MAKEMOVE (cob_u8_t *, cob_u8_t *, cob_u8_t *);
static int        MAKEMOVE_ (const int, cob_u8_t *, cob_u8_t *, cob_u8_t *);
static void        MAKEMOVE_module_init (cob_module *module);
COB_EXT_EXPORT int        UNMAKEMOVE (cob_u8_t *, cob_u8_t *);
static int        UNMAKEMOVE_ (const int, cob_u8_t *, cob_u8_t *);
static void        UNMAKEMOVE_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MAKEMOVE' */

/* ENTRY 'MAKEMOVE' */

int
MAKEMOVE (cob_u8_t *b_101, cob_u8_t *b_123, cob_u8_t *b_137)
{
  cob_u8_t *cob_parm_101 = NULL;    /* linkage for GAME-STATE */
  cob_u8_t *cob_parm_123 = NULL;    /* linkage for MOVE-REC */
  cob_u8_t *cob_parm_137 = NULL;    /* linkage for L-OK */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
      cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
      cob_call_params = 3;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_101 = b_101;
  }
  if (cob_call_params > 1) {
    cob_parm_123 = b_123;
  }
  if (cob_call_params > 2) {
    cob_parm_137 = b_137;
  }

  return MAKEMOVE_ (0, cob_parm_101, cob_parm_123, cob_parm_137);
}

static int
MAKEMOVE_ (const int entry, cob_u8_t *b_101, cob_u8_t *b_123, 
    cob_u8_t *b_137)
{
  /* Program local variables */
  #include "makemove.c.l1.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (1, &d_0);

  /* Increment module active */
  module->module_active++;

  /* Increment module reference count */
  cob_reference_count++;

  /* Store last parameters for possible later lookup */
  last_b_101 = b_101;
  last_b_123 = b_123;
  last_b_137 = b_137;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 56        : Entry     MAKEMOVE                : makemove.cob */
  l_2:;

  /* Line: 56        : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, COB_SET_DATA (f_137, b_137));

  /* Line: 58        : MOVE               : makemove.cob */
  memmove (b_66, b_101 + 256, 2);

  /* Line: 59        : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
  {

    /* Line: 60        : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_67);
  }
  else
  {
    /* ELSE */

    /* Line: 62        : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_8, &f_67);
  }

  /* Line: 65        : MOVE               : makemove.cob */
  memmove (b_68, b_123, 2);

  /* Line: 66        : MOVE               : makemove.cob */
  memmove (b_69, b_123 + 2, 2);

  /* Line: 67        : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_68)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_70, 0);

  /* Line: 68        : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_69)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_71, 0);

  /* Line: 70        : MOVE               : makemove.cob */
  memmove (b_72, b_101 + 2LL * ((cob_s64_t)((*(short *)(b_70))) - 1), 2);

  /* Line: 71        : MOVE               : makemove.cob */
  memmove (b_73, b_101 + 2LL * ((cob_s64_t)((*(short *)(b_71))) - 1), 2);

  /* Line: 73        : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_111, b_101 + 270)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_74, 0);

  /* Line: 74        : MOVE               : makemove.cob */
  memmove (b_101 + 280 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_73, 2);

  /* Line: 75        : MOVE               : makemove.cob */
  memmove (b_101 + 282 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_72, 2);

  /* Line: 76        : MOVE               : makemove.cob */
  memmove (b_101 + 284 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_101 + 258, 2);

  /* Line: 77        : MOVE               : makemove.cob */
  memmove (b_101 + 286 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_101 + 260, 2);

  /* Line: 78        : MOVE               : makemove.cob */
  memmove (b_101 + 288 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_101 + 262, 2);

  /* Line: 79        : MOVE               : makemove.cob */
  memmove (b_101 + 290 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_101 + 264, 2);

  /* Line: 80        : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
  {

    /* Line: 81        : MOVE               : makemove.cob */
    memmove (b_101 + 292 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_101 + 266, 2);
  }
  else
  {
    /* ELSE */

    /* Line: 83        : MOVE               : makemove.cob */
    memmove (b_101 + 292 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_101 + 266 + 2LL * 1LL, 2);
  }

  /* Line: 85        : MOVE               : makemove.cob */
  memmove (b_101 + 294 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_101 + 272, 8);

  /* Line: 88        : PERFORM            : makemove.cob */
  /* PERFORM DECODE-FLAGS */
  frame_ptr++;
  frame_ptr->perform_through = 9;
  frame_ptr->return_address_ptr = &&l_36;
  goto l_9;
  l_36:
  frame_ptr--;

  /* Line: 90        : PERFORM            : makemove.cob */
  /* PERFORM ENSURE-HASH-INIT */
  frame_ptr++;
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_37;
  goto l_5;
  l_37:
  frame_ptr--;

  /* Line: 91        : MOVE               : makemove.cob */
  memmove (b_91, b_101 + 272, 8);

  /* Line: 94        : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_66, 1LL) == 0))
  {

    /* Line: 95        : SUBTRACT           : makemove.cob */
    cob_sub (&f_91, COB_SET_DATA (f_63, b_58 + 12298), 0);

    /* Line: 96        : IF                 : makemove.cob */
    if (((int)cob_cmp_s64 (b_91, 0LL) < 0))
    {

      /* Line: 96        : ADD                : makemove.cob */
      cob_add_s64 (b_91, 2147483647);
    }
  }

  /* Line: 99        : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_105, b_101 + 258)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_92, 0);

  /* Line: 100       : IF                 : makemove.cob */
  if ((((int)cob_cmp_s16 (b_92, 1LL) >= 0) && 
      ((int)cob_cmp_s16 (b_92, 16LL) <= 0)))
  {

    /* Line: 101       : SUBTRACT           : makemove.cob */
    cob_sub (&f_91, COB_SET_FLD (f0, 8, b_58 + 12306 + 8LL * ((cob_s64_t)((*(short *)(b_92))) - 1), &a_6), 0);

    /* Line: 102       : IF                 : makemove.cob */
    if (((int)cob_cmp_s64 (b_91, 0LL) < 0))
    {

      /* Line: 102       : ADD                : makemove.cob */
      cob_add_s64 (b_91, 2147483647);
    }
  }

  /* Line: 105       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_101 + 260, 0LL) >= 0))
  {

    /* Line: 106       : COMPUTE            : makemove.cob */
    cob_decimal_set_field (d_0, cob_intr_mod (COB_SET_DATA (f_106, b_101 + 260), (cob_field *)&c_2));
    cob_decimal_get_field (d_0, &f_93, 0);

    /* Line: 107       : COMPUTE            : makemove.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_93)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_94, 0);

    /* Line: 108       : IF                 : makemove.cob */
    if ((((int)cob_cmp_s16 (b_94, 1LL) >= 0) && 
        ((int)cob_cmp_s16 (b_94, 8LL) <= 0)))
    {

      /* Line: 109       : SUBTRACT           : makemove.cob */
      cob_sub (&f_91, COB_SET_FLD (f0, 8, b_58 + 12434 + 8LL * ((cob_s64_t)((*(short *)(b_94))) - 1), &a_6), 0);

      /* Line: 110       : IF                 : makemove.cob */
      if (((int)cob_cmp_s64 (b_91, 0LL) < 0))
      {

        /* Line: 110       : ADD                : makemove.cob */
        cob_add_s64 (b_91, 2147483647);
      }
    }
  }

  /* Line: 115       : SUBTRACT           : makemove.cob */
  cob_sub (&f_91, COB_SET_FLD (f0, 8, b_58 + 10 + 8LL * ((cob_s64_t)((*(short *)(b_70))) - 1) + 1024LL * ((cob_s64_t)((*(short *)(b_72))) - 1), &a_6), 0);

  /* Line: 116       : IF                 : makemove.cob */
  if (((int)cob_cmp_s64 (b_91, 0LL) < 0))
  {

    /* Line: 116       : ADD                : makemove.cob */
    cob_add_s64 (b_91, 2147483647);
  }

  /* Line: 119       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_77, 1LL) == 0))
  {

    /* Line: 120       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
    {

      /* Line: 121       : COMPUTE            : makemove.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_69)));
      cob_decimal_sub (d_0, dc_2);
      cob_decimal_get_field (d_0, &f_82, 0);
    }
    else
    {
      /* ELSE */

      /* Line: 123       : COMPUTE            : makemove.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_69)));
      cob_decimal_add (d_0, dc_2);
      cob_decimal_get_field (d_0, &f_82, 0);
    }

    /* Line: 125       : COMPUTE            : makemove.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_82)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_83, 0);

    /* Line: 126       : MOVE               : makemove.cob */
    memmove (b_73, b_101 + 2LL * ((cob_s64_t)((*(short *)(b_83))) - 1), 2);

    /* Line: 127       : IF                 : makemove.cob */
    if ((((int)cob_cmp_s16 (b_73, 1LL) >= 0) && 
        ((int)cob_cmp_s16 (b_73, 12LL) <= 0)))
    {

      /* Line: 128       : SUBTRACT           : makemove.cob */
      cob_sub (&f_91, COB_SET_FLD (f0, 8, b_58 + 10 + 8LL * ((cob_s64_t)((*(short *)(b_83))) - 1) + 1024LL * ((cob_s64_t)((*(short *)(b_73))) - 1), &a_6), 0);

      /* Line: 129       : IF                 : makemove.cob */
      if (((int)cob_cmp_s64 (b_91, 0LL) < 0))
      {

        /* Line: 129       : ADD                : makemove.cob */
        cob_add_s64 (b_91, 2147483647);
      }
    }
  }
  else
  {
    /* ELSE */

    /* Line: 132       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_73, 0LL) != 0))
    {

      /* Line: 133       : SUBTRACT           : makemove.cob */
      cob_sub (&f_91, COB_SET_FLD (f0, 8, b_58 + 10 + 8LL * ((cob_s64_t)((*(short *)(b_71))) - 1) + 1024LL * ((cob_s64_t)((*(short *)(b_73))) - 1), &a_6), 0);

      /* Line: 134       : IF                 : makemove.cob */
      if (((int)cob_cmp_s64 (b_91, 0LL) < 0))
      {

        /* Line: 134       : ADD                : makemove.cob */
        cob_add_s64 (b_91, 2147483647);
      }
    }
  }

  /* Line: 139       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_78, 1LL) == 0))
  {

    /* Line: 140       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_8, &f_86);
    cob_move ((cob_field *)&c_8, &f_87);

    /* Line: 141       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
    {

      /* Line: 142       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_6, &f_90);

      /* Line: 143       : IF                 : makemove.cob */
      if (((int)cob_cmp_s16 (b_69, 6LL) == 0))
      {

        /* Line: 144       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_9, &f_86);

        /* Line: 145       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_10, &f_87);
      }
      else
      {
        /* ELSE */

        /* Line: 147       : IF                 : makemove.cob */
        if (((int)cob_cmp_s16 (b_69, 2LL) == 0))
        {

          /* Line: 148       : MOVE               : makemove.cob */
          cob_move ((cob_field *)&c_8, &f_86);

          /* Line: 149       : MOVE               : makemove.cob */
          cob_move ((cob_field *)&c_11, &f_87);
        }
      }
    }
    else
    {
      /* ELSE */

      /* Line: 153       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_12, &f_90);

      /* Line: 154       : IF                 : makemove.cob */
      if (((int)cob_cmp_s16 (b_69, 118LL) == 0))
      {

        /* Line: 155       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_13, &f_86);

        /* Line: 156       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_14, &f_87);
      }
      else
      {
        /* ELSE */

        /* Line: 158       : IF                 : makemove.cob */
        if (((int)cob_cmp_s16 (b_69, 114LL) == 0))
        {

          /* Line: 159       : MOVE               : makemove.cob */
          cob_move ((cob_field *)&c_15, &f_86);

          /* Line: 160       : MOVE               : makemove.cob */
          cob_move ((cob_field *)&c_16, &f_87);
        }
      }
    }

    /* Line: 165       : COMPUTE            : makemove.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_86)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_88, 0);

    /* Line: 166       : COMPUTE            : makemove.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_87)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_89, 0);

    /* Line: 167       : SUBTRACT           : makemove.cob */
    cob_sub (&f_91, COB_SET_FLD (f0, 8, b_58 + 10 + 8LL * ((cob_s64_t)((*(short *)(b_88))) - 1) + 1024LL * ((cob_s64_t)((*(short *)(b_90))) - 1), &a_6), 0);

    /* Line: 168       : IF                 : makemove.cob */
    if (((int)cob_cmp_s64 (b_91, 0LL) < 0))
    {

      /* Line: 168       : ADD                : makemove.cob */
      cob_add_s64 (b_91, 2147483647);
    }

    /* Line: 169       : ADD                : makemove.cob */
    cob_add (&f_91, COB_SET_FLD (f0, 8, b_58 + 10 + 8LL * ((cob_s64_t)((*(short *)(b_89))) - 1) + 1024LL * ((cob_s64_t)((*(short *)(b_90))) - 1), &a_6), 0);

    /* Line: 170       : IF                 : makemove.cob */
    if (((int)cob_cmp_s64 (b_91, 2147483647LL) >= 0))
    {

      /* Line: 170       : SUBTRACT           : makemove.cob */
      cob_sub_s64 (b_91, 2147483647);
    }
  }

  /* Line: 174       : MOVE               : makemove.cob */
  memcpy (b_75, b_72, 2);

  /* Line: 175       : IF                 : makemove.cob */
  if ((((int)cob_cmp_s16 (b_79, 1LL) == 0) && 
      ((int)cob_cmp_s16 (b_123 + 4, 0LL) != 0)))
  {

    /* Line: 176       : PERFORM            : makemove.cob */
    /* PERFORM PROMO-PIECE-FROM */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_38;
    goto l_11;
    l_38:
    frame_ptr--;
  }

  /* Line: 178       : ADD                : makemove.cob */
  cob_add (&f_91, COB_SET_FLD (f0, 8, b_58 + 10 + 8LL * ((cob_s64_t)((*(short *)(b_71))) - 1) + 1024LL * ((cob_s64_t)((*(short *)(b_75))) - 1), &a_6), 0);

  /* Line: 179       : IF                 : makemove.cob */
  if (((int)cob_cmp_s64 (b_91, 2147483647LL) >= 0))
  {

    /* Line: 179       : SUBTRACT           : makemove.cob */
    cob_sub_s64 (b_91, 2147483647);
  }

  /* Line: 181       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_17, COB_SET_DATA (f_106, b_101 + 260));

  /* Line: 184       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, &f_76);

  /* Line: 185       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_73, 0LL) != 0))
  {

    /* Line: 186       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_76);
  }

  /* Line: 188       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_77, 1LL) == 0))
  {

    /* Line: 189       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_76);
  }

  /* Line: 192       : IF                 : makemove.cob */
  if (((((int)cob_cmp_s16 (b_72, 1LL) == 0) || 
      ((int)cob_cmp_s16 (b_72, 7LL) == 0)) || 
      ((int)cob_cmp_s16 (b_76, 1LL) == 0)))
  {

    /* Line: 193       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_8, COB_SET_DATA (f_107, b_101 + 262));
  }
  else
  {
    /* ELSE */

    /* Line: 195       : ADD                : makemove.cob */
    cob_add_s16 (b_101 + 262, 1);
  }

  /* Line: 199       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, COB_SET_FLD (f0, 2, b_101 + 2LL * ((cob_s64_t)((*(short *)(b_70))) - 1), &a_5));

  /* Line: 202       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_77, 1LL) == 0))
  {

    /* Line: 203       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
    {

      /* Line: 204       : COMPUTE            : makemove.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_69)));
      cob_decimal_sub (d_0, dc_2);
      cob_decimal_get_field (d_0, &f_82, 0);
    }
    else
    {
      /* ELSE */

      /* Line: 206       : COMPUTE            : makemove.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_69)));
      cob_decimal_add (d_0, dc_2);
      cob_decimal_get_field (d_0, &f_82, 0);
    }

    /* Line: 208       : COMPUTE            : makemove.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_82)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_83, 0);

    /* Line: 209       : MOVE               : makemove.cob */
    memmove (b_73, b_101 + 2LL * ((cob_s64_t)((*(short *)(b_83))) - 1), 2);

    /* Line: 210       : MOVE               : makemove.cob */
    memmove (b_101 + 280 + 22LL * ((cob_s64_t)((*(short *)(b_74))) - 1), b_73, 2);

    /* Line: 211       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_8, COB_SET_FLD (f0, 2, b_101 + 2LL * ((cob_s64_t)((*(short *)(b_83))) - 1), &a_5));
  }

  /* Line: 215       : MOVE               : makemove.cob */
  memmove (b_101 + 2LL * ((cob_s64_t)((*(short *)(b_71))) - 1), b_72, 2);

  /* Line: 218       : IF                 : makemove.cob */
  if ((((int)cob_cmp_s16 (b_79, 1LL) == 0) && 
      ((int)cob_cmp_s16 (b_123 + 4, 0LL) != 0)))
  {

    /* Line: 219       : PERFORM            : makemove.cob */
    /* PERFORM PROMO-PIECE-FROM */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_39;
    goto l_11;
    l_39:
    frame_ptr--;

    /* Line: 220       : MOVE               : makemove.cob */
    memmove (b_101 + 2LL * ((cob_s64_t)((*(short *)(b_71))) - 1), b_75, 2);
  }

  /* Line: 224       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_78, 1LL) == 0))
  {

    /* Line: 225       : PERFORM            : makemove.cob */
    /* PERFORM DO-CASTLE-ROOK */
    frame_ptr++;
    frame_ptr->perform_through = 15;
    frame_ptr->return_address_ptr = &&l_40;
    goto l_15;
    l_40:
    frame_ptr--;
  }

  /* Line: 229       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_72, 6LL) == 0))
  {

    /* Line: 230       : MOVE               : makemove.cob */
    memmove (b_101 + 266, b_69, 2);
  }

  /* Line: 232       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_72, 12LL) == 0))
  {

    /* Line: 233       : MOVE               : makemove.cob */
    memmove (b_101 + 266 + 2LL * 1LL, b_69, 2);
  }

  /* Line: 237       : PERFORM            : makemove.cob */
  /* PERFORM UPDATE-CASTLING */
  frame_ptr++;
  frame_ptr->perform_through = 17;
  frame_ptr->return_address_ptr = &&l_41;
  goto l_17;
  l_41:
  frame_ptr--;

  /* Line: 240       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_80, 1LL) == 0))
  {

    /* Line: 241       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
    {

      /* Line: 242       : COMPUTE            : makemove.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_68)));
      cob_decimal_add (d_0, dc_2);
      cob_decimal_get_field (d_0, COB_SET_DATA (f_106, b_101 + 260), 0);
    }
    else
    {
      /* ELSE */

      /* Line: 244       : COMPUTE            : makemove.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_68)));
      cob_decimal_sub (d_0, dc_2);
      cob_decimal_get_field (d_0, COB_SET_DATA (f_106, b_101 + 260), 0);
    }
  }

  /* Line: 249       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_66, 1LL) == 0))
  {

    /* Line: 250       : ADD                : makemove.cob */
    cob_add_s16 (b_101 + 264, 1);
  }

  /* Line: 254       : MOVE               : makemove.cob */
  memmove (b_101 + 256, b_67, 2);

  /* Line: 255       : ADD                : makemove.cob */
  cob_add_s16 (b_101 + 270, 1);

  /* Line: 258       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_101 + 256, 1LL) == 0))
  {

    /* Line: 259       : ADD                : makemove.cob */
    cob_add (&f_91, COB_SET_DATA (f_63, b_58 + 12298), 0);

    /* Line: 260       : IF                 : makemove.cob */
    if (((int)cob_cmp_s64 (b_91, 2147483647LL) >= 0))
    {

      /* Line: 260       : SUBTRACT           : makemove.cob */
      cob_sub_s64 (b_91, 2147483647);
    }
  }

  /* Line: 263       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_105, b_101 + 258)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_95, 0);

  /* Line: 264       : IF                 : makemove.cob */
  if ((((int)cob_cmp_s16 (b_95, 1LL) >= 0) && 
      ((int)cob_cmp_s16 (b_95, 16LL) <= 0)))
  {

    /* Line: 265       : ADD                : makemove.cob */
    cob_add (&f_91, COB_SET_FLD (f0, 8, b_58 + 12306 + 8LL * ((cob_s64_t)((*(short *)(b_95))) - 1), &a_6), 0);

    /* Line: 266       : IF                 : makemove.cob */
    if (((int)cob_cmp_s64 (b_91, 2147483647LL) >= 0))
    {

      /* Line: 266       : SUBTRACT           : makemove.cob */
      cob_sub_s64 (b_91, 2147483647);
    }
  }

  /* Line: 269       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_101 + 260, 0LL) >= 0))
  {

    /* Line: 270       : COMPUTE            : makemove.cob */
    cob_decimal_set_field (d_0, cob_intr_mod (COB_SET_DATA (f_106, b_101 + 260), (cob_field *)&c_2));
    cob_decimal_get_field (d_0, &f_96, 0);

    /* Line: 271       : COMPUTE            : makemove.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_96)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_97, 0);

    /* Line: 272       : IF                 : makemove.cob */
    if ((((int)cob_cmp_s16 (b_97, 1LL) >= 0) && 
        ((int)cob_cmp_s16 (b_97, 8LL) <= 0)))
    {

      /* Line: 273       : ADD                : makemove.cob */
      cob_add (&f_91, COB_SET_FLD (f0, 8, b_58 + 12434 + 8LL * ((cob_s64_t)((*(short *)(b_97))) - 1), &a_6), 0);

      /* Line: 274       : IF                 : makemove.cob */
      if (((int)cob_cmp_s64 (b_91, 2147483647LL) >= 0))
      {

        /* Line: 274       : SUBTRACT           : makemove.cob */
        cob_sub_s64 (b_91, 2147483647);
      }
    }
  }

  /* Line: 278       : MOVE               : makemove.cob */
  memmove (b_101 + 272, b_91, 8);

  /* Line: 281       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, &f_85);

  /* Line: 282       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
  {

    /* Line: 283       : MOVE               : makemove.cob */
    memmove (b_84, b_101 + 266, 2);
  }
  else
  {
    /* ELSE */

    /* Line: 285       : MOVE               : makemove.cob */
    memmove (b_84, b_101 + 266 + 2LL * 1LL, 2);
  }

  /* Line: 287       : CALL               : makemove.cob */
  cob_procedure_params[0] = COB_SET_DATA (f_101, b_101);
  cob_procedure_params[1] = &f_84;
  cob_procedure_params[2] = &f_67;
  cob_procedure_params[3] = &f_85;
  cob_glob_ptr->cob_call_params = 4;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_101, b_84, b_67, b_85);

  /* Line: 288       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_85, 1LL) == 0))
  {

    /* Line: 289       : CALL               : makemove.cob */
    cob_procedure_params[0] = COB_SET_DATA (f_101, b_101);
    cob_procedure_params[1] = COB_SET_DATA (f_123, b_123);
    cob_glob_ptr->cob_call_params = 2;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
        if (unlikely(call_UNMAKEMOVE.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
    {
      call_UNMAKEMOVE.funcvoid = cob_resolve_cobol ("UNMAKEMOVE", 0, 1);
    }
    b_2 = ((int (*)(void *, void *))call_UNMAKEMOVE.funcint) (b_101, b_123);

    /* Line: 290       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_8, COB_SET_DATA (f_137, b_137));

    /* Line: 291       : GOBACK             : makemove.cob */
    goto exit_program;
  }

  /* Line: 294       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_1, COB_SET_DATA (f_137, b_137));

  /* Line: 295       : GOBACK             : makemove.cob */
  goto exit_program;

  /* Line: 297       : Paragraph ENSURE-HASH-INIT        : makemove.cob */
  l_5:;

  /* Line: 298       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_58, 1LL) == 0))
  {

    /* Line: 299       : EXIT PARAGRAPH     : makemove.cob */
    goto l_6;
  }

  /* Line: 302       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_1, COB_SET_DATA (f_60, b_58 + 2));

  /* Line: 304       : PERFORM            : makemove.cob */
  cob_move ((cob_field *)&c_1, &f_98);
  for (;;)
  {
    /* Line: 304       : UNTIL              : makemove.cob */
    if (((int)cob_cmp_s16 (b_98, 12LL) > 0))
      break;

    /* Line: 305       : PERFORM            : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_99);
    for (;;)
    {
      /* Line: 305       : UNTIL              : makemove.cob */
      if (((int)cob_cmp_s16 (b_99, 128LL) > 0))
        break;

      /* Line: 306       : PERFORM            : makemove.cob */
      /* PERFORM NEXT-RAND */
      frame_ptr++;
      frame_ptr->perform_through = 7;
      frame_ptr->return_address_ptr = &&l_42;
      goto l_7;
      l_42:
      frame_ptr--;

      /* Line: 307       : MOVE               : makemove.cob */
      memmove (b_58 + 10 + 8LL * ((cob_s64_t)((*(short *)(b_99))) - 1) + 1024LL * ((cob_s64_t)((*(short *)(b_98))) - 1), b_58 + 2, 8);
      /* Line: 305       : VARYING            : makemove.cob */
      cob_add_s16 (b_99, 1);
    }
    /* Line: 304       : VARYING            : makemove.cob */
    cob_add_s16 (b_98, 1);
  }

  /* Line: 311       : PERFORM            : makemove.cob */
  /* PERFORM NEXT-RAND */
  frame_ptr++;
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_43;
  goto l_7;
  l_43:
  frame_ptr--;

  /* Line: 312       : MOVE               : makemove.cob */
  memcpy (b_58 + 12298, b_58 + 2, 8);

  /* Line: 314       : PERFORM            : makemove.cob */
  cob_move ((cob_field *)&c_1, &f_99);
  for (;;)
  {
    /* Line: 314       : UNTIL              : makemove.cob */
    if (((int)cob_cmp_s16 (b_99, 16LL) > 0))
      break;

    /* Line: 315       : PERFORM            : makemove.cob */
    /* PERFORM NEXT-RAND */
    frame_ptr++;
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_44;
    goto l_7;
    l_44:
    frame_ptr--;

    /* Line: 316       : MOVE               : makemove.cob */
    memmove (b_58 + 12306 + 8LL * ((cob_s64_t)((*(short *)(b_99))) - 1), b_58 + 2, 8);
    /* Line: 314       : VARYING            : makemove.cob */
    cob_add_s16 (b_99, 1);
  }

  /* Line: 319       : PERFORM            : makemove.cob */
  cob_move ((cob_field *)&c_1, &f_99);
  for (;;)
  {
    /* Line: 319       : UNTIL              : makemove.cob */
    if (((int)cob_cmp_s16 (b_99, 8LL) > 0))
      break;

    /* Line: 320       : PERFORM            : makemove.cob */
    /* PERFORM NEXT-RAND */
    frame_ptr++;
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_45;
    goto l_7;
    l_45:
    frame_ptr--;

    /* Line: 321       : MOVE               : makemove.cob */
    memmove (b_58 + 12434 + 8LL * ((cob_s64_t)((*(short *)(b_99))) - 1), b_58 + 2, 8);
    /* Line: 319       : VARYING            : makemove.cob */
    cob_add_s16 (b_99, 1);
  }

  /* Line: 324       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_1, COB_SET_DATA (f_59, b_58));

  /* Line: 325       : EXIT PARAGRAPH     : makemove.cob */
  goto l_6;

  /* Implicit EXIT label */
  l_6:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 327       : Paragraph NEXT-RAND               : makemove.cob */
  l_7:;

  /* Line: 328       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_60, b_58 + 2)));
  cob_decimal_mul (d_0, dc_3);
  cob_decimal_add (d_0, dc_4);
  cob_decimal_get_field (d_0, &f_100, 0);

  /* Line: 329       : COMPUTE            : makemove.cob */
  cob_decimal_set_field (d_0, cob_intr_mod (&f_100, (cob_field *)&c_18));
  cob_decimal_get_field (d_0, COB_SET_DATA (f_60, b_58 + 2), 0);

  /* Line: 330       : IF                 : makemove.cob */
  if (((int)cob_cmp_s64 (b_58 + 2, 0LL) < 0))
  {

    /* Line: 331       : ADD                : makemove.cob */
    cob_add_s64 (b_58 + 2, 2147483647);
  }

  /* Line: 333       : EXIT PARAGRAPH     : makemove.cob */
  goto l_8;

  /* Implicit EXIT label */
  l_8:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 335       : Paragraph DECODE-FLAGS            : makemove.cob */
  l_9:;

  /* Line: 336       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, &f_77);
  cob_move ((cob_field *)&c_8, &f_78);
  cob_move ((cob_field *)&c_8, &f_79);
  cob_move ((cob_field *)&c_8, &f_80);

  /* Line: 337       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_127, b_123 + 6)));
  cob_decimal_div (d_0, dc_5);
  cob_decimal_get_field (d_0, &f_81, 0);

  /* Line: 338       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_81, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 338       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_77);
  }

  /* Line: 339       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_127, b_123 + 6)));
  cob_decimal_div (d_0, dc_6);
  cob_decimal_get_field (d_0, &f_81, 0);

  /* Line: 340       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_81, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 340       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_78);
  }

  /* Line: 341       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_127, b_123 + 6)));
  cob_decimal_div (d_0, dc_7);
  cob_decimal_get_field (d_0, &f_81, 0);

  /* Line: 342       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_81, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 342       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_79);
  }

  /* Line: 343       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_127, b_123 + 6)));
  cob_decimal_div (d_0, dc_2);
  cob_decimal_get_field (d_0, &f_81, 0);

  /* Line: 344       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_81, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 344       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_80);
  }

  /* Line: 345       : EXIT PARAGRAPH     : makemove.cob */
  goto l_10;

  /* Implicit EXIT label */
  l_10:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 347       : Paragraph PROMO-PIECE-FROM        : makemove.cob */
  l_11:;

  /* Line: 348       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, &f_75);

  /* Line: 349       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
  {

    /* Line: 350       : EVALUATE           : makemove.cob */

    /* Line: 351       : WHEN               : makemove.cob */

    if (((int)cob_cmp_s16 (b_123 + 4, 1LL) == 0))
    {

      /* Line: 351       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_10, &f_75);
      goto l_12;
    }

    /* Line: 352       : WHEN               : makemove.cob */

    if (((int)cob_cmp_s16 (b_123 + 4, 2LL) == 0))
    {

      /* Line: 352       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_6, &f_75);
      goto l_12;
    }

    /* Line: 353       : WHEN               : makemove.cob */

    if (((int)cob_cmp_s16 (b_123 + 4, 3LL) == 0))
    {

      /* Line: 353       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_11, &f_75);
      goto l_12;
    }

    /* Line: 354       : WHEN               : makemove.cob */

    if (((int)cob_cmp_s16 (b_123 + 4, 4LL) == 0))
    {

      /* Line: 354       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_5, &f_75);
      goto l_12;
    }

    /* WHEN OTHER */

    /* Line: 355       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_10, &f_75);

    /* End EVALUATE */
    l_12:;
  }
  else
  {
    /* ELSE */

    /* Line: 358       : EVALUATE           : makemove.cob */

    /* Line: 359       : WHEN               : makemove.cob */

    if (((int)cob_cmp_s16 (b_123 + 4, 1LL) == 0))
    {

      /* Line: 359       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_19, &f_75);
      goto l_13;
    }

    /* Line: 360       : WHEN               : makemove.cob */

    if (((int)cob_cmp_s16 (b_123 + 4, 2LL) == 0))
    {

      /* Line: 360       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_12, &f_75);
      goto l_13;
    }

    /* Line: 361       : WHEN               : makemove.cob */

    if (((int)cob_cmp_s16 (b_123 + 4, 3LL) == 0))
    {

      /* Line: 361       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_20, &f_75);
      goto l_13;
    }

    /* Line: 362       : WHEN               : makemove.cob */

    if (((int)cob_cmp_s16 (b_123 + 4, 4LL) == 0))
    {

      /* Line: 362       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_7, &f_75);
      goto l_13;
    }

    /* WHEN OTHER */

    /* Line: 363       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_19, &f_75);

    /* End EVALUATE */
    l_13:;
  }

  /* Line: 366       : EXIT PARAGRAPH     : makemove.cob */
  goto l_14;

  /* Implicit EXIT label */
  l_14:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 368       : Paragraph DO-CASTLE-ROOK          : makemove.cob */
  l_15:;

  /* Line: 369       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, &f_86);
  cob_move ((cob_field *)&c_8, &f_87);

  /* Line: 370       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_66, 0LL) == 0))
  {

    /* Line: 371       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_69, 6LL) == 0))
    {

      /* Line: 372       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_9, &f_86);

      /* Line: 373       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_10, &f_87);
    }
    else
    {
      /* ELSE */

      /* Line: 375       : IF                 : makemove.cob */
      if (((int)cob_cmp_s16 (b_69, 2LL) == 0))
      {

        /* Line: 376       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_8, &f_86);

        /* Line: 377       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_11, &f_87);
      }
    }
  }
  else
  {
    /* ELSE */

    /* Line: 381       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_69, 118LL) == 0))
    {

      /* Line: 382       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_13, &f_86);

      /* Line: 383       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_14, &f_87);
    }
    else
    {
      /* ELSE */

      /* Line: 385       : IF                 : makemove.cob */
      if (((int)cob_cmp_s16 (b_69, 114LL) == 0))
      {

        /* Line: 386       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_15, &f_86);

        /* Line: 387       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_16, &f_87);
      }
    }
  }

  /* Line: 392       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_86)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_88, 0);

  /* Line: 393       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_87)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_89, 0);

  /* Line: 394       : MOVE               : makemove.cob */
  memmove (b_90, b_101 + 2LL * ((cob_s64_t)((*(short *)(b_88))) - 1), 2);

  /* Line: 395       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, COB_SET_FLD (f0, 2, b_101 + 2LL * ((cob_s64_t)((*(short *)(b_88))) - 1), &a_5));

  /* Line: 396       : MOVE               : makemove.cob */
  memmove (b_101 + 2LL * ((cob_s64_t)((*(short *)(b_89))) - 1), b_90, 2);

  /* Line: 397       : EXIT PARAGRAPH     : makemove.cob */
  goto l_16;

  /* Implicit EXIT label */
  l_16:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Line: 399       : Paragraph UPDATE-CASTLING         : makemove.cob */
  l_17:;

  /* Line: 401       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_72, 6LL) == 0))
  {

    /* Line: 402       : PERFORM            : makemove.cob */
    /* PERFORM CLEAR-WHITE-CASTLING */
    frame_ptr++;
    frame_ptr->perform_through = 19;
    frame_ptr->return_address_ptr = &&l_46;
    goto l_19;
    l_46:
    frame_ptr--;
  }

  /* Line: 404       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_72, 12LL) == 0))
  {

    /* Line: 405       : PERFORM            : makemove.cob */
    /* PERFORM CLEAR-BLACK-CASTLING */
    frame_ptr++;
    frame_ptr->perform_through = 21;
    frame_ptr->return_address_ptr = &&l_47;
    goto l_21;
    l_47:
    frame_ptr--;
  }

  /* Line: 409       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_72, 4LL) == 0))
  {

    /* Line: 410       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_68, 0LL) == 0))
    {

      /* Line: 411       : PERFORM            : makemove.cob */
      /* PERFORM CLEAR-WQ */
      frame_ptr++;
      frame_ptr->perform_through = 25;
      frame_ptr->return_address_ptr = &&l_48;
      goto l_25;
      l_48:
      frame_ptr--;
    }

    /* Line: 413       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_68, 7LL) == 0))
    {

      /* Line: 414       : PERFORM            : makemove.cob */
      /* PERFORM CLEAR-WK */
      frame_ptr++;
      frame_ptr->perform_through = 23;
      frame_ptr->return_address_ptr = &&l_49;
      goto l_23;
      l_49:
      frame_ptr--;
    }
  }

  /* Line: 417       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_72, 10LL) == 0))
  {

    /* Line: 418       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_68, 112LL) == 0))
    {

      /* Line: 419       : PERFORM            : makemove.cob */
      /* PERFORM CLEAR-BQ */
      frame_ptr++;
      frame_ptr->perform_through = 29;
      frame_ptr->return_address_ptr = &&l_50;
      goto l_29;
      l_50:
      frame_ptr--;
    }

    /* Line: 421       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_68, 119LL) == 0))
    {

      /* Line: 422       : PERFORM            : makemove.cob */
      /* PERFORM CLEAR-BK */
      frame_ptr++;
      frame_ptr->perform_through = 27;
      frame_ptr->return_address_ptr = &&l_51;
      goto l_27;
      l_51:
      frame_ptr--;
    }
  }

  /* Line: 427       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_73, 4LL) == 0))
  {

    /* Line: 428       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_69, 0LL) == 0))
    {

      /* Line: 429       : PERFORM            : makemove.cob */
      /* PERFORM CLEAR-WQ */
      frame_ptr++;
      frame_ptr->perform_through = 25;
      frame_ptr->return_address_ptr = &&l_52;
      goto l_25;
      l_52:
      frame_ptr--;
    }

    /* Line: 431       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_69, 7LL) == 0))
    {

      /* Line: 432       : PERFORM            : makemove.cob */
      /* PERFORM CLEAR-WK */
      frame_ptr++;
      frame_ptr->perform_through = 23;
      frame_ptr->return_address_ptr = &&l_53;
      goto l_23;
      l_53:
      frame_ptr--;
    }
  }

  /* Line: 435       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_73, 10LL) == 0))
  {

    /* Line: 436       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_69, 112LL) == 0))
    {

      /* Line: 437       : PERFORM            : makemove.cob */
      /* PERFORM CLEAR-BQ */
      frame_ptr++;
      frame_ptr->perform_through = 29;
      frame_ptr->return_address_ptr = &&l_54;
      goto l_29;
      l_54:
      frame_ptr--;
    }

    /* Line: 439       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_69, 119LL) == 0))
    {

      /* Line: 440       : PERFORM            : makemove.cob */
      /* PERFORM CLEAR-BK */
      frame_ptr++;
      frame_ptr->perform_through = 27;
      frame_ptr->return_address_ptr = &&l_55;
      goto l_27;
      l_55:
      frame_ptr--;
    }
  }

  /* Line: 443       : EXIT PARAGRAPH     : makemove.cob */
  goto l_18;

  /* Implicit EXIT label */
  l_18:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address_ptr;

  /* Line: 445       : Paragraph CLEAR-WHITE-CASTLING    : makemove.cob */
  l_19:;

  /* Line: 446       : PERFORM            : makemove.cob */
  /* PERFORM CLEAR-WK */
  frame_ptr++;
  frame_ptr->perform_through = 23;
  frame_ptr->return_address_ptr = &&l_56;
  goto l_23;
  l_56:
  frame_ptr--;

  /* Line: 447       : PERFORM            : makemove.cob */
  /* PERFORM CLEAR-WQ */
  frame_ptr++;
  frame_ptr->perform_through = 25;
  frame_ptr->return_address_ptr = &&l_57;
  goto l_25;
  l_57:
  frame_ptr--;

  /* Line: 448       : EXIT PARAGRAPH     : makemove.cob */
  goto l_20;

  /* Implicit EXIT label */
  l_20:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 19)
    goto *frame_ptr->return_address_ptr;

  /* Line: 450       : Paragraph CLEAR-BLACK-CASTLING    : makemove.cob */
  l_21:;

  /* Line: 451       : PERFORM            : makemove.cob */
  /* PERFORM CLEAR-BK */
  frame_ptr++;
  frame_ptr->perform_through = 27;
  frame_ptr->return_address_ptr = &&l_58;
  goto l_27;
  l_58:
  frame_ptr--;

  /* Line: 452       : PERFORM            : makemove.cob */
  /* PERFORM CLEAR-BQ */
  frame_ptr++;
  frame_ptr->perform_through = 29;
  frame_ptr->return_address_ptr = &&l_59;
  goto l_29;
  l_59:
  frame_ptr--;

  /* Line: 453       : EXIT PARAGRAPH     : makemove.cob */
  goto l_22;

  /* Implicit EXIT label */
  l_22:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 21)
    goto *frame_ptr->return_address_ptr;

  /* Line: 455       : Paragraph CLEAR-WK                : makemove.cob */
  l_23:;

  /* Line: 456       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_105, b_101 + 258)));
  cob_decimal_get_field (d_0, &f_81, 0);

  /* Line: 457       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_81, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 458       : SUBTRACT           : makemove.cob */
    cob_sub_s16 (b_101 + 258, 1);
  }

  /* Line: 460       : EXIT PARAGRAPH     : makemove.cob */
  goto l_24;

  /* Implicit EXIT label */
  l_24:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 23)
    goto *frame_ptr->return_address_ptr;

  /* Line: 462       : Paragraph CLEAR-WQ                : makemove.cob */
  l_25:;

  /* Line: 463       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_105, b_101 + 258)));
  cob_decimal_div (d_0, dc_5);
  cob_decimal_get_field (d_0, &f_81, 0);

  /* Line: 464       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_81, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 465       : SUBTRACT           : makemove.cob */
    cob_sub_s16 (b_101 + 258, 2);
  }

  /* Line: 467       : EXIT PARAGRAPH     : makemove.cob */
  goto l_26;

  /* Implicit EXIT label */
  l_26:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 25)
    goto *frame_ptr->return_address_ptr;

  /* Line: 469       : Paragraph CLEAR-BK                : makemove.cob */
  l_27:;

  /* Line: 470       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_105, b_101 + 258)));
  cob_decimal_div (d_0, dc_6);
  cob_decimal_get_field (d_0, &f_81, 0);

  /* Line: 471       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_81, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 472       : SUBTRACT           : makemove.cob */
    cob_sub_s16 (b_101 + 258, 4);
  }

  /* Line: 474       : EXIT PARAGRAPH     : makemove.cob */
  goto l_28;

  /* Implicit EXIT label */
  l_28:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 27)
    goto *frame_ptr->return_address_ptr;

  /* Line: 476       : Paragraph CLEAR-BQ                : makemove.cob */
  l_29:;

  /* Line: 477       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_105, b_101 + 258)));
  cob_decimal_div (d_0, dc_7);
  cob_decimal_get_field (d_0, &f_81, 0);

  /* Line: 478       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_81, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 479       : SUBTRACT           : makemove.cob */
    cob_sub_s16 (b_101 + 258, 8);
  }

  /* Line: 481       : EXIT PARAGRAPH     : makemove.cob */
  goto l_30;

  /* Implicit EXIT label */
  l_30:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 29)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Decrement module reference count */
  if (cob_reference_count) {
      cob_reference_count--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  MAKEMOVE_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  b_58 = cob_external_addr ("HASH_STATE", 12498);
  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field SIDE */
  memset (b_66, 0x0, 2);

  /* initialize field OPP-SIDE */
  memset (b_67, 0x0, 2);

  /* initialize field FROM-SQ */
  memset (b_68, 0x0, 2);

  /* initialize field TO-SQ */
  memset (b_69, 0x0, 2);

  /* initialize field FROM-IDX */
  memset (b_70, 0x0, 2);

  /* initialize field TO-IDX */
  memset (b_71, 0x0, 2);

  /* initialize field PIECE */
  memset (b_72, 0x0, 2);

  /* initialize field CAPTURED */
  memset (b_73, 0x0, 2);

  /* initialize field UNDO-IX */
  memset (b_74, 0x0, 2);

  /* initialize field PROMO-PIECE */
  memset (b_75, 0x0, 2);

  /* initialize field IS-CAPTURE */
  memset (b_76, 0x0, 2);

  /* initialize field IS-EP */
  memset (b_77, 0x0, 2);

  /* initialize field IS-CASTLE */
  memset (b_78, 0x0, 2);

  /* initialize field IS-PROMO */
  memset (b_79, 0x0, 2);

  /* initialize field IS-PAWN-DOUBLE */
  memset (b_80, 0x0, 2);

  /* initialize field Q */
  memset (b_81, 0x0, 2);

  /* initialize field CAP-SQ */
  memset (b_82, 0x0, 2);

  /* initialize field CAP-IDX */
  memset (b_83, 0x0, 2);

  /* initialize field KING-SQ */
  memset (b_84, 0x0, 2);

  /* initialize field ATTACKED */
  memset (b_85, 0x0, 2);

  /* initialize field ROOK-FROM-SQ */
  memset (b_86, 0x0, 2);

  /* initialize field ROOK-TO-SQ */
  memset (b_87, 0x0, 2);

  /* initialize field ROOK-FROM-IDX */
  memset (b_88, 0x0, 2);

  /* initialize field ROOK-TO-IDX */
  memset (b_89, 0x0, 2);

  /* initialize field ROOK-PIECE */
  memset (b_90, 0x0, 2);

  /* initialize field WORK-KEY */
  memset (b_91, 0x0, 8);

  /* initialize field OLD-CAST-IX */
  memset (b_92, 0x0, 2);

  /* initialize field OLD-EP-FILE */
  memset (b_93, 0x0, 2);

  /* initialize field OLD-EP-IX */
  memset (b_94, 0x0, 2);

  /* initialize field NEW-CAST-IX */
  memset (b_95, 0x0, 2);

  /* initialize field NEW-EP-FILE */
  memset (b_96, 0x0, 2);

  /* initialize field NEW-EP-IX */
  memset (b_97, 0x0, 2);

  /* initialize field H-P */
  memset (b_98, 0x0, 2);

  /* initialize field H-S */
  memset (b_99, 0x0, 2);

  /* initialize field H-TMP */
  memset (b_100, 0x0, 8);


  /* Set Decimal Constant values */
  dc_7 = &kc_7;
  cob_decimal_init (dc_7);
  cob_decimal_set_field (dc_7, (cob_field *)&c_7);

  dc_6 = &kc_6;
  cob_decimal_init (dc_6);
  cob_decimal_set_field (dc_6, (cob_field *)&c_6);

  dc_5 = &kc_5;
  cob_decimal_init (dc_5);
  cob_decimal_set_field (dc_5, (cob_field *)&c_5);

  dc_4 = &kc_4;
  cob_decimal_init (dc_4);
  cob_decimal_set_field (dc_4, (cob_field *)&c_4);

  dc_3 = &kc_3;
  cob_decimal_init (dc_3);
  cob_decimal_set_field (dc_3, (cob_field *)&c_3);

  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  call_UNMAKEMOVE.funcvoid = NULL;
  call_ATTACK.funcvoid = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_7);
  dc_7 = NULL;
  cob_decimal_clear (dc_6);
  dc_6 = NULL;
  cob_decimal_clear (dc_5);
  dc_5 = NULL;
  cob_decimal_clear (dc_4);
  dc_4 = NULL;
  cob_decimal_clear (dc_3);
  dc_3 = NULL;
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'MAKEMOVE' */

/* Initialize module structure for MAKEMOVE */
static void MAKEMOVE_module_init (cob_module *module)
{
  module->module_name = "MAKEMOVE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MAKEMOVE;
  module->module_cancel.funcptr = (void *(*)())MAKEMOVE_;
  module->module_ref_count = &cob_reference_count;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 3;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* PROGRAM-ID 'UNMAKEMOVE' */

/* ENTRY 'UNMAKEMOVE' */

int
UNMAKEMOVE (cob_u8_t *b_212, cob_u8_t *b_234)
{
  cob_u8_t *cob_parm_212 = NULL;    /* linkage for GAME-STATE */
  cob_u8_t *cob_parm_234 = NULL;    /* linkage for MOVE-REC */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
      cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
      cob_call_params = 2;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_212 = b_212;
  }
  if (cob_call_params > 1) {
    cob_parm_234 = b_234;
  }

  return UNMAKEMOVE_ (0, cob_parm_212, cob_parm_234);
}

static int
UNMAKEMOVE_ (const int entry, cob_u8_t *b_212, cob_u8_t *b_234)
{
  /* Program local variables */
  #include "makemove.c.l2.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (1, &d_0);

  /* Increment module active */
  module->module_active++;

  /* Increment module reference count */
  cob_reference_count++;

  /* Store last parameters for possible later lookup */
  last_b_212 = b_212;
  last_b_234 = b_234;

  /* Entry dispatch */
  goto l_31;

  /* PROCEDURE DIVISION */

  /* Line: 519       : Entry     UNMAKEMOVE              : makemove.cob */
  l_31:;

  /* Line: 519       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_222, b_212 + 270)));
  cob_decimal_get_field (d_0, &f_198, 0);

  /* Line: 522       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_212 + 256, 0LL) == 0))
  {

    /* Line: 523       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_193);
  }
  else
  {
    /* ELSE */

    /* Line: 525       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_8, &f_193);
  }

  /* Line: 527       : MOVE               : makemove.cob */
  memmove (b_212 + 256, b_193, 2);

  /* Line: 529       : MOVE               : makemove.cob */
  memmove (b_212 + 258, b_212 + 284 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 2);

  /* Line: 530       : MOVE               : makemove.cob */
  memmove (b_212 + 260, b_212 + 286 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 2);

  /* Line: 531       : MOVE               : makemove.cob */
  memmove (b_212 + 262, b_212 + 288 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 2);

  /* Line: 532       : MOVE               : makemove.cob */
  memmove (b_212 + 264, b_212 + 290 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 2);

  /* Line: 534       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_193, 0LL) == 0))
  {

    /* Line: 535       : MOVE               : makemove.cob */
    memmove (b_212 + 266, b_212 + 292 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 2);
  }
  else
  {
    /* ELSE */

    /* Line: 537       : MOVE               : makemove.cob */
    memmove (b_212 + 266 + 2LL * 1LL, b_212 + 292 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 2);
  }

  /* Line: 540       : MOVE               : makemove.cob */
  memmove (b_194, b_234, 2);

  /* Line: 541       : MOVE               : makemove.cob */
  memmove (b_195, b_234 + 2, 2);

  /* Line: 542       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_194)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_196, 0);

  /* Line: 543       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_195)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_197, 0);

  /* Line: 545       : MOVE               : makemove.cob */
  memmove (b_199, b_212 + 282 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 2);

  /* Line: 546       : MOVE               : makemove.cob */
  memmove (b_200, b_212 + 280 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 2);

  /* Line: 549       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, &f_201);
  cob_move ((cob_field *)&c_8, &f_202);
  cob_move ((cob_field *)&c_8, &f_203);

  /* Line: 550       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_238, b_234 + 6)));
  cob_decimal_div (d_0, dc_5);
  cob_decimal_get_field (d_0, &f_204, 0);

  /* Line: 551       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_204, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 551       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_201);
  }

  /* Line: 552       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_238, b_234 + 6)));
  cob_decimal_div (d_0, dc_6);
  cob_decimal_get_field (d_0, &f_204, 0);

  /* Line: 553       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_204, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 553       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_202);
  }

  /* Line: 554       : DIVIDE             : makemove.cob */
  cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_238, b_234 + 6)));
  cob_decimal_div (d_0, dc_7);
  cob_decimal_get_field (d_0, &f_204, 0);

  /* Line: 555       : IF                 : makemove.cob */
  if (((int)cob_cmp_llint (cob_intr_mod (&f_204, (cob_field *)&c_5), 1LL) == 0))
  {

    /* Line: 555       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_1, &f_203);
  }

  /* Line: 558       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_202, 1LL) == 0))
  {

    /* Line: 559       : PERFORM            : makemove.cob */
    /* PERFORM UNDO-CASTLE-ROOK */
    frame_ptr++;
    frame_ptr->perform_through = 34;
    frame_ptr->return_address_ptr = &&l_60;
    goto l_34;
    l_60:
    frame_ptr--;
  }

  /* Line: 563       : MOVE               : makemove.cob */
  memmove (b_212 + 2LL * ((cob_s64_t)((*(short *)(b_196))) - 1), b_199, 2);

  /* Line: 566       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_201, 1LL) == 0))
  {

    /* Line: 567       : MOVE               : makemove.cob */
    cob_move ((cob_field *)&c_8, COB_SET_FLD (f0, 2, b_212 + 2LL * ((cob_s64_t)((*(short *)(b_197))) - 1), &a_5));

    /* Line: 568       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_193, 0LL) == 0))
    {

      /* Line: 569       : COMPUTE            : makemove.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_195)));
      cob_decimal_sub (d_0, dc_2);
      cob_decimal_get_field (d_0, &f_205, 0);
    }
    else
    {
      /* ELSE */

      /* Line: 571       : COMPUTE            : makemove.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_195)));
      cob_decimal_add (d_0, dc_2);
      cob_decimal_get_field (d_0, &f_205, 0);
    }

    /* Line: 573       : COMPUTE            : makemove.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_205)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_206, 0);

    /* Line: 574       : MOVE               : makemove.cob */
    memmove (b_212 + 2LL * ((cob_s64_t)((*(short *)(b_206))) - 1), b_200, 2);
  }
  else
  {
    /* ELSE */

    /* Line: 576       : MOVE               : makemove.cob */
    memmove (b_212 + 2LL * ((cob_s64_t)((*(short *)(b_197))) - 1), b_200, 2);
  }

  /* Line: 579       : MOVE               : makemove.cob */
  memmove (b_212 + 272, b_212 + 294 + 22LL * ((cob_s64_t)((*(short *)(b_198))) - 1), 8);

  /* Line: 581       : SUBTRACT           : makemove.cob */
  cob_sub_s16 (b_212 + 270, 1);

  /* Line: 582       : GOBACK             : makemove.cob */
  goto exit_program;

  /* Line: 584       : Paragraph UNDO-CASTLE-ROOK        : makemove.cob */
  l_34:;

  /* Line: 585       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, &f_207);
  cob_move ((cob_field *)&c_8, &f_208);

  /* Line: 586       : IF                 : makemove.cob */
  if (((int)cob_cmp_s16 (b_193, 0LL) == 0))
  {

    /* Line: 587       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_195, 6LL) == 0))
    {

      /* Line: 588       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_10, &f_207);

      /* Line: 589       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_9, &f_208);
    }
    else
    {
      /* ELSE */

      /* Line: 591       : IF                 : makemove.cob */
      if (((int)cob_cmp_s16 (b_195, 2LL) == 0))
      {

        /* Line: 592       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_11, &f_207);

        /* Line: 593       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_8, &f_208);
      }
    }
  }
  else
  {
    /* ELSE */

    /* Line: 597       : IF                 : makemove.cob */
    if (((int)cob_cmp_s16 (b_195, 118LL) == 0))
    {

      /* Line: 598       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_14, &f_207);

      /* Line: 599       : MOVE               : makemove.cob */
      cob_move ((cob_field *)&c_13, &f_208);
    }
    else
    {
      /* ELSE */

      /* Line: 601       : IF                 : makemove.cob */
      if (((int)cob_cmp_s16 (b_195, 114LL) == 0))
      {

        /* Line: 602       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_16, &f_207);

        /* Line: 603       : MOVE               : makemove.cob */
        cob_move ((cob_field *)&c_15, &f_208);
      }
    }
  }

  /* Line: 608       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_207)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_209, 0);

  /* Line: 609       : COMPUTE            : makemove.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_208)));
  cob_decimal_add (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_210, 0);

  /* Line: 610       : MOVE               : makemove.cob */
  memmove (b_211, b_212 + 2LL * ((cob_s64_t)((*(short *)(b_209))) - 1), 2);

  /* Line: 611       : MOVE               : makemove.cob */
  cob_move ((cob_field *)&c_8, COB_SET_FLD (f0, 2, b_212 + 2LL * ((cob_s64_t)((*(short *)(b_209))) - 1), &a_5));

  /* Line: 612       : MOVE               : makemove.cob */
  memmove (b_212 + 2LL * ((cob_s64_t)((*(short *)(b_210))) - 1), b_211, 2);

  /* Line: 613       : EXIT PARAGRAPH     : makemove.cob */
  goto l_35;

  /* Implicit EXIT label */
  l_35:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 34)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Decrement module reference count */
  if (cob_reference_count) {
      cob_reference_count--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_140;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  UNMAKEMOVE_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_140 = 0;

  /* initialize field SIDE */
  memset (b_193, 0x0, 2);

  /* initialize field FROM-SQ */
  memset (b_194, 0x0, 2);

  /* initialize field TO-SQ */
  memset (b_195, 0x0, 2);

  /* initialize field FROM-IDX */
  memset (b_196, 0x0, 2);

  /* initialize field TO-IDX */
  memset (b_197, 0x0, 2);

  /* initialize field UNDO-IX */
  memset (b_198, 0x0, 2);

  /* initialize field MOVED */
  memset (b_199, 0x0, 2);

  /* initialize field CAPTURED */
  memset (b_200, 0x0, 2);

  /* initialize field IS-EP */
  memset (b_201, 0x0, 2);

  /* initialize field IS-CASTLE */
  memset (b_202, 0x0, 2);

  /* initialize field IS-PROMO */
  memset (b_203, 0x0, 2);

  /* initialize field Q */
  memset (b_204, 0x0, 2);

  /* initialize field CAP-SQ */
  memset (b_205, 0x0, 2);

  /* initialize field CAP-IDX */
  memset (b_206, 0x0, 2);

  /* initialize field ROOK-FROM-SQ */
  memset (b_207, 0x0, 2);

  /* initialize field ROOK-TO-SQ */
  memset (b_208, 0x0, 2);

  /* initialize field ROOK-FROM-IDX */
  memset (b_209, 0x0, 2);

  /* initialize field ROOK-TO-IDX */
  memset (b_210, 0x0, 2);

  /* initialize field ROOK-PIECE */
  memset (b_211, 0x0, 2);


  /* Set Decimal Constant values */
  dc_7 = &kc_7;
  cob_decimal_init (dc_7);
  cob_decimal_set_field (dc_7, (cob_field *)&c_7);

  dc_6 = &kc_6;
  cob_decimal_init (dc_6);
  cob_decimal_set_field (dc_6, (cob_field *)&c_6);

  dc_5 = &kc_5;
  cob_decimal_init (dc_5);
  cob_decimal_set_field (dc_5, (cob_field *)&c_5);

  dc_4 = &kc_4;
  cob_decimal_init (dc_4);
  cob_decimal_set_field (dc_4, (cob_field *)&c_4);

  dc_3 = &kc_3;
  cob_decimal_init (dc_3);
  cob_decimal_set_field (dc_3, (cob_field *)&c_3);

  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  b_140 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_7);
  dc_7 = NULL;
  cob_decimal_clear (dc_6);
  dc_6 = NULL;
  cob_decimal_clear (dc_5);
  dc_5 = NULL;
  cob_decimal_clear (dc_4);
  dc_4 = NULL;
  cob_decimal_clear (dc_3);
  dc_3 = NULL;
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'UNMAKEMOVE' */

/* Initialize module structure for UNMAKEMOVE */
static void UNMAKEMOVE_module_init (cob_module *module)
{
  module->module_name = "UNMAKEMOVE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())UNMAKEMOVE;
  module->module_cancel.funcptr = (void *(*)())UNMAKEMOVE_;
  module->module_ref_count = &cob_reference_count;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

