/* Generated by           cobc 3.2.0 */
/* Generated from         makemove.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'UNMAKEMOVE' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_147 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_148 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_149 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_150 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_151 = NULL;  /* XML-NTEXT */
static unsigned char    *b_152 = NULL;  /* XML-TEXT */
static unsigned char    *b_240 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_212;
static unsigned char    *last_b_234;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_140;    /* RETURN-CODE */
static cob_u8_t    b_193[2] __attribute__((aligned));    /* SIDE */
static cob_u8_t    b_194[2] __attribute__((aligned));    /* FROM-SQ */
static cob_u8_t    b_195[2] __attribute__((aligned));    /* TO-SQ */
static cob_u8_t    b_196[2] __attribute__((aligned));    /* FROM-IDX */
static cob_u8_t    b_197[2] __attribute__((aligned));    /* TO-IDX */
static cob_u8_t    b_198[2] __attribute__((aligned));    /* UNDO-IX */
static cob_u8_t    b_199[2] __attribute__((aligned));    /* MOVED */
static cob_u8_t    b_200[2] __attribute__((aligned));    /* CAPTURED */
static cob_u8_t    b_201[2] __attribute__((aligned));    /* IS-EP */
static cob_u8_t    b_202[2] __attribute__((aligned));    /* IS-CASTLE */
static cob_u8_t    b_203[2] __attribute__((aligned));    /* IS-PROMO */
static cob_u8_t    b_204[2] __attribute__((aligned));    /* Q */
static cob_u8_t    b_205[2] __attribute__((aligned));    /* CAP-SQ */
static cob_u8_t    b_206[2] __attribute__((aligned));    /* CAP-IDX */
static cob_u8_t    b_207[2] __attribute__((aligned));    /* ROOK-FROM-SQ */
static cob_u8_t    b_208[2] __attribute__((aligned));    /* ROOK-TO-SQ */
static cob_u8_t    b_209[2] __attribute__((aligned));    /* ROOK-FROM-IDX */
static cob_u8_t    b_210[2] __attribute__((aligned));    /* ROOK-TO-IDX */
static cob_u8_t    b_211[2] __attribute__((aligned));    /* ROOK-PIECE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_193    = {2, b_193, &a_5};    /* SIDE */
static cob_field f_196    = {2, b_196, &a_5};    /* FROM-IDX */
static cob_field f_197    = {2, b_197, &a_5};    /* TO-IDX */
static cob_field f_198    = {2, b_198, &a_5};    /* UNDO-IX */
static cob_field f_201    = {2, b_201, &a_5};    /* IS-EP */
static cob_field f_202    = {2, b_202, &a_5};    /* IS-CASTLE */
static cob_field f_203    = {2, b_203, &a_5};    /* IS-PROMO */
static cob_field f_204    = {2, b_204, &a_5};    /* Q */
static cob_field f_205    = {2, b_205, &a_5};    /* CAP-SQ */
static cob_field f_206    = {2, b_206, &a_5};    /* CAP-IDX */
static cob_field f_207    = {2, b_207, &a_5};    /* ROOK-FROM-SQ */
static cob_field f_208    = {2, b_208, &a_5};    /* ROOK-TO-SQ */
static cob_field f_209    = {2, b_209, &a_5};    /* ROOK-FROM-IDX */
static cob_field f_210    = {2, b_210, &a_5};    /* ROOK-TO-IDX */
static cob_field f_222    = {2, NULL, &a_5};    /* GS-PLY */
static cob_field f_238    = {2, NULL, &a_5};    /* M-FLAGS */

/* End of fields */

