/* Generated by           cobc 3.2.0 */
/* Generated from         makemove.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'MAKEMOVE' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;

/* EXTERNAL items */
static unsigned char    *b_58 = NULL;  /* HASH-STATE */


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */
static unsigned char    *b_129 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_101;
static unsigned char    *last_b_123;
static unsigned char    *last_b_137;

/* Call pointers */
static cob_call_union    call_ATTACK;
static cob_call_union    call_UNMAKEMOVE;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[4];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_66[2] __attribute__((aligned));    /* SIDE */
static cob_u8_t    b_67[2] __attribute__((aligned));    /* OPP-SIDE */
static cob_u8_t    b_68[2] __attribute__((aligned));    /* FROM-SQ */
static cob_u8_t    b_69[2] __attribute__((aligned));    /* TO-SQ */
static cob_u8_t    b_70[2] __attribute__((aligned));    /* FROM-IDX */
static cob_u8_t    b_71[2] __attribute__((aligned));    /* TO-IDX */
static cob_u8_t    b_72[2] __attribute__((aligned));    /* PIECE */
static cob_u8_t    b_73[2] __attribute__((aligned));    /* CAPTURED */
static cob_u8_t    b_74[2] __attribute__((aligned));    /* UNDO-IX */
static cob_u8_t    b_75[2] __attribute__((aligned));    /* PROMO-PIECE */
static cob_u8_t    b_76[2] __attribute__((aligned));    /* IS-CAPTURE */
static cob_u8_t    b_77[2] __attribute__((aligned));    /* IS-EP */
static cob_u8_t    b_78[2] __attribute__((aligned));    /* IS-CASTLE */
static cob_u8_t    b_79[2] __attribute__((aligned));    /* IS-PROMO */
static cob_u8_t    b_80[2] __attribute__((aligned));    /* IS-PAWN-DOUBLE */
static cob_u8_t    b_81[2] __attribute__((aligned));    /* Q */
static cob_u8_t    b_82[2] __attribute__((aligned));    /* CAP-SQ */
static cob_u8_t    b_83[2] __attribute__((aligned));    /* CAP-IDX */
static cob_u8_t    b_84[2] __attribute__((aligned));    /* KING-SQ */
static cob_u8_t    b_85[2] __attribute__((aligned));    /* ATTACKED */
static cob_u8_t    b_86[2] __attribute__((aligned));    /* ROOK-FROM-SQ */
static cob_u8_t    b_87[2] __attribute__((aligned));    /* ROOK-TO-SQ */
static cob_u8_t    b_88[2] __attribute__((aligned));    /* ROOK-FROM-IDX */
static cob_u8_t    b_89[2] __attribute__((aligned));    /* ROOK-TO-IDX */
static cob_u8_t    b_90[2] __attribute__((aligned));    /* ROOK-PIECE */
static cob_u8_t    b_91[8] __attribute__((aligned));    /* WORK-KEY */
static cob_u8_t    b_92[2] __attribute__((aligned));    /* OLD-CAST-IX */
static cob_u8_t    b_93[2] __attribute__((aligned));    /* OLD-EP-FILE */
static cob_u8_t    b_94[2] __attribute__((aligned));    /* OLD-EP-IX */
static cob_u8_t    b_95[2] __attribute__((aligned));    /* NEW-CAST-IX */
static cob_u8_t    b_96[2] __attribute__((aligned));    /* NEW-EP-FILE */
static cob_u8_t    b_97[2] __attribute__((aligned));    /* NEW-EP-IX */
static cob_u8_t    b_98[2] __attribute__((aligned));    /* H-P */
static cob_u8_t    b_99[2] __attribute__((aligned));    /* H-S */
static cob_u8_t    b_100[8] __attribute__((aligned));    /* H-TMP */

/* End of local data storage */


/* Fields (local) */
static cob_field f_59    = {2, NULL, &a_5};    /* HS-INIT */
static cob_field f_60    = {8, NULL, &a_6};    /* HS-SEED */
static cob_field f_63    = {8, NULL, &a_6};    /* HS-SIDEKEY */
static cob_field f_67    = {2, b_67, &a_5};    /* OPP-SIDE */
static cob_field f_70    = {2, b_70, &a_5};    /* FROM-IDX */
static cob_field f_71    = {2, b_71, &a_5};    /* TO-IDX */
static cob_field f_74    = {2, b_74, &a_5};    /* UNDO-IX */
static cob_field f_75    = {2, b_75, &a_5};    /* PROMO-PIECE */
static cob_field f_76    = {2, b_76, &a_5};    /* IS-CAPTURE */
static cob_field f_77    = {2, b_77, &a_5};    /* IS-EP */
static cob_field f_78    = {2, b_78, &a_5};    /* IS-CASTLE */
static cob_field f_79    = {2, b_79, &a_5};    /* IS-PROMO */
static cob_field f_80    = {2, b_80, &a_5};    /* IS-PAWN-DOUBLE */
static cob_field f_81    = {2, b_81, &a_5};    /* Q */
static cob_field f_82    = {2, b_82, &a_5};    /* CAP-SQ */
static cob_field f_83    = {2, b_83, &a_5};    /* CAP-IDX */
static cob_field f_84    = {2, b_84, &a_5};    /* KING-SQ */
static cob_field f_85    = {2, b_85, &a_5};    /* ATTACKED */
static cob_field f_86    = {2, b_86, &a_5};    /* ROOK-FROM-SQ */
static cob_field f_87    = {2, b_87, &a_5};    /* ROOK-TO-SQ */
static cob_field f_88    = {2, b_88, &a_5};    /* ROOK-FROM-IDX */
static cob_field f_89    = {2, b_89, &a_5};    /* ROOK-TO-IDX */
static cob_field f_90    = {2, b_90, &a_5};    /* ROOK-PIECE */
static cob_field f_91    = {8, b_91, &a_6};    /* WORK-KEY */
static cob_field f_92    = {2, b_92, &a_5};    /* OLD-CAST-IX */
static cob_field f_93    = {2, b_93, &a_5};    /* OLD-EP-FILE */
static cob_field f_94    = {2, b_94, &a_5};    /* OLD-EP-IX */
static cob_field f_95    = {2, b_95, &a_5};    /* NEW-CAST-IX */
static cob_field f_96    = {2, b_96, &a_5};    /* NEW-EP-FILE */
static cob_field f_97    = {2, b_97, &a_5};    /* NEW-EP-IX */
static cob_field f_98    = {2, b_98, &a_5};    /* H-P */
static cob_field f_99    = {2, b_99, &a_5};    /* H-S */
static cob_field f_100    = {8, b_100, &a_6};    /* H-TMP */
static cob_field f_101    = {5912, NULL, &a_9};    /* GAME-STATE */
static cob_field f_105    = {2, NULL, &a_5};    /* GS-CASTLING */
static cob_field f_106    = {2, NULL, &a_5};    /* GS-EP-SQ */
static cob_field f_107    = {2, NULL, &a_5};    /* GS-HALFMOVE */
static cob_field f_111    = {2, NULL, &a_5};    /* GS-PLY */
static cob_field f_123    = {12, NULL, &a_9};    /* MOVE-REC */
static cob_field f_127    = {2, NULL, &a_5};    /* M-FLAGS */
static cob_field f_137    = {2, NULL, &a_5};    /* L-OK */

/* End of fields */

