/* Generated by           cobc 3.2.0 */
/* Generated from         movegen.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'MOVEGEN' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */
static unsigned char    *b_100 = NULL;  /* MOVE-REC */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_78;
static unsigned char    *last_b_106;
static unsigned char    *last_b_114;

/* Call pointers */
static cob_call_union    call_ATTACK;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[4];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_55[48] __attribute__((aligned));    /* OFFSETS */
static cob_u8_t    b_60[2] __attribute__((aligned));    /* OFFSETS-INIT */
static cob_u8_t    b_61[2] __attribute__((aligned));    /* SIDE */
static cob_u8_t    b_62[2] __attribute__((aligned));    /* OPP-SIDE */
static cob_u8_t    b_63[2] __attribute__((aligned));    /* FROM-SQ */
static cob_u8_t    b_64[2] __attribute__((aligned));    /* TO-SQ */
static cob_u8_t    b_65[2] __attribute__((aligned));    /* IDX */
static cob_u8_t    b_66[2] __attribute__((aligned));    /* P */
static cob_u8_t    b_67[2] __attribute__((aligned));    /* TGT */
static cob_u8_t    b_68[2] __attribute__((aligned));    /* PIECE-TYPE */
static cob_u8_t    b_69[2] __attribute__((aligned));    /* RANK */
static cob_u8_t    b_70[2] __attribute__((aligned));    /* I */
static cob_u8_t    b_71[2] __attribute__((aligned));    /* DIR */
static cob_u8_t    b_72[2] __attribute__((aligned));    /* CAP-ONLY */
static cob_u8_t    b_73[2] __attribute__((aligned));    /* ATTACKED */
static cob_u8_t    b_74[2] __attribute__((aligned));    /* RIGHT-QUOT */
static cob_u8_t    b_75[2] __attribute__((aligned));    /* ADD-FLAGS */
static cob_u8_t    b_76[2] __attribute__((aligned));    /* ADD-PROMO */
static cob_u8_t    b_77[2] __attribute__((aligned));    /* BASE-FLAGS */

/* End of local data storage */


/* Fields (local) */
static cob_field f_60    = {2, b_60, &a_3};    /* OFFSETS-INIT */
static cob_field f_62    = {2, b_62, &a_3};    /* OPP-SIDE */
static cob_field f_63    = {2, b_63, &a_3};    /* FROM-SQ */
static cob_field f_64    = {2, b_64, &a_3};    /* TO-SQ */
static cob_field f_65    = {2, b_65, &a_3};    /* IDX */
static cob_field f_68    = {2, b_68, &a_3};    /* PIECE-TYPE */
static cob_field f_69    = {2, b_69, &a_3};    /* RANK */
static cob_field f_70    = {2, b_70, &a_3};    /* I */
static cob_field f_73    = {2, b_73, &a_3};    /* ATTACKED */
static cob_field f_74    = {2, b_74, &a_3};    /* RIGHT-QUOT */
static cob_field f_75    = {2, b_75, &a_3};    /* ADD-FLAGS */
static cob_field f_76    = {2, b_76, &a_3};    /* ADD-PROMO */
static cob_field f_78    = {5912, NULL, &a_4};    /* GAME-STATE */
static cob_field f_82    = {2, NULL, &a_3};    /* GS-CASTLING */
static cob_field f_83    = {2, NULL, &a_3};    /* GS-EP-SQ */
static cob_field f_107    = {2, NULL, &a_3};    /* ML-COUNT */

/* End of fields */

