/* Generated by           cobc 3.2.0 */
/* Generated from         movegen.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE        "movegen.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 05:30:21"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        53021

/* Global variables */
#include "movegen.c.h"

/* Function prototypes */

COB_EXT_EXPORT int        MOVEGEN (cob_u8_t *, cob_u8_t *, cob_u8_t *);
static int        MOVEGEN_ (const int, cob_u8_t *, cob_u8_t *, cob_u8_t *);
static void        MOVEGEN_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MOVEGEN' */

/* ENTRY 'MOVEGEN' */

int
MOVEGEN (cob_u8_t *b_78, cob_u8_t *b_106, cob_u8_t *b_114)
{
  cob_u8_t *cob_parm_78 = NULL;    /* linkage for GAME-STATE */
  cob_u8_t *cob_parm_106 = NULL;    /* linkage for MOVE-LIST */
  cob_u8_t *cob_parm_114 = NULL;    /* linkage for L-CAP-ONLY */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
      cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
      cob_call_params = 3;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_78 = b_78;
  }
  if (cob_call_params > 1) {
    cob_parm_106 = b_106;
  }
  if (cob_call_params > 2) {
    cob_parm_114 = b_114;
  }

  return MOVEGEN_ (0, cob_parm_78, cob_parm_106, cob_parm_114);
}

static int
MOVEGEN_ (const int entry, cob_u8_t *b_78, cob_u8_t *b_106, 
    cob_u8_t *b_114)
{
  /* Program local variables */
  #include "movegen.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_78 = b_78;
  last_b_106 = b_106;
  last_b_114 = b_114;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 38        : Entry     MOVEGEN                 : movegen.cob */
  l_2:;

  /* Line: 38        : IF                 : movegen.cob */
  if (((int)cob_cmp_s16 (b_60, 0LL) == 0))
  {

    /* Line: 39        : PERFORM            : movegen.cob */
    /* PERFORM INIT-OFFSETS */
    frame_ptr++;
    frame_ptr->perform_through = 39;
    frame_ptr->return_address_ptr = &&l_41;
    goto l_39;
    l_41:
    frame_ptr--;

    /* Line: 40        : MOVE               : movegen.cob */
    cob_move ((cob_field *)&c_1, &f_60);
  }

  /* Line: 43        : MOVE               : movegen.cob */
  memmove (b_72, b_114, 2);

  /* Line: 44        : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_10, COB_SET_DATA (f_107, b_106));

  /* Line: 46        : MOVE               : movegen.cob */
  memmove (b_61, b_78 + 256, 2);

  /* Line: 47        : IF                 : movegen.cob */
  if (((int)cob_cmp_s16 (b_61, 0LL) == 0))
  {

    /* Line: 48        : MOVE               : movegen.cob */
    cob_move ((cob_field *)&c_1, &f_62);
  }
  else
  {
    /* ELSE */

    /* Line: 50        : MOVE               : movegen.cob */
    cob_move ((cob_field *)&c_10, &f_62);
  }

  /* Line: 53        : PERFORM            : movegen.cob */
  cob_move ((cob_field *)&c_10, &f_63);
  for (;;)
  {
    /* Line: 53        : UNTIL              : movegen.cob */
    if (((int)cob_cmp_s16 (b_63, 127LL) > 0))
      break;

    /* Line: 54        : IF                 : movegen.cob */
    if (((int)cob_cmp_llint (cob_intr_mod (&f_63, (cob_field *)&c_3), 7LL) <= 0))
    {

      /* Line: 55        : COMPUTE            : movegen.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_add (d_0, dc_1);
      cob_decimal_get_field (d_0, &f_65, 0);

      /* Line: 56        : MOVE               : movegen.cob */
      memmove (b_66, b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 2);

      /* Line: 57        : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_66, 0LL) != 0))
      {

        /* Line: 58        : IF                 : movegen.cob */
        if (((int)cob_cmp_s16 (b_61, 0LL) == 0))
        {

          /* Line: 59        : IF                 : movegen.cob */
          if ((((int)cob_cmp_s16 (b_66, 1LL) >= 0) && 
              ((int)cob_cmp_s16 (b_66, 6LL) <= 0)))
          {

            /* Line: 60        : PERFORM            : movegen.cob */
            /* PERFORM GEN-PIECE */
            frame_ptr++;
            frame_ptr->perform_through = 5;
            frame_ptr->return_address_ptr = &&l_42;
            goto l_5;
            l_42:
            frame_ptr--;
          }
        }
        else
        {
          /* ELSE */

          /* Line: 63        : IF                 : movegen.cob */
          if ((((int)cob_cmp_s16 (b_66, 7LL) >= 0) && 
              ((int)cob_cmp_s16 (b_66, 12LL) <= 0)))
          {

            /* Line: 64        : PERFORM            : movegen.cob */
            /* PERFORM GEN-PIECE */
            frame_ptr++;
            frame_ptr->perform_through = 5;
            frame_ptr->return_address_ptr = &&l_43;
            goto l_5;
            l_43:
            frame_ptr--;
          }
        }
      }
    }
    /* Line: 53        : VARYING            : movegen.cob */
    cob_add_s16 (b_63, 1);
  }

  /* Line: 71        : GOBACK             : movegen.cob */
  goto exit_program;

  /* Line: 73        : Paragraph GEN-PIECE               : movegen.cob */
  l_5:;

  /* Line: 74        : IF                 : movegen.cob */
  if (((int)cob_cmp_s16 (b_66, 6LL) <= 0))
  {

    /* Line: 75        : MOVE               : movegen.cob */
    memcpy (b_68, b_66, 2);
  }
  else
  {
    /* ELSE */

    /* Line: 77        : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_66)));
    cob_decimal_sub (d_0, dc_2);
    cob_decimal_get_field (d_0, &f_68, 0);
  }

  /* Line: 80        : EVALUATE           : movegen.cob */

  /* Line: 81        : WHEN               : movegen.cob */

  if (((int)cob_cmp_s16 (b_68, 1LL) == 0))
  {

    /* Line: 81        : PERFORM            : movegen.cob */
    /* PERFORM GEN-PAWN */
    frame_ptr++;
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_44;
    goto l_8;
    l_44:
    frame_ptr--;
    goto l_6;
  }

  /* Line: 82        : WHEN               : movegen.cob */

  if (((int)cob_cmp_s16 (b_68, 2LL) == 0))
  {

    /* Line: 82        : PERFORM            : movegen.cob */
    /* PERFORM GEN-KNIGHT */
    frame_ptr++;
    frame_ptr->perform_through = 18;
    frame_ptr->return_address_ptr = &&l_45;
    goto l_18;
    l_45:
    frame_ptr--;
    goto l_6;
  }

  /* Line: 83        : WHEN               : movegen.cob */

  if (((int)cob_cmp_s16 (b_68, 3LL) == 0))
  {

    /* Line: 83        : PERFORM            : movegen.cob */
    /* PERFORM GEN-BISHOP */
    frame_ptr++;
    frame_ptr->perform_through = 20;
    frame_ptr->return_address_ptr = &&l_46;
    goto l_20;
    l_46:
    frame_ptr--;
    goto l_6;
  }

  /* Line: 84        : WHEN               : movegen.cob */

  if (((int)cob_cmp_s16 (b_68, 4LL) == 0))
  {

    /* Line: 84        : PERFORM            : movegen.cob */
    /* PERFORM GEN-ROOK */
    frame_ptr++;
    frame_ptr->perform_through = 22;
    frame_ptr->return_address_ptr = &&l_47;
    goto l_22;
    l_47:
    frame_ptr--;
    goto l_6;
  }

  /* Line: 85        : WHEN               : movegen.cob */

  if (((int)cob_cmp_s16 (b_68, 5LL) == 0))
  {

    /* Line: 85        : PERFORM            : movegen.cob */
    /* PERFORM GEN-QUEEN */
    frame_ptr++;
    frame_ptr->perform_through = 24;
    frame_ptr->return_address_ptr = &&l_48;
    goto l_24;
    l_48:
    frame_ptr--;
    goto l_6;
  }

  /* Line: 86        : WHEN               : movegen.cob */

  if (((int)cob_cmp_s16 (b_68, 6LL) == 0))
  {

    /* Line: 86        : PERFORM            : movegen.cob */
    /* PERFORM GEN-KING */
    frame_ptr++;
    frame_ptr->perform_through = 26;
    frame_ptr->return_address_ptr = &&l_49;
    goto l_26;
    l_49:
    frame_ptr--;
    goto l_6;
  }

  /* WHEN OTHER */

  /* Line: 87        : CONTINUE           : movegen.cob */
  ;

  /* End EVALUATE */
  l_6:;

  /* Line: 89        : EXIT PARAGRAPH     : movegen.cob */
  goto l_7;

  /* Implicit EXIT label */
  l_7:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 91        : Paragraph GEN-PAWN                : movegen.cob */
  l_8:;

  /* Line: 92        : DIVIDE             : movegen.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_63)));
  cob_decimal_div (d_0, dc_3);
  cob_decimal_get_field (d_0, &f_69, 0);

  /* Line: 94        : IF                 : movegen.cob */
  if (((int)cob_cmp_s16 (b_61, 0LL) == 0))
  {

    /* Line: 96        : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_63)));
    cob_decimal_add (d_0, dc_4);
    cob_decimal_get_field (d_0, &f_64, 0);

    /* Line: 97        : PERFORM            : movegen.cob */
    /* PERFORM PAWN-CAPTURE-WHITE */
    frame_ptr++;
    frame_ptr->perform_through = 14;
    frame_ptr->return_address_ptr = &&l_50;
    goto l_14;
    l_50:
    frame_ptr--;

    /* Line: 98        : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_63)));
    cob_decimal_add (d_0, dc_5);
    cob_decimal_get_field (d_0, &f_64, 0);

    /* Line: 99        : PERFORM            : movegen.cob */
    /* PERFORM PAWN-CAPTURE-WHITE */
    frame_ptr++;
    frame_ptr->perform_through = 14;
    frame_ptr->return_address_ptr = &&l_51;
    goto l_14;
    l_51:
    frame_ptr--;

    /* Line: 103       : IF                 : movegen.cob */
    if ((((int)cob_cmp_s16 (b_72, 0LL) == 0) || 
        ((int)cob_cmp_s16 (b_69, 6LL) == 0)))
    {

      /* Line: 104       : COMPUTE            : movegen.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_add (d_0, dc_3);
      cob_decimal_get_field (d_0, &f_64, 0);

      /* Line: 105       : PERFORM            : movegen.cob */
      /* PERFORM PAWN-PUSH-WHITE */
      frame_ptr++;
      frame_ptr->perform_through = 10;
      frame_ptr->return_address_ptr = &&l_52;
      goto l_10;
      l_52:
      frame_ptr--;
    }
  }
  else
  {
    /* ELSE */

    /* Line: 109       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_63)));
    cob_decimal_sub (d_0, dc_4);
    cob_decimal_get_field (d_0, &f_64, 0);

    /* Line: 110       : PERFORM            : movegen.cob */
    /* PERFORM PAWN-CAPTURE-BLACK */
    frame_ptr++;
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_53;
    goto l_16;
    l_53:
    frame_ptr--;

    /* Line: 111       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_63)));
    cob_decimal_sub (d_0, dc_5);
    cob_decimal_get_field (d_0, &f_64, 0);

    /* Line: 112       : PERFORM            : movegen.cob */
    /* PERFORM PAWN-CAPTURE-BLACK */
    frame_ptr++;
    frame_ptr->perform_through = 16;
    frame_ptr->return_address_ptr = &&l_54;
    goto l_16;
    l_54:
    frame_ptr--;

    /* Line: 116       : IF                 : movegen.cob */
    if ((((int)cob_cmp_s16 (b_72, 0LL) == 0) || 
        ((int)cob_cmp_s16 (b_69, 1LL) == 0)))
    {

      /* Line: 117       : COMPUTE            : movegen.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_63)));
      cob_decimal_sub (d_0, dc_3);
      cob_decimal_get_field (d_0, &f_64, 0);

      /* Line: 118       : PERFORM            : movegen.cob */
      /* PERFORM PAWN-PUSH-BLACK */
      frame_ptr++;
      frame_ptr->perform_through = 12;
      frame_ptr->return_address_ptr = &&l_55;
      goto l_12;
      l_55:
      frame_ptr--;
    }
  }

  /* Line: 121       : EXIT PARAGRAPH     : movegen.cob */
  goto l_9;

  /* Implicit EXIT label */
  l_9:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 123       : Paragraph PAWN-PUSH-WHITE         : movegen.cob */
  l_10:;

  /* Line: 124       : IF                 : movegen.cob */
  if (((((int)cob_cmp_s16 (b_64, 0LL) >= 0) && 
      ((int)cob_cmp_s16 (b_64, 127LL) <= 0)) && 
      ((int)cob_cmp_llint (cob_intr_mod (&f_64, (cob_field *)&c_3), 7LL) <= 0)))
  {

    /* Line: 125       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_64)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_65, 0);

    /* Line: 126       : IF                 : movegen.cob */
    if (((int)cob_cmp_s16 (b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 0LL) == 0))
    {

      /* Line: 127       : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_69, 6LL) == 0))
      {

        /* Line: 128       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_75);

        /* Line: 129       : PERFORM            : movegen.cob */
        /* PERFORM ADD-PROMOS */
        frame_ptr++;
        frame_ptr->perform_through = 35;
        frame_ptr->return_address_ptr = &&l_56;
        goto l_35;
        l_56:
        frame_ptr--;
      }
      else
      {
        /* ELSE */

        /* Line: 131       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_75);

        /* Line: 132       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_76);

        /* Line: 133       : PERFORM            : movegen.cob */
        /* PERFORM ADD-MOVE */
        frame_ptr++;
        frame_ptr->perform_through = 37;
        frame_ptr->return_address_ptr = &&l_57;
        goto l_37;
        l_57:
        frame_ptr--;

        /* Line: 134       : IF                 : movegen.cob */
        if (((int)cob_cmp_s16 (b_69, 1LL) == 0))
        {

          /* Line: 135       : COMPUTE            : movegen.cob */
          cob_decimal_set_llint (d_0, (*(short *)(b_63)));
          cob_decimal_add (d_0, dc_6);
          cob_decimal_get_field (d_0, &f_64, 0);

          /* Line: 136       : COMPUTE            : movegen.cob */
          cob_decimal_set_llint (d_0, (*(short *)(b_64)));
          cob_decimal_add (d_0, dc_1);
          cob_decimal_get_field (d_0, &f_65, 0);

          /* Line: 137       : IF                 : movegen.cob */
          if (((int)cob_cmp_s16 (b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 0LL) == 0))
          {

            /* Line: 138       : MOVE               : movegen.cob */
            cob_move ((cob_field *)&c_3, &f_75);

            /* Line: 139       : MOVE               : movegen.cob */
            cob_move ((cob_field *)&c_10, &f_76);

            /* Line: 140       : PERFORM            : movegen.cob */
            /* PERFORM ADD-MOVE */
            frame_ptr++;
            frame_ptr->perform_through = 37;
            frame_ptr->return_address_ptr = &&l_58;
            goto l_37;
            l_58:
            frame_ptr--;
          }
        }
      }
    }
  }

  /* Line: 146       : EXIT PARAGRAPH     : movegen.cob */
  goto l_11;

  /* Implicit EXIT label */
  l_11:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 148       : Paragraph PAWN-PUSH-BLACK         : movegen.cob */
  l_12:;

  /* Line: 149       : IF                 : movegen.cob */
  if (((((int)cob_cmp_s16 (b_64, 0LL) >= 0) && 
      ((int)cob_cmp_s16 (b_64, 127LL) <= 0)) && 
      ((int)cob_cmp_llint (cob_intr_mod (&f_64, (cob_field *)&c_3), 7LL) <= 0)))
  {

    /* Line: 150       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_64)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_65, 0);

    /* Line: 151       : IF                 : movegen.cob */
    if (((int)cob_cmp_s16 (b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 0LL) == 0))
    {

      /* Line: 152       : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_69, 1LL) == 0))
      {

        /* Line: 153       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_75);

        /* Line: 154       : PERFORM            : movegen.cob */
        /* PERFORM ADD-PROMOS */
        frame_ptr++;
        frame_ptr->perform_through = 35;
        frame_ptr->return_address_ptr = &&l_59;
        goto l_35;
        l_59:
        frame_ptr--;
      }
      else
      {
        /* ELSE */

        /* Line: 156       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_75);

        /* Line: 157       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_76);

        /* Line: 158       : PERFORM            : movegen.cob */
        /* PERFORM ADD-MOVE */
        frame_ptr++;
        frame_ptr->perform_through = 37;
        frame_ptr->return_address_ptr = &&l_60;
        goto l_37;
        l_60:
        frame_ptr--;

        /* Line: 159       : IF                 : movegen.cob */
        if (((int)cob_cmp_s16 (b_69, 6LL) == 0))
        {

          /* Line: 160       : COMPUTE            : movegen.cob */
          cob_decimal_set_llint (d_0, (*(short *)(b_63)));
          cob_decimal_sub (d_0, dc_6);
          cob_decimal_get_field (d_0, &f_64, 0);

          /* Line: 161       : COMPUTE            : movegen.cob */
          cob_decimal_set_llint (d_0, (*(short *)(b_64)));
          cob_decimal_add (d_0, dc_1);
          cob_decimal_get_field (d_0, &f_65, 0);

          /* Line: 162       : IF                 : movegen.cob */
          if (((int)cob_cmp_s16 (b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 0LL) == 0))
          {

            /* Line: 163       : MOVE               : movegen.cob */
            cob_move ((cob_field *)&c_3, &f_75);

            /* Line: 164       : MOVE               : movegen.cob */
            cob_move ((cob_field *)&c_10, &f_76);

            /* Line: 165       : PERFORM            : movegen.cob */
            /* PERFORM ADD-MOVE */
            frame_ptr++;
            frame_ptr->perform_through = 37;
            frame_ptr->return_address_ptr = &&l_61;
            goto l_37;
            l_61:
            frame_ptr--;
          }
        }
      }
    }
  }

  /* Line: 171       : EXIT PARAGRAPH     : movegen.cob */
  goto l_13;

  /* Implicit EXIT label */
  l_13:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 173       : Paragraph PAWN-CAPTURE-WHITE      : movegen.cob */
  l_14:;

  /* Line: 174       : IF                 : movegen.cob */
  if (((((int)cob_cmp_s16 (b_64, 0LL) >= 0) && 
      ((int)cob_cmp_s16 (b_64, 127LL) <= 0)) && 
      ((int)cob_cmp_llint (cob_intr_mod (&f_64, (cob_field *)&c_3), 7LL) <= 0)))
  {

    /* Line: 175       : IF                 : movegen.cob */
    if (((int)cob_cmp_s16 (b_64, cob_get_llint (COB_SET_DATA (f_83, b_78 + 260))) == 0))
    {

      /* Line: 176       : COMPUTE            : movegen.cob */
      cob_decimal_set_llint (d_0, 3LL);
      cob_decimal_get_field (d_0, &f_75, 0);

      /* Line: 177       : MOVE               : movegen.cob */
      cob_move ((cob_field *)&c_10, &f_76);

      /* Line: 178       : PERFORM            : movegen.cob */
      /* PERFORM ADD-MOVE */
      frame_ptr++;
      frame_ptr->perform_through = 37;
      frame_ptr->return_address_ptr = &&l_62;
      goto l_37;
      l_62:
      frame_ptr--;
    }
    else
    {
      /* ELSE */

      /* Line: 180       : COMPUTE            : movegen.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_64)));
      cob_decimal_add (d_0, dc_1);
      cob_decimal_get_field (d_0, &f_65, 0);

      /* Line: 181       : MOVE               : movegen.cob */
      memmove (b_67, b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 2);

      /* Line: 182       : IF                 : movegen.cob */
      if ((((int)cob_cmp_s16 (b_67, 7LL) >= 0) && 
          ((int)cob_cmp_s16 (b_67, 12LL) <= 0)))
      {

        /* Line: 183       : IF                 : movegen.cob */
        if (((int)cob_cmp_s16 (b_69, 6LL) == 0))
        {

          /* Line: 184       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_1, &f_75);

          /* Line: 185       : PERFORM            : movegen.cob */
          /* PERFORM ADD-PROMOS */
          frame_ptr++;
          frame_ptr->perform_through = 35;
          frame_ptr->return_address_ptr = &&l_63;
          goto l_35;
          l_63:
          frame_ptr--;
        }
        else
        {
          /* ELSE */

          /* Line: 187       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_1, &f_75);

          /* Line: 188       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_76);

          /* Line: 189       : PERFORM            : movegen.cob */
          /* PERFORM ADD-MOVE */
          frame_ptr++;
          frame_ptr->perform_through = 37;
          frame_ptr->return_address_ptr = &&l_64;
          goto l_37;
          l_64:
          frame_ptr--;
        }
      }
    }
  }

  /* Line: 194       : EXIT PARAGRAPH     : movegen.cob */
  goto l_15;

  /* Implicit EXIT label */
  l_15:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address_ptr;

  /* Line: 196       : Paragraph PAWN-CAPTURE-BLACK      : movegen.cob */
  l_16:;

  /* Line: 197       : IF                 : movegen.cob */
  if (((((int)cob_cmp_s16 (b_64, 0LL) >= 0) && 
      ((int)cob_cmp_s16 (b_64, 127LL) <= 0)) && 
      ((int)cob_cmp_llint (cob_intr_mod (&f_64, (cob_field *)&c_3), 7LL) <= 0)))
  {

    /* Line: 198       : IF                 : movegen.cob */
    if (((int)cob_cmp_s16 (b_64, cob_get_llint (COB_SET_DATA (f_83, b_78 + 260))) == 0))
    {

      /* Line: 199       : COMPUTE            : movegen.cob */
      cob_decimal_set_llint (d_0, 3LL);
      cob_decimal_get_field (d_0, &f_75, 0);

      /* Line: 200       : MOVE               : movegen.cob */
      cob_move ((cob_field *)&c_10, &f_76);

      /* Line: 201       : PERFORM            : movegen.cob */
      /* PERFORM ADD-MOVE */
      frame_ptr++;
      frame_ptr->perform_through = 37;
      frame_ptr->return_address_ptr = &&l_65;
      goto l_37;
      l_65:
      frame_ptr--;
    }
    else
    {
      /* ELSE */

      /* Line: 203       : COMPUTE            : movegen.cob */
      cob_decimal_set_llint (d_0, (*(short *)(b_64)));
      cob_decimal_add (d_0, dc_1);
      cob_decimal_get_field (d_0, &f_65, 0);

      /* Line: 204       : MOVE               : movegen.cob */
      memmove (b_67, b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 2);

      /* Line: 205       : IF                 : movegen.cob */
      if ((((int)cob_cmp_s16 (b_67, 1LL) >= 0) && 
          ((int)cob_cmp_s16 (b_67, 6LL) <= 0)))
      {

        /* Line: 206       : IF                 : movegen.cob */
        if (((int)cob_cmp_s16 (b_69, 1LL) == 0))
        {

          /* Line: 207       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_1, &f_75);

          /* Line: 208       : PERFORM            : movegen.cob */
          /* PERFORM ADD-PROMOS */
          frame_ptr++;
          frame_ptr->perform_through = 35;
          frame_ptr->return_address_ptr = &&l_66;
          goto l_35;
          l_66:
          frame_ptr--;
        }
        else
        {
          /* ELSE */

          /* Line: 210       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_1, &f_75);

          /* Line: 211       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_76);

          /* Line: 212       : PERFORM            : movegen.cob */
          /* PERFORM ADD-MOVE */
          frame_ptr++;
          frame_ptr->perform_through = 37;
          frame_ptr->return_address_ptr = &&l_67;
          goto l_37;
          l_67:
          frame_ptr--;
        }
      }
    }
  }

  /* Line: 217       : EXIT PARAGRAPH     : movegen.cob */
  goto l_17;

  /* Implicit EXIT label */
  l_17:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Line: 219       : Paragraph GEN-KNIGHT              : movegen.cob */
  l_18:;

  /* Line: 220       : PERFORM            : movegen.cob */
  cob_move ((cob_field *)&c_1, &f_70);
  for (;;)
  {
    /* Line: 220       : UNTIL              : movegen.cob */
    if (((int)cob_cmp_s16 (b_70, 8LL) > 0))
      break;

    /* Line: 221       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_63)));
    cob_decimal_set_llint (d_1, cob_get_llint (COB_SET_FLD (f0, 2, b_55 + 2LL * ((cob_s64_t)((*(short *)(b_70))) - 1), &a_3)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_64, 0);

    /* Line: 222       : PERFORM            : movegen.cob */
    /* PERFORM STEP-TO */
    frame_ptr++;
    frame_ptr->perform_through = 28;
    frame_ptr->return_address_ptr = &&l_68;
    goto l_28;
    l_68:
    frame_ptr--;
    /* Line: 220       : VARYING            : movegen.cob */
    cob_add_s16 (b_70, 1);
  }

  /* Line: 224       : EXIT PARAGRAPH     : movegen.cob */
  goto l_19;

  /* Implicit EXIT label */
  l_19:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 18)
    goto *frame_ptr->return_address_ptr;

  /* Line: 226       : Paragraph GEN-BISHOP              : movegen.cob */
  l_20:;

  /* Line: 227       : PERFORM            : movegen.cob */
  cob_move ((cob_field *)&c_1, &f_70);
  for (;;)
  {
    /* Line: 227       : UNTIL              : movegen.cob */
    if (((int)cob_cmp_s16 (b_70, 4LL) > 0))
      break;

    /* Line: 228       : MOVE               : movegen.cob */
    memcpy (b_71, b_55 + 32 + 2LL * ((cob_s64_t)((*(short *)(b_70))) - 1), 2);

    /* Line: 229       : PERFORM            : movegen.cob */
    /* PERFORM SLIDE-DIR */
    frame_ptr++;
    frame_ptr->perform_through = 30;
    frame_ptr->return_address_ptr = &&l_69;
    goto l_30;
    l_69:
    frame_ptr--;
    /* Line: 227       : VARYING            : movegen.cob */
    cob_add_s16 (b_70, 1);
  }

  /* Line: 231       : EXIT PARAGRAPH     : movegen.cob */
  goto l_21;

  /* Implicit EXIT label */
  l_21:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 20)
    goto *frame_ptr->return_address_ptr;

  /* Line: 233       : Paragraph GEN-ROOK                : movegen.cob */
  l_22:;

  /* Line: 234       : PERFORM            : movegen.cob */
  cob_move ((cob_field *)&c_1, &f_70);
  for (;;)
  {
    /* Line: 234       : UNTIL              : movegen.cob */
    if (((int)cob_cmp_s16 (b_70, 4LL) > 0))
      break;

    /* Line: 235       : MOVE               : movegen.cob */
    memcpy (b_71, b_55 + 40 + 2LL * ((cob_s64_t)((*(short *)(b_70))) - 1), 2);

    /* Line: 236       : PERFORM            : movegen.cob */
    /* PERFORM SLIDE-DIR */
    frame_ptr++;
    frame_ptr->perform_through = 30;
    frame_ptr->return_address_ptr = &&l_70;
    goto l_30;
    l_70:
    frame_ptr--;
    /* Line: 234       : VARYING            : movegen.cob */
    cob_add_s16 (b_70, 1);
  }

  /* Line: 238       : EXIT PARAGRAPH     : movegen.cob */
  goto l_23;

  /* Implicit EXIT label */
  l_23:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 22)
    goto *frame_ptr->return_address_ptr;

  /* Line: 240       : Paragraph GEN-QUEEN               : movegen.cob */
  l_24:;

  /* Line: 241       : PERFORM            : movegen.cob */
  cob_move ((cob_field *)&c_1, &f_70);
  for (;;)
  {
    /* Line: 241       : UNTIL              : movegen.cob */
    if (((int)cob_cmp_s16 (b_70, 4LL) > 0))
      break;

    /* Line: 242       : MOVE               : movegen.cob */
    memcpy (b_71, b_55 + 32 + 2LL * ((cob_s64_t)((*(short *)(b_70))) - 1), 2);

    /* Line: 243       : PERFORM            : movegen.cob */
    /* PERFORM SLIDE-DIR */
    frame_ptr++;
    frame_ptr->perform_through = 30;
    frame_ptr->return_address_ptr = &&l_71;
    goto l_30;
    l_71:
    frame_ptr--;
    /* Line: 241       : VARYING            : movegen.cob */
    cob_add_s16 (b_70, 1);
  }

  /* Line: 245       : PERFORM            : movegen.cob */
  cob_move ((cob_field *)&c_1, &f_70);
  for (;;)
  {
    /* Line: 245       : UNTIL              : movegen.cob */
    if (((int)cob_cmp_s16 (b_70, 4LL) > 0))
      break;

    /* Line: 246       : MOVE               : movegen.cob */
    memcpy (b_71, b_55 + 40 + 2LL * ((cob_s64_t)((*(short *)(b_70))) - 1), 2);

    /* Line: 247       : PERFORM            : movegen.cob */
    /* PERFORM SLIDE-DIR */
    frame_ptr++;
    frame_ptr->perform_through = 30;
    frame_ptr->return_address_ptr = &&l_72;
    goto l_30;
    l_72:
    frame_ptr--;
    /* Line: 245       : VARYING            : movegen.cob */
    cob_add_s16 (b_70, 1);
  }

  /* Line: 249       : EXIT PARAGRAPH     : movegen.cob */
  goto l_25;

  /* Implicit EXIT label */
  l_25:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 24)
    goto *frame_ptr->return_address_ptr;

  /* Line: 251       : Paragraph GEN-KING                : movegen.cob */
  l_26:;

  /* Line: 252       : PERFORM            : movegen.cob */
  cob_move ((cob_field *)&c_1, &f_70);
  for (;;)
  {
    /* Line: 252       : UNTIL              : movegen.cob */
    if (((int)cob_cmp_s16 (b_70, 8LL) > 0))
      break;

    /* Line: 253       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_63)));
    cob_decimal_set_llint (d_1, cob_get_llint (COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * ((cob_s64_t)((*(short *)(b_70))) - 1), &a_3)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_64, 0);

    /* Line: 254       : PERFORM            : movegen.cob */
    /* PERFORM STEP-TO */
    frame_ptr++;
    frame_ptr->perform_through = 28;
    frame_ptr->return_address_ptr = &&l_73;
    goto l_28;
    l_73:
    frame_ptr--;
    /* Line: 252       : VARYING            : movegen.cob */
    cob_add_s16 (b_70, 1);
  }

  /* Line: 257       : IF                 : movegen.cob */
  if (((int)cob_cmp_s16 (b_72, 0LL) == 0))
  {

    /* Line: 258       : PERFORM            : movegen.cob */
    /* PERFORM GEN-CASTLING */
    frame_ptr++;
    frame_ptr->perform_through = 33;
    frame_ptr->return_address_ptr = &&l_74;
    goto l_33;
    l_74:
    frame_ptr--;
  }

  /* Line: 260       : EXIT PARAGRAPH     : movegen.cob */
  goto l_27;

  /* Implicit EXIT label */
  l_27:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 26)
    goto *frame_ptr->return_address_ptr;

  /* Line: 262       : Paragraph STEP-TO                 : movegen.cob */
  l_28:;

  /* Line: 263       : IF                 : movegen.cob */
  if (((((int)cob_cmp_s16 (b_64, 0LL) >= 0) && 
      ((int)cob_cmp_s16 (b_64, 127LL) <= 0)) && 
      ((int)cob_cmp_llint (cob_intr_mod (&f_64, (cob_field *)&c_3), 7LL) <= 0)))
  {

    /* Line: 264       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_64)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_65, 0);

    /* Line: 265       : MOVE               : movegen.cob */
    memmove (b_67, b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 2);

    /* Line: 266       : IF                 : movegen.cob */
    if (((int)cob_cmp_s16 (b_67, 0LL) == 0))
    {

      /* Line: 267       : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_72, 0LL) == 0))
      {

        /* Line: 268       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_75);

        /* Line: 269       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_76);

        /* Line: 270       : PERFORM            : movegen.cob */
        /* PERFORM ADD-MOVE */
        frame_ptr++;
        frame_ptr->perform_through = 37;
        frame_ptr->return_address_ptr = &&l_75;
        goto l_37;
        l_75:
        frame_ptr--;
      }
    }
    else
    {
      /* ELSE */

      /* Line: 273       : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_61, 0LL) == 0))
      {

        /* Line: 274       : IF                 : movegen.cob */
        if ((((int)cob_cmp_s16 (b_67, 7LL) >= 0) && 
            ((int)cob_cmp_s16 (b_67, 12LL) <= 0)))
        {

          /* Line: 275       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_1, &f_75);

          /* Line: 276       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_76);

          /* Line: 277       : PERFORM            : movegen.cob */
          /* PERFORM ADD-MOVE */
          frame_ptr++;
          frame_ptr->perform_through = 37;
          frame_ptr->return_address_ptr = &&l_76;
          goto l_37;
          l_76:
          frame_ptr--;
        }
      }
      else
      {
        /* ELSE */

        /* Line: 280       : IF                 : movegen.cob */
        if ((((int)cob_cmp_s16 (b_67, 1LL) >= 0) && 
            ((int)cob_cmp_s16 (b_67, 6LL) <= 0)))
        {

          /* Line: 281       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_1, &f_75);

          /* Line: 282       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_76);

          /* Line: 283       : PERFORM            : movegen.cob */
          /* PERFORM ADD-MOVE */
          frame_ptr++;
          frame_ptr->perform_through = 37;
          frame_ptr->return_address_ptr = &&l_77;
          goto l_37;
          l_77:
          frame_ptr--;
        }
      }
    }
  }

  /* Line: 288       : EXIT PARAGRAPH     : movegen.cob */
  goto l_29;

  /* Implicit EXIT label */
  l_29:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 28)
    goto *frame_ptr->return_address_ptr;

  /* Line: 290       : Paragraph SLIDE-DIR               : movegen.cob */
  l_30:;

  /* Line: 291       : COMPUTE            : movegen.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_63)));
  cob_decimal_set_llint (d_1, (*(short *)(b_71)));
  cob_decimal_add (d_0, d_1);
  cob_decimal_get_field (d_0, &f_64, 0);

  /* Line: 292       : PERFORM            : movegen.cob */
  for (;;)
  {
    /* Line: 292       : UNTIL              : movegen.cob */
    if (((((int)cob_cmp_s16 (b_64, 0LL) < 0) || 
        ((int)cob_cmp_s16 (b_64, 127LL) > 0)) || 
        ((int)cob_cmp_llint (cob_intr_mod (&f_64, (cob_field *)&c_3), 7LL) > 0)))
      break;

    /* Line: 293       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_64)));
    cob_decimal_add (d_0, dc_1);
    cob_decimal_get_field (d_0, &f_65, 0);

    /* Line: 294       : MOVE               : movegen.cob */
    memmove (b_67, b_78 + 2LL * ((cob_s64_t)((*(short *)(b_65))) - 1), 2);

    /* Line: 295       : IF                 : movegen.cob */
    if (((int)cob_cmp_s16 (b_67, 0LL) == 0))
    {

      /* Line: 296       : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_72, 0LL) == 0))
      {

        /* Line: 297       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_75);

        /* Line: 298       : MOVE               : movegen.cob */
        cob_move ((cob_field *)&c_10, &f_76);

        /* Line: 299       : PERFORM            : movegen.cob */
        /* PERFORM ADD-MOVE */
        frame_ptr++;
        frame_ptr->perform_through = 37;
        frame_ptr->return_address_ptr = &&l_78;
        goto l_37;
        l_78:
        frame_ptr--;
      }
    }
    else
    {
      /* ELSE */

      /* Line: 302       : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_61, 0LL) == 0))
      {

        /* Line: 303       : IF                 : movegen.cob */
        if ((((int)cob_cmp_s16 (b_67, 7LL) >= 0) && 
            ((int)cob_cmp_s16 (b_67, 12LL) <= 0)))
        {

          /* Line: 304       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_1, &f_75);

          /* Line: 305       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_76);

          /* Line: 306       : PERFORM            : movegen.cob */
          /* PERFORM ADD-MOVE */
          frame_ptr++;
          frame_ptr->perform_through = 37;
          frame_ptr->return_address_ptr = &&l_79;
          goto l_37;
          l_79:
          frame_ptr--;
        }
      }
      else
      {
        /* ELSE */

        /* Line: 309       : IF                 : movegen.cob */
        if ((((int)cob_cmp_s16 (b_67, 1LL) >= 0) && 
            ((int)cob_cmp_s16 (b_67, 6LL) <= 0)))
        {

          /* Line: 310       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_1, &f_75);

          /* Line: 311       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_76);

          /* Line: 312       : PERFORM            : movegen.cob */
          /* PERFORM ADD-MOVE */
          frame_ptr++;
          frame_ptr->perform_through = 37;
          frame_ptr->return_address_ptr = &&l_80;
          goto l_37;
          l_80:
          frame_ptr--;
        }
      }

      /* Line: 315       : EXIT PERFORM       : movegen.cob */
      goto l_31;
    }

    /* Line: 317       : COMPUTE            : movegen.cob */
    cob_decimal_set_llint (d_0, (*(short *)(b_64)));
    cob_decimal_set_llint (d_1, (*(short *)(b_71)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_64, 0);
  }

  /* Implicit EXIT label */
  l_31:;

  /* Line: 319       : EXIT PARAGRAPH     : movegen.cob */
  goto l_32;

  /* Implicit EXIT label */
  l_32:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 30)
    goto *frame_ptr->return_address_ptr;

  /* Line: 321       : Paragraph GEN-CASTLING            : movegen.cob */
  l_33:;

  /* Line: 322       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_10, &f_73);

  /* Line: 324       : IF                 : movegen.cob */
  if (((int)cob_cmp_s16 (b_61, 0LL) == 0))
  {

    /* Line: 325       : IF                 : movegen.cob */
    if (((int)cob_cmp_s16 (b_63, 4LL) == 0))
    {

      /* Line: 326       : CALL               : movegen.cob */
      cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
      cob_procedure_params[1] = &f_63;
      cob_procedure_params[2] = &f_62;
      cob_procedure_params[3] = &f_73;
      cob_glob_ptr->cob_call_params = 4;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, b_63, b_62, b_73);

      /* Line: 327       : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
      {

        /* Line: 329       : DIVIDE             : movegen.cob */
        cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_82, b_78 + 258)));
        cob_decimal_get_field (d_0, &f_74, 0);

        /* Line: 330       : IF                 : movegen.cob */
        if ((((((int)cob_cmp_llint (cob_intr_mod (&f_74, (cob_field *)&c_7), 1LL) == 0) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 5LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 6LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 7LL, 4LL) == 0)))
        {

          /* Line: 334       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_73);

          /* Line: 335       : CALL               : movegen.cob */
          {
            cob_content    content_2;
            cob_field    content_fb_2 = { 4, NULL, &a_5 };

            content_fb_2.data = content_2.data;
            content_2.dataint = 5;
            cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
            cob_procedure_params[1] = &content_fb_2;
            cob_procedure_params[2] = &f_62;
            cob_procedure_params[3] = &f_73;
            cob_glob_ptr->cob_call_params = 4;
            cob_glob_ptr->cob_stmt_exception = 0;
            if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                        if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
            {
              call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
            }
            b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, content_2.data, b_62, b_73);
          }

          /* Line: 336       : IF                 : movegen.cob */
          if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
          {

            /* Line: 337       : CALL               : movegen.cob */
            {
              cob_content    content_2;
              cob_field    content_fb_2 = { 4, NULL, &a_5 };

              content_fb_2.data = content_2.data;
              content_2.dataint = 6;
              cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
              cob_procedure_params[1] = &content_fb_2;
              cob_procedure_params[2] = &f_62;
              cob_procedure_params[3] = &f_73;
              cob_glob_ptr->cob_call_params = 4;
              cob_glob_ptr->cob_stmt_exception = 0;
              if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                            if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
              {
                call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
              }
              b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, content_2.data, b_62, b_73);
            }

            /* Line: 338       : IF                 : movegen.cob */
            if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
            {

              /* Line: 339       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_2, &f_64);

              /* Line: 340       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_8, &f_75);

              /* Line: 341       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_10, &f_76);

              /* Line: 342       : PERFORM            : movegen.cob */
              /* PERFORM ADD-MOVE */
              frame_ptr++;
              frame_ptr->perform_through = 37;
              frame_ptr->return_address_ptr = &&l_81;
              goto l_37;
              l_81:
              frame_ptr--;
            }
          }
        }

        /* Line: 348       : DIVIDE             : movegen.cob */
        cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_82, b_78 + 258)));
        cob_decimal_div (d_0, dc_7);
        cob_decimal_get_field (d_0, &f_74, 0);

        /* Line: 349       : IF                 : movegen.cob */
        if (((((((int)cob_cmp_llint (cob_intr_mod (&f_74, (cob_field *)&c_7), 1LL) == 0) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 1LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 2LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 3LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78, 4LL) == 0)))
        {

          /* Line: 354       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_73);

          /* Line: 355       : CALL               : movegen.cob */
          {
            cob_content    content_2;
            cob_field    content_fb_2 = { 4, NULL, &a_5 };

            content_fb_2.data = content_2.data;
            content_2.dataint = 3;
            cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
            cob_procedure_params[1] = &content_fb_2;
            cob_procedure_params[2] = &f_62;
            cob_procedure_params[3] = &f_73;
            cob_glob_ptr->cob_call_params = 4;
            cob_glob_ptr->cob_stmt_exception = 0;
            if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                        if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
            {
              call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
            }
            b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, content_2.data, b_62, b_73);
          }

          /* Line: 356       : IF                 : movegen.cob */
          if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
          {

            /* Line: 357       : CALL               : movegen.cob */
            {
              cob_content    content_2;
              cob_field    content_fb_2 = { 4, NULL, &a_5 };

              content_fb_2.data = content_2.data;
              content_2.dataint = 2;
              cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
              cob_procedure_params[1] = &content_fb_2;
              cob_procedure_params[2] = &f_62;
              cob_procedure_params[3] = &f_73;
              cob_glob_ptr->cob_call_params = 4;
              cob_glob_ptr->cob_stmt_exception = 0;
              if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                            if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
              {
                call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
              }
              b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, content_2.data, b_62, b_73);
            }

            /* Line: 358       : IF                 : movegen.cob */
            if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
            {

              /* Line: 359       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_7, &f_64);

              /* Line: 360       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_8, &f_75);

              /* Line: 361       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_10, &f_76);

              /* Line: 362       : PERFORM            : movegen.cob */
              /* PERFORM ADD-MOVE */
              frame_ptr++;
              frame_ptr->perform_through = 37;
              frame_ptr->return_address_ptr = &&l_82;
              goto l_37;
              l_82:
              frame_ptr--;
            }
          }
        }
      }
    }
  }
  else
  {
    /* ELSE */

    /* Line: 369       : IF                 : movegen.cob */
    if (((int)cob_cmp_s16 (b_63, 116LL) == 0))
    {

      /* Line: 370       : CALL               : movegen.cob */
      cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
      cob_procedure_params[1] = &f_63;
      cob_procedure_params[2] = &f_62;
      cob_procedure_params[3] = &f_73;
      cob_glob_ptr->cob_call_params = 4;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, b_63, b_62, b_73);

      /* Line: 371       : IF                 : movegen.cob */
      if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
      {

        /* Line: 373       : DIVIDE             : movegen.cob */
        cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_82, b_78 + 258)));
        cob_decimal_div (d_0, dc_8);
        cob_decimal_get_field (d_0, &f_74, 0);

        /* Line: 374       : IF                 : movegen.cob */
        if ((((((int)cob_cmp_llint (cob_intr_mod (&f_74, (cob_field *)&c_7), 1LL) == 0) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 117LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 118LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 119LL, 10LL) == 0)))
        {

          /* Line: 378       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_73);

          /* Line: 379       : CALL               : movegen.cob */
          {
            cob_content    content_2;
            cob_field    content_fb_2 = { 4, NULL, &a_5 };

            content_fb_2.data = content_2.data;
            content_2.dataint = 117;
            cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
            cob_procedure_params[1] = &content_fb_2;
            cob_procedure_params[2] = &f_62;
            cob_procedure_params[3] = &f_73;
            cob_glob_ptr->cob_call_params = 4;
            cob_glob_ptr->cob_stmt_exception = 0;
            if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                        if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
            {
              call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
            }
            b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, content_2.data, b_62, b_73);
          }

          /* Line: 380       : IF                 : movegen.cob */
          if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
          {

            /* Line: 381       : CALL               : movegen.cob */
            {
              cob_content    content_2;
              cob_field    content_fb_2 = { 4, NULL, &a_5 };

              content_fb_2.data = content_2.data;
              content_2.dataint = 118;
              cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
              cob_procedure_params[1] = &content_fb_2;
              cob_procedure_params[2] = &f_62;
              cob_procedure_params[3] = &f_73;
              cob_glob_ptr->cob_call_params = 4;
              cob_glob_ptr->cob_stmt_exception = 0;
              if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                            if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
              {
                call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
              }
              b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, content_2.data, b_62, b_73);
            }

            /* Line: 382       : IF                 : movegen.cob */
            if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
            {

              /* Line: 383       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_11, &f_64);

              /* Line: 384       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_8, &f_75);

              /* Line: 385       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_10, &f_76);

              /* Line: 386       : PERFORM            : movegen.cob */
              /* PERFORM ADD-MOVE */
              frame_ptr++;
              frame_ptr->perform_through = 37;
              frame_ptr->return_address_ptr = &&l_83;
              goto l_37;
              l_83:
              frame_ptr--;
            }
          }
        }

        /* Line: 392       : DIVIDE             : movegen.cob */
        cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_82, b_78 + 258)));
        cob_decimal_div (d_0, dc_9);
        cob_decimal_get_field (d_0, &f_74, 0);

        /* Line: 393       : IF                 : movegen.cob */
        if (((((((int)cob_cmp_llint (cob_intr_mod (&f_74, (cob_field *)&c_7), 1LL) == 0) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 113LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 114LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 115LL, 0LL) == 0)) && 
            ((int)cob_cmp_s16 (b_78 + 2LL * 112LL, 10LL) == 0)))
        {

          /* Line: 398       : MOVE               : movegen.cob */
          cob_move ((cob_field *)&c_10, &f_73);

          /* Line: 399       : CALL               : movegen.cob */
          {
            cob_content    content_2;
            cob_field    content_fb_2 = { 4, NULL, &a_5 };

            content_fb_2.data = content_2.data;
            content_2.dataint = 115;
            cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
            cob_procedure_params[1] = &content_fb_2;
            cob_procedure_params[2] = &f_62;
            cob_procedure_params[3] = &f_73;
            cob_glob_ptr->cob_call_params = 4;
            cob_glob_ptr->cob_stmt_exception = 0;
            if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                        if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
            {
              call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
            }
            b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, content_2.data, b_62, b_73);
          }

          /* Line: 400       : IF                 : movegen.cob */
          if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
          {

            /* Line: 401       : CALL               : movegen.cob */
            {
              cob_content    content_2;
              cob_field    content_fb_2 = { 4, NULL, &a_5 };

              content_fb_2.data = content_2.data;
              content_2.dataint = 114;
              cob_procedure_params[0] = COB_SET_DATA (f_78, b_78);
              cob_procedure_params[1] = &content_fb_2;
              cob_procedure_params[2] = &f_62;
              cob_procedure_params[3] = &f_73;
              cob_glob_ptr->cob_call_params = 4;
              cob_glob_ptr->cob_stmt_exception = 0;
              if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
                            if (unlikely(call_ATTACK.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
              {
                call_ATTACK.funcvoid = cob_resolve_cobol ("ATTACK", 0, 1);
              }
              b_2 = ((int (*)(void *, void *, void *, void *))call_ATTACK.funcint) (b_78, content_2.data, b_62, b_73);
            }

            /* Line: 402       : IF                 : movegen.cob */
            if (((int)cob_cmp_s16 (b_73, 0LL) == 0))
            {

              /* Line: 403       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_12, &f_64);

              /* Line: 404       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_8, &f_75);

              /* Line: 405       : MOVE               : movegen.cob */
              cob_move ((cob_field *)&c_10, &f_76);

              /* Line: 406       : PERFORM            : movegen.cob */
              /* PERFORM ADD-MOVE */
              frame_ptr++;
              frame_ptr->perform_through = 37;
              frame_ptr->return_address_ptr = &&l_84;
              goto l_37;
              l_84:
              frame_ptr--;
            }
          }
        }
      }
    }
  }

  /* Line: 413       : EXIT PARAGRAPH     : movegen.cob */
  goto l_34;

  /* Implicit EXIT label */
  l_34:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 33)
    goto *frame_ptr->return_address_ptr;

  /* Line: 415       : Paragraph ADD-PROMOS              : movegen.cob */
  l_35:;

  /* Line: 416       : MOVE               : movegen.cob */
  memcpy (b_77, b_75, 2);

  /* Line: 417       : COMPUTE            : movegen.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_77)));
  cob_decimal_add (d_0, dc_9);
  cob_decimal_get_field (d_0, &f_75, 0);

  /* Line: 419       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_1, &f_76);

  /* Line: 420       : PERFORM            : movegen.cob */
  /* PERFORM ADD-MOVE */
  frame_ptr++;
  frame_ptr->perform_through = 37;
  frame_ptr->return_address_ptr = &&l_85;
  goto l_37;
  l_85:
  frame_ptr--;

  /* Line: 421       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_7, &f_76);

  /* Line: 422       : PERFORM            : movegen.cob */
  /* PERFORM ADD-MOVE */
  frame_ptr++;
  frame_ptr->perform_through = 37;
  frame_ptr->return_address_ptr = &&l_86;
  goto l_37;
  l_86:
  frame_ptr--;

  /* Line: 423       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_13, &f_76);

  /* Line: 424       : PERFORM            : movegen.cob */
  /* PERFORM ADD-MOVE */
  frame_ptr++;
  frame_ptr->perform_through = 37;
  frame_ptr->return_address_ptr = &&l_87;
  goto l_37;
  l_87:
  frame_ptr--;

  /* Line: 425       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_8, &f_76);

  /* Line: 426       : PERFORM            : movegen.cob */
  /* PERFORM ADD-MOVE */
  frame_ptr++;
  frame_ptr->perform_through = 37;
  frame_ptr->return_address_ptr = &&l_88;
  goto l_37;
  l_88:
  frame_ptr--;

  /* Line: 428       : MOVE               : movegen.cob */
  memcpy (b_75, b_77, 2);

  /* Line: 429       : EXIT PARAGRAPH     : movegen.cob */
  goto l_36;

  /* Implicit EXIT label */
  l_36:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 35)
    goto *frame_ptr->return_address_ptr;

  /* Line: 431       : Paragraph ADD-MOVE                : movegen.cob */
  l_37:;

  /* Line: 432       : IF                 : movegen.cob */
  if (((int)cob_cmp_s16 (b_106, 256LL) < 0))
  {

    /* Line: 433       : ADD                : movegen.cob */
    cob_add_s16 (b_106, 1);

    /* Line: 434       : MOVE               : movegen.cob */
    memmove (b_106 + 2 + 12LL * ((cob_s64_t)(cob_get_int (COB_SET_DATA (f_107, b_106))) - 1), b_63, 2);

    /* Line: 435       : MOVE               : movegen.cob */
    memmove (b_106 + 4 + 12LL * ((cob_s64_t)(cob_get_int (COB_SET_DATA (f_107, b_106))) - 1), b_64, 2);

    /* Line: 436       : MOVE               : movegen.cob */
    memmove (b_106 + 6 + 12LL * ((cob_s64_t)(cob_get_int (COB_SET_DATA (f_107, b_106))) - 1), b_76, 2);

    /* Line: 437       : MOVE               : movegen.cob */
    memmove (b_106 + 8 + 12LL * ((cob_s64_t)(cob_get_int (COB_SET_DATA (f_107, b_106))) - 1), b_75, 2);

    /* Line: 438       : MOVE               : movegen.cob */
    cob_move ((cob_field *)&c_10, COB_SET_FLD (f0, 4, b_106 + 10 + 12LL * ((cob_s64_t)(cob_get_int (COB_SET_DATA (f_107, b_106))) - 1), &a_7));
  }

  /* Line: 440       : EXIT PARAGRAPH     : movegen.cob */
  goto l_38;

  /* Implicit EXIT label */
  l_38:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 37)
    goto *frame_ptr->return_address_ptr;

  /* Line: 442       : Paragraph INIT-OFFSETS            : movegen.cob */
  l_39:;

  /* Line: 443       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_14, COB_SET_FLD (f0, 2, b_55, &a_3));

  /* Line: 444       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_15, COB_SET_FLD (f0, 2, b_55 + 2LL * 1LL, &a_3));

  /* Line: 445       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_16, COB_SET_FLD (f0, 2, b_55 + 2LL * 2LL, &a_3));

  /* Line: 446       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_17, COB_SET_FLD (f0, 2, b_55 + 2LL * 3LL, &a_3));

  /* Line: 447       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_18, COB_SET_FLD (f0, 2, b_55 + 2LL * 4LL, &a_3));

  /* Line: 448       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_19, COB_SET_FLD (f0, 2, b_55 + 2LL * 5LL, &a_3));

  /* Line: 449       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_20, COB_SET_FLD (f0, 2, b_55 + 2LL * 6LL, &a_3));

  /* Line: 450       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_21, COB_SET_FLD (f0, 2, b_55 + 2LL * 7LL, &a_3));

  /* Line: 452       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_22, COB_SET_FLD (f0, 2, b_55 + 16, &a_3));

  /* Line: 453       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_23, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 1LL, &a_3));

  /* Line: 454       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_24, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 2LL, &a_3));

  /* Line: 455       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_25, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 3LL, &a_3));

  /* Line: 456       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_1, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 4LL, &a_3));

  /* Line: 457       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_4, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 5LL, &a_3));

  /* Line: 458       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_3, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 6LL, &a_3));

  /* Line: 459       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_5, COB_SET_FLD (f0, 2, b_55 + 16 + 2LL * 7LL, &a_3));

  /* Line: 461       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_22, COB_SET_FLD (f0, 2, b_55 + 32, &a_3));

  /* Line: 462       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_24, COB_SET_FLD (f0, 2, b_55 + 32 + 2LL * 1LL, &a_3));

  /* Line: 463       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_4, COB_SET_FLD (f0, 2, b_55 + 32 + 2LL * 2LL, &a_3));

  /* Line: 464       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_5, COB_SET_FLD (f0, 2, b_55 + 32 + 2LL * 3LL, &a_3));

  /* Line: 466       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_23, COB_SET_FLD (f0, 2, b_55 + 40, &a_3));

  /* Line: 467       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_25, COB_SET_FLD (f0, 2, b_55 + 40 + 2LL * 1LL, &a_3));

  /* Line: 468       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_1, COB_SET_FLD (f0, 2, b_55 + 40 + 2LL * 2LL, &a_3));

  /* Line: 469       : MOVE               : movegen.cob */
  cob_move ((cob_field *)&c_3, COB_SET_FLD (f0, 2, b_55 + 40 + 2LL * 3LL, &a_3));

  /* Line: 470       : EXIT PARAGRAPH     : movegen.cob */
  goto l_40;

  /* Implicit EXIT label */
  l_40:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 39)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  MOVEGEN_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize KNIGHT-OFF: init first record */
  {
    /* initialize field KNIGHT-OFF */
    cob_move ((cob_field *)&c_10, COB_SET_FLD (f0, 2, b_55, &a_3));
    /* initialize KNIGHT-OFF: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_55;
      memcpy (b_ptr +      2, b_ptr,      2);    /* KNIGHT-OFF:     2 thru 2 */
      memcpy (b_ptr +      4, b_ptr,      4);    /* KNIGHT-OFF:     3 thru 4 */
      memcpy (b_ptr +      8, b_ptr,      8);    /* KNIGHT-OFF:     5 thru 8 */
    }
  }
  /* initialize KING-OFF: init first record */
  {
    /* initialize field KING-OFF */
    cob_move ((cob_field *)&c_10, COB_SET_FLD (f0, 2, b_55 + 16, &a_3));
    /* initialize KING-OFF: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_55 + 16;
      memcpy (b_ptr +      2, b_ptr,      2);    /* KING-OFF:     2 thru 2 */
      memcpy (b_ptr +      4, b_ptr,      4);    /* KING-OFF:     3 thru 4 */
      memcpy (b_ptr +      8, b_ptr,      8);    /* KING-OFF:     5 thru 8 */
    }
  }
  /* initialize BISHOP-OFF: init first record */
  {
    /* initialize field BISHOP-OFF */
    cob_move ((cob_field *)&c_10, COB_SET_FLD (f0, 2, b_55 + 32, &a_3));
    /* initialize BISHOP-OFF: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_55 + 32;
      memcpy (b_ptr +      2, b_ptr,      2);    /* BISHOP-OFF:     2 thru 2 */
      memcpy (b_ptr +      4, b_ptr,      4);    /* BISHOP-OFF:     3 thru 4 */
    }
  }
  /* initialize ROOK-OFF: init first record */
  {
    /* initialize field ROOK-OFF */
    cob_move ((cob_field *)&c_10, COB_SET_FLD (f0, 2, b_55 + 40, &a_3));
    /* initialize ROOK-OFF: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_55 + 40;
      memcpy (b_ptr +      2, b_ptr,      2);    /* ROOK-OFF:     2 thru 2 */
      memcpy (b_ptr +      4, b_ptr,      4);    /* ROOK-OFF:     3 thru 4 */
    }
  }

  /* initialize field OFFSETS-INIT */
  cob_move ((cob_field *)&c_10, &f_60);

  /* initialize field SIDE */
  memset (b_61, 0x0, 2);

  /* initialize field OPP-SIDE */
  memset (b_62, 0x0, 2);

  /* initialize field FROM-SQ */
  memset (b_63, 0x0, 2);

  /* initialize field TO-SQ */
  memset (b_64, 0x0, 2);

  /* initialize field IDX */
  memset (b_65, 0x0, 2);

  /* initialize field P */
  memset (b_66, 0x0, 2);

  /* initialize field TGT */
  memset (b_67, 0x0, 2);

  /* initialize field PIECE-TYPE */
  memset (b_68, 0x0, 2);

  /* initialize field RANK */
  memset (b_69, 0x0, 2);

  /* initialize field I */
  memset (b_70, 0x0, 2);

  /* initialize field DIR */
  memset (b_71, 0x0, 2);

  /* initialize field CAP-ONLY */
  memset (b_72, 0x0, 2);

  /* initialize field ATTACKED */
  memset (b_73, 0x0, 2);

  /* initialize field RIGHT-QUOT */
  memset (b_74, 0x0, 2);

  /* initialize field ADD-FLAGS */
  memset (b_75, 0x0, 2);

  /* initialize field ADD-PROMO */
  memset (b_76, 0x0, 2);

  /* initialize field BASE-FLAGS */
  memset (b_77, 0x0, 2);


  /* Set Decimal Constant values */
  dc_9 = &kc_9;
  cob_decimal_init (dc_9);
  cob_decimal_set_field (dc_9, (cob_field *)&c_9);

  dc_8 = &kc_8;
  cob_decimal_init (dc_8);
  cob_decimal_set_field (dc_8, (cob_field *)&c_8);

  dc_7 = &kc_7;
  cob_decimal_init (dc_7);
  cob_decimal_set_field (dc_7, (cob_field *)&c_7);

  dc_6 = &kc_6;
  cob_decimal_init (dc_6);
  cob_decimal_set_field (dc_6, (cob_field *)&c_6);

  dc_5 = &kc_5;
  cob_decimal_init (dc_5);
  cob_decimal_set_field (dc_5, (cob_field *)&c_5);

  dc_4 = &kc_4;
  cob_decimal_init (dc_4);
  cob_decimal_set_field (dc_4, (cob_field *)&c_4);

  dc_3 = &kc_3;
  cob_decimal_init (dc_3);
  cob_decimal_set_field (dc_3, (cob_field *)&c_3);

  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  call_ATTACK.funcvoid = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_9);
  dc_9 = NULL;
  cob_decimal_clear (dc_8);
  dc_8 = NULL;
  cob_decimal_clear (dc_7);
  dc_7 = NULL;
  cob_decimal_clear (dc_6);
  dc_6 = NULL;
  cob_decimal_clear (dc_5);
  dc_5 = NULL;
  cob_decimal_clear (dc_4);
  dc_4 = NULL;
  cob_decimal_clear (dc_3);
  dc_3 = NULL;
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'MOVEGEN' */

/* Initialize module structure for MOVEGEN */
static void MOVEGEN_module_init (cob_module *module)
{
  module->module_name = "MOVEGEN";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MOVEGEN;
  module->module_cancel.funcptr = (void *(*)())MOVEGEN_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 3;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

