/* Generated by           cobc 3.2.0 */
/* Generated from         perft.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE        "perft.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 05:30:21"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        53021

/* Global variables */
#include "perft.c.h"

/* Function prototypes */

COB_EXT_EXPORT int        PERFT (cob_u8_t *, cob_u8_t *, cob_u8_t *);
static int        PERFT_ (const int, cob_u8_t *, cob_u8_t *, cob_u8_t *);
static void        PERFT_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'PERFT' */

/* ENTRY 'PERFT' */

int
PERFT (cob_u8_t *b_75, cob_u8_t *b_111, cob_u8_t *b_112)
{
  cob_u8_t *cob_parm_75 = NULL;    /* linkage for GAME-STATE */
  cob_u8_t *cob_parm_111 = NULL;    /* linkage for L-DEPTH */
  cob_u8_t *cob_parm_112 = NULL;    /* linkage for L-NODES */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
      cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
      cob_call_params = 3;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_75 = b_75;
  }
  if (cob_call_params > 1) {
    cob_parm_111 = b_111;
  }
  if (cob_call_params > 2) {
    cob_parm_112 = b_112;
  }

  return PERFT_ (0, cob_parm_75, cob_parm_111, cob_parm_112);
}

static int
PERFT_ (const int entry, cob_u8_t *b_75, cob_u8_t *b_111, 
    cob_u8_t *b_112)
{
  /* Program local variables */
  #include "perft.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  PERFT_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Set address of module parameter list */
  cob_procedure_params = cob_malloc (3U * sizeof(void *));
  module->cob_procedure_params = cob_procedure_params;

  /* Set recursive frame stack pointer */
  frame_stack = cob_malloc (63U * sizeof(struct cob_frame));
  frame_ptr = frame_stack;

  /* Allocate LOCAL storage */
  cob_local_ptr = cob_malloc (3200U);

  /* Initialize LOCAL storage */
  /* initialize field LS-MOVE */
  memset (cob_local_ptr, 0x0, 12);

  /* initialize field LS-MOVE-LIST */
  memset (cob_local_ptr + 16, 0x0, 3074);

  /* initialize field I */
  memset (cob_local_ptr + 3104, 0x0, 2);

  /* initialize field OK */
  memset (cob_local_ptr + 3120, 0x0, 2);

  /* initialize field CAP-ONLY */
  memset (cob_local_ptr + 3136, 0x0, 2);

  /* initialize field CHILD-DEPTH */
  memset (cob_local_ptr + 3152, 0x0, 2);

  /* initialize field CHILD-NODES */
  memset (cob_local_ptr + 3168, 0x0, 8);

  /* initialize field TOTAL-NODES */
  memset (cob_local_ptr + 3184, 0x0, 8);


  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_push (1, &d_0);

  /* Store last parameters for possible later lookup */
  last_b_75 = b_75;
  last_b_111 = b_111;
  last_b_112 = b_112;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 38        : Entry     PERFT                   : perft.cob */
  l_2:;

  /* Line: 38        : IF                 : perft.cob */
  if (((int)cob_cmp_s16 (b_111, 0LL) == 0))
  {

    /* Line: 39        : MOVE               : perft.cob */
    cob_move ((cob_field *)&c_1, COB_SET_DATA (f_112, b_112));

    /* Line: 40        : GOBACK             : perft.cob */
    goto exit_program;
  }

  /* Line: 43        : MOVE               : perft.cob */
  cob_move ((cob_field *)&c_2, COB_SET_DATA (f_74, cob_local_ptr + 3184));

  /* Line: 44        : MOVE               : perft.cob */
  cob_move ((cob_field *)&c_2, COB_SET_DATA (f_71, cob_local_ptr + 3136));

  /* Line: 45        : CALL               : perft.cob */
  cob_procedure_params[0] = COB_SET_DATA (f_75, b_75);
  cob_procedure_params[1] = COB_SET_DATA (f_61, cob_local_ptr + 16);
  cob_procedure_params[2] = COB_SET_DATA (f_71, cob_local_ptr + 3136);
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_MOVEGEN.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
  {
    call_MOVEGEN.funcvoid = cob_resolve_cobol ("MOVEGEN", 0, 1);
  }
  b_2 = ((int (*)(void *, void *, void *))call_MOVEGEN.funcint) (b_75, cob_local_ptr + 16, cob_local_ptr + 3136);

  /* Line: 47        : PERFORM            : perft.cob */
  cob_move ((cob_field *)&c_1, COB_SET_DATA (f_69, cob_local_ptr + 3104));
  for (;;)
  {
    /* Line: 47        : UNTIL              : perft.cob */
    if (((int)cob_cmp_s16 (cob_local_ptr + 3104, (*(short *)(cob_local_ptr + 16))) > 0))
      break;

    /* Line: 48        : MOVE               : perft.cob */
    memcpy (cob_local_ptr, cob_local_ptr + 16 + 2 + 12LL * ((cob_s64_t)((*(short *)(cob_local_ptr + 3104))) - 1), 2);

    /* Line: 49        : MOVE               : perft.cob */
    memcpy (cob_local_ptr + 2, cob_local_ptr + 16 + 4 + 12LL * ((cob_s64_t)((*(short *)(cob_local_ptr + 3104))) - 1), 2);

    /* Line: 50        : MOVE               : perft.cob */
    memcpy (cob_local_ptr + 4, cob_local_ptr + 16 + 6 + 12LL * ((cob_s64_t)((*(short *)(cob_local_ptr + 3104))) - 1), 2);

    /* Line: 51        : MOVE               : perft.cob */
    memcpy (cob_local_ptr + 6, cob_local_ptr + 16 + 8 + 12LL * ((cob_s64_t)((*(short *)(cob_local_ptr + 3104))) - 1), 2);

    /* Line: 52        : MOVE               : perft.cob */
    cob_move ((cob_field *)&c_2, COB_SET_DATA (f_60, cob_local_ptr + 8));

    /* Line: 54        : CALL               : perft.cob */
    cob_procedure_params[0] = COB_SET_DATA (f_75, b_75);
    cob_procedure_params[1] = COB_SET_DATA (f_55, cob_local_ptr);
    cob_procedure_params[2] = COB_SET_DATA (f_70, cob_local_ptr + 3120);
    cob_glob_ptr->cob_call_params = 3;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
        if (unlikely(call_MAKEMOVE.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
    {
      call_MAKEMOVE.funcvoid = cob_resolve_cobol ("MAKEMOVE", 0, 1);
    }
    b_2 = ((int (*)(void *, void *, void *))call_MAKEMOVE.funcint) (b_75, cob_local_ptr, cob_local_ptr + 3120);

    /* Line: 55        : IF                 : perft.cob */
    if (((int)cob_cmp_s16 (cob_local_ptr + 3120, 1LL) == 0))
    {

      /* Line: 56        : COMPUTE            : perft.cob */
      cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_DATA (f_111, b_111)));
      cob_decimal_sub (d_0, dc_1);
      cob_decimal_get_field (d_0, COB_SET_DATA (f_72, cob_local_ptr + 3152), 0);

      /* Line: 57        : CALL               : perft.cob */
      cob_procedure_params[0] = COB_SET_DATA (f_75, b_75);
      cob_procedure_params[1] = COB_SET_DATA (f_72, cob_local_ptr + 3152);
      cob_procedure_params[2] = COB_SET_DATA (f_73, cob_local_ptr + 3168);
      cob_glob_ptr->cob_call_params = 3;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_PERFT.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_PERFT.funcvoid = cob_resolve_cobol ("PERFT", 0, 1);
      }
      b_2 = ((int (*)(void *, void *, void *))call_PERFT.funcint) (b_75, cob_local_ptr + 3152, cob_local_ptr + 3168);

      /* Line: 58        : ADD                : perft.cob */
      cob_add (COB_SET_DATA (f_74, cob_local_ptr + 3184), COB_SET_DATA (f_73, cob_local_ptr + 3168), 0);

      /* Line: 59        : CALL               : perft.cob */
      cob_procedure_params[0] = COB_SET_DATA (f_75, b_75);
      cob_procedure_params[1] = COB_SET_DATA (f_55, cob_local_ptr);
      cob_glob_ptr->cob_call_params = 2;
      cob_glob_ptr->cob_stmt_exception = 0;
      if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
            if (unlikely(call_UNMAKEMOVE.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel == 1))
      {
        call_UNMAKEMOVE.funcvoid = cob_resolve_cobol ("UNMAKEMOVE", 0, 1);
      }
      b_2 = ((int (*)(void *, void *))call_UNMAKEMOVE.funcint) (b_75, cob_local_ptr);
    }
    /* Line: 47        : VARYING            : perft.cob */
    cob_add_s16 (cob_local_ptr + 3104, 1);
  }

  /* Line: 63        : MOVE               : perft.cob */
  memmove (b_112, cob_local_ptr + 3184, 8);

  /* Line: 64        : GOBACK             : perft.cob */
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Deallocate LOCAL storage */
  if (cob_local_ptr) {
      cob_free (cob_local_ptr);
      cob_local_ptr = NULL;
  }

  /* Free decimal structures */
  cob_decimal_pop (1, d_0);

  /* Free frame stack / call parameters */
  cob_free (frame_stack);
  cob_free (cob_procedure_params);

  /* Pop module stack */
  cob_module_leave (module);

  /* Free for recursive module */
  cob_module_free (&module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;


  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  call_UNMAKEMOVE.funcvoid = NULL;
  call_PERFT.funcvoid = NULL;
  call_MAKEMOVE.funcvoid = NULL;
  call_MOVEGEN.funcvoid = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'PERFT' */

/* Initialize module structure for PERFT */
static void PERFT_module_init (cob_module *module)
{
  module->module_name = "PERFT";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())PERFT;
  module->module_cancel.funcptr = (void *(*)())PERFT_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 3;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

