/* Generated by           cobc 3.2.0 */
/* Generated from         perft.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'PERFT' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer for recursive */
cob_module        *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */
static unsigned char    *b_97 = NULL;  /* MOVE-REC */
static unsigned char    *b_103 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_75;
static unsigned char    *last_b_111;
static unsigned char    *last_b_112;

/* Call pointers */
static cob_call_union    call_MOVEGEN;
static cob_call_union    call_MAKEMOVE;
static cob_call_union    call_PERFT;
static cob_call_union    call_UNMAKEMOVE;

/* LOCAL storage pointer */
unsigned char        *cob_local_ptr = NULL;

/* Call parameters */
cob_field        **cob_procedure_params;

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    *frame_stack;


/* Data storage */
static int    b_2;    /* RETURN-CODE */

/* End of local data storage */


/* Fields for recursive routine */
static cob_field f_55    = {12, NULL, &a_4};    /* LS-MOVE */
static cob_field f_60    = {4, NULL, &a_5};    /* M-SCORE */
static cob_field f_61    = {3074, NULL, &a_4};    /* LS-MOVE-LIST */
static cob_field f_69    = {2, NULL, &a_3};    /* I */
static cob_field f_70    = {2, NULL, &a_3};    /* OK */
static cob_field f_71    = {2, NULL, &a_3};    /* CAP-ONLY */
static cob_field f_72    = {2, NULL, &a_3};    /* CHILD-DEPTH */
static cob_field f_73    = {8, NULL, &a_2};    /* CHILD-NODES */
static cob_field f_74    = {8, NULL, &a_2};    /* TOTAL-NODES */
static cob_field f_75    = {5912, NULL, &a_4};    /* GAME-STATE */
static cob_field f_111    = {2, NULL, &a_3};    /* L-DEPTH */
static cob_field f_112    = {8, NULL, &a_2};    /* L-NODES */

/* End of fields */

