/* Generated by           cobc 3.2.0 */
/* Generated from         search.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'QUIESCE' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer for recursive */
cob_module        *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_459 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_460 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_461 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_462 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_463 = NULL;  /* XML-NTEXT */
static unsigned char    *b_464 = NULL;  /* XML-TEXT */
static unsigned char    *b_573 = NULL;  /* MOVE-REC */
static unsigned char    *b_579 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_551;
static unsigned char    *last_b_587;
static unsigned char    *last_b_588;
static unsigned char    *last_b_589;
static unsigned char    *last_b_618;

/* Call pointers */
static cob_call_union    call_TIMEUTIL;
static cob_call_union    call_EVAL;
static cob_call_union    call_MOVEGEN;
static cob_call_union    call_MAKEMOVE;
static cob_call_union    call_QUIESCE;
static cob_call_union    call_UNMAKEMOVE;

/* Local cob_field items */
cob_field        f0;


/* LOCAL storage pointer */
unsigned char        *cob_local_ptr = NULL;

/* Call parameters */
cob_field        **cob_procedure_params;

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    *frame_stack;


/* Data storage */
static int    b_452;    /* RETURN-CODE */

/* End of local data storage */


/* Fields for recursive routine */
static cob_field f_505    = {12, NULL, &a_11};    /* LS-MOVE */
static cob_field f_510    = {4, NULL, &a_8};    /* M-SCORE */
static cob_field f_511    = {3074, NULL, &a_11};    /* LS-LIST */
static cob_field f_519    = {2, NULL, &a_6};    /* I */
static cob_field f_520    = {2, NULL, &a_6};    /* OK */
static cob_field f_521    = {2, NULL, &a_6};    /* CAP-ONLY */
static cob_field f_522    = {4, NULL, &a_8};    /* STANDPAT */
static cob_field f_523    = {4, NULL, &a_8};    /* Q */
static cob_field f_535    = {2, NULL, &a_6};    /* S-FROM-IDX */
static cob_field f_536    = {2, NULL, &a_6};    /* S-TO-IDX */
static cob_field f_539    = {2, NULL, &a_6};    /* S-ATT-TYPE */
static cob_field f_540    = {2, NULL, &a_6};    /* S-VIC-TYPE */
static cob_field f_541    = {4, NULL, &a_8};    /* S-ATT-VALUE */
static cob_field f_542    = {4, NULL, &a_8};    /* S-VIC-VALUE */
static cob_field f_543    = {4, NULL, &a_8};    /* S-PROMO-VALUE */
static cob_field f_544    = {4, NULL, &a_8};    /* S-MOVE-SCORE */
static cob_field f_545    = {2, NULL, &a_6};    /* S-EP */
static cob_field f_546    = {8, NULL, &a_5};    /* NOW-CS */
static cob_field f_547    = {8, NULL, &a_5};    /* ELAPSED */
static cob_field f_548    = {4, NULL, &a_8};    /* CHILD-ALPHA */
static cob_field f_549    = {4, NULL, &a_8};    /* CHILD-BETA */
static cob_field f_550    = {4, NULL, &a_8};    /* CHILD-SCORE */
static cob_field f_551    = {5912, NULL, &a_11};    /* GAME-STATE */
static cob_field f_587    = {4, NULL, &a_8};    /* L-ALPHA */
static cob_field f_588    = {4, NULL, &a_8};    /* L-BETA */
static cob_field f_589    = {25235488, NULL, &a_11};    /* L-SS */
static cob_field f_591    = {2, NULL, &a_6};    /* SS-STOP */
static cob_field f_592    = {8, NULL, &a_5};    /* SS-START-CS */
static cob_field f_593    = {8, NULL, &a_5};    /* SS-TIME-LIMIT-CS */
static cob_field f_594    = {4, NULL, &a_8};    /* SS-TIME-CHECK */
static cob_field f_618    = {4, NULL, &a_8};    /* L-OUT */

/* End of fields */

