/* Generated by           cobc 3.2.0 */
/* Generated from         search.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */


/* Module reference count */
static unsigned int        cob_reference_count = 0;

/* Module path */
static const char        *cob_module_path = NULL;

/* Number of call parameters */
static int        cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
    {'Z', 2},
    {'9', 1},
    {'\0', 1}
};
static const cob_pic_symbol p_2[] = {
    {'Z', 17},
    {'9', 1},
    {'\0', 1}
};
static const cob_pic_symbol p_3[] = {
    {'-', 1},
    {'Z', 4},
    {'9', 1},
    {'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =    {0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =    {0x10,   6,   0, 0x1000, NULL};
static const cob_field_attr a_3 =    {0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_4 =    {0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_5 =    {0x11,  18,   0, 0x0041, NULL};
static const cob_field_attr a_6 =    {0x11,   4,   0, 0x0041, NULL};
static const cob_field_attr a_7 =    {0x10,   4,   0, 0x1000, NULL};
static const cob_field_attr a_8 =    {0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_9 =    {0x10,   1,   0, 0x0007, NULL};
static const cob_field_attr a_10 =    {0x10,   5,   0, 0x1000, NULL};
static const cob_field_attr a_11 =    {0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_12 =    {0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_13 =    {0x24,   3,   0, 0x0000, p_1};
static const cob_field_attr a_14 =    {0x24,  18,   0, 0x0000, p_2};
static const cob_field_attr a_15 =    {0x24,   5,   0, 0x0001, p_3};
static const cob_field_attr a_16 =    {0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_17 =    {0x10,   7,   0, 0x1000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1    = {1, (cob_u8_ptr)"1", &a_1};
static const cob_field c_2    = {1, (cob_u8_ptr)"2", &a_1};
static const cob_field c_3    = {1, (cob_u8_ptr)"4", &a_1};
static const cob_field c_4    = {1, (cob_u8_ptr)"6", &a_1};
static const cob_field c_5    = {6, (cob_u8_ptr)"100000", &a_2};
static const cob_field c_6    = {2, (cob_u8_ptr)"10", &a_3};
static const cob_field c_7    = {1, (cob_u8_ptr)"3", &a_1};
static const cob_field c_8    = {1, (cob_u8_ptr)"8", &a_1};
static const cob_field c_9    = {3, (cob_u8_ptr)"128", &a_4};
static const cob_field c_10    = {3, (cob_u8_ptr)"950", &a_4};
static const cob_field c_11    = {1, (cob_u8_ptr)"0", &a_1};
static const cob_field c_12    = {4, (cob_u8_ptr)"2048", &a_7};
static const cob_field c_13    = {2, (cob_u8_ptr)"-1", &a_9};
static const cob_field c_14    = {2, (cob_u8_ptr)"50", &a_3};
static const cob_field c_15    = {5, (cob_u8_ptr)"30000", &a_10};
static const cob_field c_16    = {11, (cob_u8_ptr)"info depth ", &a_16};
static const cob_field c_17    = {7, (cob_u8_ptr)" nodes ", &a_16};
static const cob_field c_18    = {10, (cob_u8_ptr)" score cp ", &a_16};
static const cob_field c_19    = {4, (cob_u8_ptr)" pv ", &a_16};
static const cob_field c_20    = {3, (cob_u8_ptr)"900", &a_4};
static const cob_field c_21    = {3, (cob_u8_ptr)"500", &a_4};
static const cob_field c_22    = {3, (cob_u8_ptr)"330", &a_4};
static const cob_field c_23    = {3, (cob_u8_ptr)"320", &a_4};
static const cob_field c_24    = {3, (cob_u8_ptr)"100", &a_4};
static const cob_field c_25    = {5, (cob_u8_ptr)"20000", &a_10};
static const cob_field c_26    = {7, (cob_u8_ptr)"1048576", &a_17};
static const cob_field c_27    = {2, (cob_u8_ptr)"12", &a_3};
static const cob_field c_28    = {2, (cob_u8_ptr)"20", &a_3};
static const cob_field c_29    = {2, (cob_u8_ptr)"16", &a_3};

static cob_field cob_all_zero    = {1, (cob_u8_ptr)"0", &cob_all_attr};


static COB_INLINE COB_A_INLINE int
cob_cmp_s16 (const void *p, const cob_s64_t n)
{
    short    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 2);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE int
cob_cmp_s32 (const void *p, const cob_s64_t n)
{
    int    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 4);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE int
cob_cmp_s64 (const void *p, const cob_s64_t n)
{
    cob_s64_t    val;
    void        *x;
    x = &val;
    optim_memcpy (x, p, 8);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_add_s16 (void *p, const int val)
{
    void    *x;
    short    n;
    x = &n;
    optim_memcpy (x, p, 2);
    n += val;
    optim_memcpy (p, x, 2);
}


static COB_INLINE COB_A_INLINE void
cob_add_s32 (void *p, const int val)
{
    void    *x;
    int    n;
    x = &n;
    optim_memcpy (x, p, 4);
    n += val;
    optim_memcpy (p, x, 4);
}


static COB_INLINE COB_A_INLINE void
cob_add_s64 (void *p, const int val)
{
    void        *x;
    cob_s64_t    n;
    x = &n;
    optim_memcpy (x, p, 8);
    n += val;
    optim_memcpy (p, x, 8);
}


static COB_INLINE COB_A_INLINE void
cob_sub_s32 (void *p, const int val)
{
    void    *x;
    int    n;
    x = &n;
    optim_memcpy (x, p, 4);
    n -= val;
    optim_memcpy (p, x, 4);
}


static COB_INLINE COB_A_INLINE void
cob_sub_s64 (void *p, const int val)
{
    void        *x;
    cob_s64_t    n;
    x = &n;
    optim_memcpy (x, p, 8);
    n -= val;
    optim_memcpy (p, x, 8);
}


/* Decimal constants */
static    cob_decimal    kc_1;
static    cob_decimal    *dc_1 = NULL;
static    cob_decimal    kc_2;
static    cob_decimal    *dc_2 = NULL;
static    cob_decimal    kc_3;
static    cob_decimal    *dc_3 = NULL;
static    cob_decimal    kc_4;
static    cob_decimal    *dc_4 = NULL;
static    cob_decimal    kc_5;
static    cob_decimal    *dc_5 = NULL;
static    cob_decimal    kc_6;
static    cob_decimal    *dc_6 = NULL;
static    cob_decimal    kc_7;
static    cob_decimal    *dc_7 = NULL;
static    cob_decimal    kc_8;
static    cob_decimal    *dc_8 = NULL;
static    cob_decimal    kc_9;
static    cob_decimal    *dc_9 = NULL;
static    cob_decimal    kc_10;
static    cob_decimal    *dc_10 = NULL;

