/* Generated by           cobc 3.2.0 */
/* Generated from         search.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'ALPHABETA' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer for recursive */
cob_module        *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;

/* EXTERNAL items */
static unsigned char    *b_274 = NULL;  /* HASH-STATE */


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_225 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_226 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_227 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_228 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_229 = NULL;  /* XML-NTEXT */
static unsigned char    *b_230 = NULL;  /* XML-TEXT */
static unsigned char    *b_402 = NULL;  /* MOVE-REC */
static unsigned char    *b_408 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_380;
static unsigned char    *last_b_416;
static unsigned char    *last_b_417;
static unsigned char    *last_b_418;
static unsigned char    *last_b_419;
static unsigned char    *last_b_448;
static unsigned char    *last_b_449;

/* Call pointers */
static cob_call_union    call_TIMEUTIL;
static cob_call_union    call_ATTACK;
static cob_call_union    call_QUIESCE;
static cob_call_union    call_ALPHABETA;
static cob_call_union    call_MOVEGEN;
static cob_call_union    call_MAKEMOVE;
static cob_call_union    call_UNMAKEMOVE;

/* Local cob_field items */
cob_field        f0;


/* LOCAL storage pointer */
unsigned char        *cob_local_ptr = NULL;

/* Call parameters */
cob_field        **cob_procedure_params;

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    *frame_stack;


/* Data storage */
static int    b_218;    /* RETURN-CODE */

/* End of local data storage */


/* Fields for recursive routine */
static cob_field f_279    = {8, NULL, &a_5};    /* HS-SIDEKEY */
static cob_field f_282    = {12, NULL, &a_11};    /* LS-MOVE */
static cob_field f_287    = {4, NULL, &a_8};    /* M-SCORE */
static cob_field f_288    = {3074, NULL, &a_11};    /* LS-LIST */
static cob_field f_298    = {4, NULL, &a_8};    /* BEST-SCORE */
static cob_field f_299    = {2, NULL, &a_6};    /* BM-FROM */
static cob_field f_300    = {2, NULL, &a_6};    /* BM-TO */
static cob_field f_301    = {2, NULL, &a_6};    /* BM-PROMO */
static cob_field f_302    = {2, NULL, &a_6};    /* BM-FLAGS */
static cob_field f_303    = {4, NULL, &a_8};    /* TT-INDEX */
static cob_field f_304    = {2, NULL, &a_6};    /* TT-MFROM */
static cob_field f_305    = {2, NULL, &a_6};    /* TT-MTO */
static cob_field f_306    = {2, NULL, &a_6};    /* TT-MPROMO */
static cob_field f_307    = {2, NULL, &a_6};    /* TT-MFLAGS */
static cob_field f_308    = {4, NULL, &a_8};    /* TT-SCORE */
static cob_field f_311    = {2, NULL, &a_6};    /* STORE-FLAG */
static cob_field f_313    = {2, NULL, &a_6};    /* I */
static cob_field f_314    = {2, NULL, &a_6};    /* OK */
static cob_field f_315    = {2, NULL, &a_6};    /* CAP-ONLY */
static cob_field f_317    = {4, NULL, &a_8};    /* Q */
static cob_field f_318    = {2, NULL, &a_6};    /* IS-CAP */
static cob_field f_319    = {2, NULL, &a_6};    /* LEGAL-COUNT */
static cob_field f_321    = {2, NULL, &a_6};    /* REDUCE */
static cob_field f_322    = {2, NULL, &a_6};    /* RED-DEPTH */
static cob_field f_323    = {2, NULL, &a_6};    /* IS-PROMO */
static cob_field f_324    = {2, NULL, &a_6};    /* IS-CASTLE */
static cob_field f_325    = {2, NULL, &a_6};    /* IS-TT */
static cob_field f_326    = {2, NULL, &a_6};    /* LMP-LIMIT */
static cob_field f_327    = {2, NULL, &a_6};    /* LMP-SKIP */
static cob_field f_328    = {4, NULL, &a_8};    /* MATE-LOW */
static cob_field f_329    = {4, NULL, &a_8};    /* MATE-HIGH */
static cob_field f_339    = {2, NULL, &a_6};    /* PLY-IX */
static cob_field f_340    = {4, NULL, &a_8};    /* HIST-IX */
static cob_field f_341    = {4, NULL, &a_8};    /* UPDATE-SCORE */
static cob_field f_344    = {2, NULL, &a_6};    /* S-FROM-IDX */
static cob_field f_345    = {2, NULL, &a_6};    /* S-TO-IDX */
static cob_field f_348    = {2, NULL, &a_6};    /* S-ATT-TYPE */
static cob_field f_349    = {2, NULL, &a_6};    /* S-VIC-TYPE */
static cob_field f_350    = {4, NULL, &a_8};    /* S-ATT-VALUE */
static cob_field f_351    = {4, NULL, &a_8};    /* S-VIC-VALUE */
static cob_field f_352    = {4, NULL, &a_8};    /* S-PROMO-VALUE */
static cob_field f_353    = {4, NULL, &a_8};    /* S-MOVE-SCORE */
static cob_field f_354    = {2, NULL, &a_6};    /* S-CAP */
static cob_field f_355    = {2, NULL, &a_6};    /* S-EP */
static cob_field f_357    = {2, NULL, &a_6};    /* OPP-SIDE */
static cob_field f_358    = {2, NULL, &a_6};    /* KING-SQ */
static cob_field f_359    = {2, NULL, &a_6};    /* IN-CHECK */
static cob_field f_360    = {8, NULL, &a_5};    /* NOW-CS */
static cob_field f_361    = {8, NULL, &a_5};    /* ELAPSED */
static cob_field f_362    = {2, NULL, &a_6};    /* CHILD-DEPTH */
static cob_field f_363    = {4, NULL, &a_8};    /* CHILD-ALPHA */
static cob_field f_364    = {4, NULL, &a_8};    /* CHILD-BETA */
static cob_field f_365    = {4, NULL, &a_8};    /* CHILD-SCORE */
static cob_field f_366    = {2, NULL, &a_6};    /* CHILD-NMP */
static cob_field f_371    = {8, NULL, &a_5};    /* WORK-KEY */
static cob_field f_372    = {2, NULL, &a_6};    /* EP-FILE */
static cob_field f_373    = {2, NULL, &a_6};    /* EP-IX */
static cob_field f_374    = {2, NULL, &a_6};    /* HAS-NPM */
static cob_field f_375    = {2, NULL, &a_6};    /* SCAN-I */
static cob_field f_378    = {2, NULL, &a_6};    /* REP-START */
static cob_field f_379    = {2, NULL, &a_6};    /* REP-HITS */
static cob_field f_380    = {5912, NULL, &a_11};    /* GAME-STATE */
static cob_field f_383    = {2, NULL, &a_6};    /* GS-SIDE-TO-MOVE */
static cob_field f_385    = {2, NULL, &a_6};    /* GS-EP-SQ */
static cob_field f_386    = {2, NULL, &a_6};    /* GS-HALFMOVE */
static cob_field f_390    = {2, NULL, &a_6};    /* GS-PLY */
static cob_field f_391    = {8, NULL, &a_5};    /* GS-KEY */
static cob_field f_417    = {4, NULL, &a_8};    /* L-ALPHA */
static cob_field f_418    = {4, NULL, &a_8};    /* L-BETA */
static cob_field f_419    = {25235488, NULL, &a_11};    /* L-SS */
static cob_field f_421    = {2, NULL, &a_6};    /* SS-STOP */
static cob_field f_422    = {8, NULL, &a_5};    /* SS-START-CS */
static cob_field f_423    = {8, NULL, &a_5};    /* SS-TIME-LIMIT-CS */
static cob_field f_424    = {4, NULL, &a_8};    /* SS-TIME-CHECK */
static cob_field f_449    = {4, NULL, &a_8};    /* L-OUT */

/* End of fields */

