/* Generated by           cobc 3.2.0 */
/* Generated from         search.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'SEARCH' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;

/* EXTERNAL items */
static unsigned char    *b_58 = NULL;  /* HASH-STATE */


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */
static unsigned char    *b_192 = NULL;  /* MOVE-REC */
static unsigned char    *b_198 = NULL;  /* MOVE-LIST */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_170;
static unsigned char    *last_b_206;
static unsigned char    *last_b_207;
static unsigned char    *last_b_208;
static unsigned char    *last_b_214;
static unsigned char    *last_b_215;

/* Call pointers */
static cob_call_union    call_TIMEUTIL;
static cob_call_union    call_MOVE2UCI;
static cob_call_union    call_MOVEGEN;
static cob_call_union    call_MAKEMOVE;
static cob_call_union    call_ALPHABETA;
static cob_call_union    call_UNMAKEMOVE;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[7];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_66[25235488] __attribute__((aligned));    /* SS */
static cob_u8_t    b_95[2] __attribute__((aligned));    /* DEPTH */
static cob_u8_t    b_96[2] __attribute__((aligned));    /* I */
static cob_u8_t    b_97[4] __attribute__((aligned));    /* TT-I */
static cob_u8_t    b_98[2] __attribute__((aligned));    /* OK */
static cob_u8_t    b_99[2] __attribute__((aligned));    /* CAP-ONLY */
static cob_u8_t    b_100[4] __attribute__((aligned));    /* ALPHA */
static cob_u8_t    b_101[4] __attribute__((aligned));    /* BETA */
static cob_u8_t    b_102[4] __attribute__((aligned));    /* SCORE */
static cob_u8_t    b_103[4] __attribute__((aligned));    /* CHILD-SCORE */
static cob_u8_t    b_104[4] __attribute__((aligned));    /* BEST-SCORE */
static cob_u8_t    b_105[4] __attribute__((aligned));    /* LAST-BEST-SCORE */
static cob_u8_t    b_106[2] __attribute__((aligned));    /* CALL-DEPTH */
static cob_u8_t    b_107[4] __attribute__((aligned));    /* CALL-ALPHA */
static cob_u8_t    b_108[4] __attribute__((aligned));    /* CALL-BETA */
static cob_u8_t    b_109[2] __attribute__((aligned));    /* NMP-ROOT */
static cob_u8_t    b_110[4] __attribute__((aligned));    /* ASP-WINDOW */
static cob_u8_t    b_111[4] __attribute__((aligned));    /* ASP-ALPHA */
static cob_u8_t    b_112[4] __attribute__((aligned));    /* ASP-BETA */
static cob_u8_t    b_113[2] __attribute__((aligned));    /* PASS */
static cob_u8_t    b_114[4] __attribute__((aligned));    /* Q */
static cob_u8_t    b_115[2] __attribute__((aligned));    /* IS-CAP */
static cob_u8_t    b_116[2] __attribute__((aligned));    /* ROOT-LEGAL-COUNT */
static cob_u8_t    b_117[12] __attribute__((aligned));    /* BESTMOVE-TMP */
static cob_u8_t    b_123[12] __attribute__((aligned));    /* ROOT-MOVE */
static cob_u8_t    b_129[3074] __attribute__((aligned));    /* ROOT-LIST */
static cob_u8_t    b_137[8] __attribute__((aligned));    /* PV-MOVE */
static cob_u8_t    b_142[2] __attribute__((aligned));    /* J */
static cob_u8_t    b_143[2] __attribute__((aligned));    /* BEST-IX */
static cob_u8_t    b_144[4] __attribute__((aligned));    /* BEST-MV-SCORE */
static cob_u8_t    b_145[12] __attribute__((aligned));    /* SWAP-TMP */
static cob_u8_t    b_151[2] __attribute__((aligned));    /* S-FROM-SQ */
static cob_u8_t    b_152[2] __attribute__((aligned));    /* S-TO-SQ */
static cob_u8_t    b_153[2] __attribute__((aligned));    /* S-FROM-IDX */
static cob_u8_t    b_154[2] __attribute__((aligned));    /* S-TO-IDX */
static cob_u8_t    b_155[2] __attribute__((aligned));    /* S-ATT */
static cob_u8_t    b_156[2] __attribute__((aligned));    /* S-VIC */
static cob_u8_t    b_157[2] __attribute__((aligned));    /* S-ATT-TYPE */
static cob_u8_t    b_158[2] __attribute__((aligned));    /* S-VIC-TYPE */
static cob_u8_t    b_159[4] __attribute__((aligned));    /* S-ATT-VALUE */
static cob_u8_t    b_160[4] __attribute__((aligned));    /* S-VIC-VALUE */
static cob_u8_t    b_161[4] __attribute__((aligned));    /* S-PROMO-VALUE */
static cob_u8_t    b_162[4] __attribute__((aligned));    /* S-MOVE-SCORE */
static cob_u8_t    b_163[2] __attribute__((aligned));    /* S-CAP */
static cob_u8_t    b_164[2] __attribute__((aligned));    /* S-EP */
static cob_u8_t    b_165[2] __attribute__((aligned));    /* S-CASTLE */
static cob_u8_t    b_166[8] __attribute__((aligned));    /* UCI-BUF */
static cob_u8_t    b_167[3] __attribute__((aligned));    /* DEPTH-DISP */
static cob_u8_t    b_168[18] __attribute__((aligned));    /* NODES-DISP */
static cob_u8_t    b_169[6] __attribute__((aligned));    /* SCORE-DISP */

/* End of local data storage */


/* Fields (local) */
static cob_field f_66    = {25235488, b_66, &a_11};    /* SS */
static cob_field f_67    = {8, b_66, &a_5};    /* SS-NODES */
static cob_field f_68    = {2, b_66 + 8, &a_6};    /* SS-STOP */
static cob_field f_69    = {8, b_66 + 10, &a_5};    /* SS-START-CS */
static cob_field f_71    = {4, b_66 + 26, &a_8};    /* SS-TIME-CHECK */
static cob_field f_72    = {2, b_66 + 30, &a_6};    /* SS-TT-INIT */
static cob_field f_95    = {2, b_95, &a_6};    /* DEPTH */
static cob_field f_96    = {2, b_96, &a_6};    /* I */
static cob_field f_97    = {4, b_97, &a_8};    /* TT-I */
static cob_field f_98    = {2, b_98, &a_6};    /* OK */
static cob_field f_99    = {2, b_99, &a_6};    /* CAP-ONLY */
static cob_field f_100    = {4, b_100, &a_8};    /* ALPHA */
static cob_field f_101    = {4, b_101, &a_8};    /* BETA */
static cob_field f_102    = {4, b_102, &a_8};    /* SCORE */
static cob_field f_103    = {4, b_103, &a_8};    /* CHILD-SCORE */
static cob_field f_104    = {4, b_104, &a_8};    /* BEST-SCORE */
static cob_field f_105    = {4, b_105, &a_8};    /* LAST-BEST-SCORE */
static cob_field f_106    = {2, b_106, &a_6};    /* CALL-DEPTH */
static cob_field f_107    = {4, b_107, &a_8};    /* CALL-ALPHA */
static cob_field f_108    = {4, b_108, &a_8};    /* CALL-BETA */
static cob_field f_109    = {2, b_109, &a_6};    /* NMP-ROOT */
static cob_field f_110    = {4, b_110, &a_8};    /* ASP-WINDOW */
static cob_field f_111    = {4, b_111, &a_8};    /* ASP-ALPHA */
static cob_field f_112    = {4, b_112, &a_8};    /* ASP-BETA */
static cob_field f_114    = {4, b_114, &a_8};    /* Q */
static cob_field f_116    = {2, b_116, &a_6};    /* ROOT-LEGAL-COUNT */
static cob_field f_118    = {2, b_117, &a_6};    /* BM-FROM */
static cob_field f_119    = {2, b_117 + 2, &a_6};    /* BM-TO */
static cob_field f_120    = {2, b_117 + 4, &a_6};    /* BM-PROMO */
static cob_field f_121    = {2, b_117 + 6, &a_6};    /* BM-FLAGS */
static cob_field f_122    = {4, b_117 + 8, &a_8};    /* BM-SCORE */
static cob_field f_123    = {12, b_123, &a_11};    /* ROOT-MOVE */
static cob_field f_128    = {4, b_123 + 8, &a_8};    /* RM-SCORE */
static cob_field f_129    = {3074, b_129, &a_11};    /* ROOT-LIST */
static cob_field f_153    = {2, b_153, &a_6};    /* S-FROM-IDX */
static cob_field f_154    = {2, b_154, &a_6};    /* S-TO-IDX */
static cob_field f_157    = {2, b_157, &a_6};    /* S-ATT-TYPE */
static cob_field f_158    = {2, b_158, &a_6};    /* S-VIC-TYPE */
static cob_field f_159    = {4, b_159, &a_8};    /* S-ATT-VALUE */
static cob_field f_160    = {4, b_160, &a_8};    /* S-VIC-VALUE */
static cob_field f_161    = {4, b_161, &a_8};    /* S-PROMO-VALUE */
static cob_field f_162    = {4, b_162, &a_8};    /* S-MOVE-SCORE */
static cob_field f_163    = {2, b_163, &a_6};    /* S-CAP */
static cob_field f_164    = {2, b_164, &a_6};    /* S-EP */
static cob_field f_165    = {2, b_165, &a_6};    /* S-CASTLE */
static cob_field f_166    = {8, b_166, &a_12};    /* UCI-BUF */
static cob_field f_167    = {3, b_167, &a_13};    /* DEPTH-DISP */
static cob_field f_168    = {18, b_168, &a_14};    /* NODES-DISP */
static cob_field f_169    = {6, b_169, &a_15};    /* SCORE-DISP */
static cob_field f_170    = {5912, NULL, &a_11};    /* GAME-STATE */
static cob_field f_206    = {2, NULL, &a_6};    /* L-MAX-DEPTH */
static cob_field f_208    = {12, NULL, &a_11};    /* L-BESTMOVE */
static cob_field f_213    = {4, NULL, &a_8};    /* M-SCORE */
static cob_field f_214    = {4, NULL, &a_8};    /* L-OUT-SCORE */

/* End of fields */

