/* Generated by           cobc 3.2.0 */
/* Generated from         time.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */


/* Module path */
static const char        *cob_module_path = NULL;

/* Number of call parameters */
static int        cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =    {0x10,   7,   0, 0x1000, NULL};
static const cob_field_attr a_2 =    {0x10,   6,   0, 0x1000, NULL};
static const cob_field_attr a_3 =    {0x10,   4,   0, 0x1000, NULL};
static const cob_field_attr a_4 =    {0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_5 =    {0x10,   8,   0, 0x0000, NULL};
static const cob_field_attr a_6 =    {0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_7 =    {0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_8 =    {0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_9 =    {0x11,  18,   0, 0x0041, NULL};
static const cob_field_attr a_10 =    {0x10,   1,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1    = {7, (cob_u8_ptr)"8640000", &a_1};
static const cob_field c_2    = {6, (cob_u8_ptr)"360000", &a_2};
static const cob_field c_3    = {4, (cob_u8_ptr)"6000", &a_3};
static const cob_field c_4    = {3, (cob_u8_ptr)"100", &a_4};
static const cob_field c_5    = {1, (cob_u8_ptr)"0", &a_10};


/* Decimal constants */
static    cob_decimal    kc_1;
static    cob_decimal    *dc_1 = NULL;
static    cob_decimal    kc_2;
static    cob_decimal    *dc_2 = NULL;
static    cob_decimal    kc_3;
static    cob_decimal    *dc_3 = NULL;
static    cob_decimal    kc_4;
static    cob_decimal    *dc_4 = NULL;

