/* Generated by           cobc 3.2.0 */
/* Generated from         time.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'TIMEUTIL' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_27;

/* Local cob_field items */
cob_field        f0;


/* Call parameters */
cob_field        *cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_17[8] __attribute__((aligned));    /* WS-DATE */
static cob_u8_t    b_18[8] __attribute__((aligned));    /* WS-TIME-X */
static cob_u8_t    b_19[8] __attribute__((aligned));    /* CACHED-DATE */
static cob_u8_t    b_20[4] __attribute__((aligned));    /* CACHED-DAYS */
static cob_u8_t    b_21[2] __attribute__((aligned));    /* WS-HH */
static cob_u8_t    b_22[2] __attribute__((aligned));    /* WS-MM */
static cob_u8_t    b_23[2] __attribute__((aligned));    /* WS-SS */
static cob_u8_t    b_24[2] __attribute__((aligned));    /* WS-CC */
static cob_u8_t    b_25[4] __attribute__((aligned));    /* WS-DAYS */
static cob_u8_t    b_26[8] __attribute__((aligned));    /* WS-CS */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17    = {8, b_17, &a_5};    /* WS-DATE */
static cob_field f_18    = {8, b_18, &a_6};    /* WS-TIME-X */
static cob_field f_20    = {4, b_20, &a_8};    /* CACHED-DAYS */
static cob_field f_21    = {2, b_21, &a_7};    /* WS-HH */
static cob_field f_22    = {2, b_22, &a_7};    /* WS-MM */
static cob_field f_23    = {2, b_23, &a_7};    /* WS-SS */
static cob_field f_24    = {2, b_24, &a_7};    /* WS-CC */
static cob_field f_26    = {8, b_26, &a_9};    /* WS-CS */

/* End of fields */

