/* Generated by           cobc 3.2.0 */
/* Generated from         time.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE        "time.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 05:30:21"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        53021

/* Global variables */
#include "time.c.h"

/* Function prototypes */

COB_EXT_EXPORT int        TIMEUTIL (cob_u8_t *);
static int        TIMEUTIL_ (const int, cob_u8_t *);
static void        TIMEUTIL_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'TIMEUTIL' */

/* ENTRY 'TIMEUTIL' */

int
TIMEUTIL (cob_u8_t *b_27)
{
  cob_u8_t *cob_parm_27 = NULL;    /* linkage for L-CS */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
      cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
      cob_call_params = 1;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_27 = b_27;
  }

  return TIMEUTIL_ (0, cob_parm_27);
}

static int
TIMEUTIL_ (const int entry, cob_u8_t *b_27)
{
  /* Program local variables */
  #include "time.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_27 = b_27;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 25        : Entry     TIMEUTIL                : time.cob */
  l_2:;

  /* Line: 25        : ACCEPT             : time.cob */
  cob_accept_date_yyyymmdd (&f_17);

  /* Line: 26        : ACCEPT             : time.cob */
  cob_accept_time (&f_18);

  /* Line: 28        : MOVE               : time.cob */
  cob_move (COB_SET_FLD (f0, 2, b_18 + 0LL, &a_6), &f_21);

  /* Line: 29        : MOVE               : time.cob */
  cob_move (COB_SET_FLD (f0, 2, b_18 + 2LL, &a_6), &f_22);

  /* Line: 30        : MOVE               : time.cob */
  cob_move (COB_SET_FLD (f0, 2, b_18 + 4LL, &a_6), &f_23);

  /* Line: 31        : MOVE               : time.cob */
  cob_move (COB_SET_FLD (f0, 2, b_18 + 6LL, &a_6), &f_24);

  /* Line: 33        : IF                 : time.cob */
  if (((int)memcmp (b_17, b_19, 8) != 0))
  {

    /* Line: 34        : MOVE               : time.cob */
    cob_move (cob_intr_integer_of_date (&f_17), &f_20);

    /* Line: 35        : MOVE               : time.cob */
    memcpy (b_19, b_17, 8);
  }

  /* Line: 37        : MOVE               : time.cob */
  memcpy (b_25, b_20, 4);

  /* Line: 39        : COMPUTE            : time.cob */
  cob_decimal_set_llint (d_0, (*(int *)(b_25)));
  cob_decimal_mul (d_0, dc_1);
  cob_decimal_set_field (d_1, &f_21);
  cob_decimal_mul (d_1, dc_2);
  cob_decimal_add (d_0, d_1);
  cob_decimal_set_field (d_1, &f_22);
  cob_decimal_mul (d_1, dc_3);
  cob_decimal_add (d_0, d_1);
  cob_decimal_set_field (d_1, &f_23);
  cob_decimal_mul (d_1, dc_4);
  cob_decimal_add (d_0, d_1);
  cob_decimal_set_field (d_1, &f_24);
  cob_decimal_add (d_0, d_1);
  cob_decimal_get_field (d_0, &f_26, 0);

  /* Line: 46        : MOVE               : time.cob */
  memmove (b_27, b_26, 8);

  /* Line: 47        : GOBACK             : time.cob */
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  TIMEUTIL_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-DATE */
  memset (b_17, (unsigned char)'0', 8);

  /* initialize field WS-TIME-X */
  memset (b_18, (unsigned char)' ', 8);

  /* initialize field CACHED-DATE */
  memset (b_19, 48, 8);

  /* initialize field CACHED-DAYS */
  cob_move ((cob_field *)&c_5, &f_20);

  /* initialize field WS-HH */
  memset (b_21, (unsigned char)'0', 2);

  /* initialize field WS-MM */
  memset (b_22, (unsigned char)'0', 2);

  /* initialize field WS-SS */
  memset (b_23, (unsigned char)'0', 2);

  /* initialize field WS-CC */
  memset (b_24, (unsigned char)'0', 2);

  /* initialize field WS-DAYS */
  memset (b_25, 0x0, 4);

  /* initialize field WS-CS */
  memset (b_26, 0x0, 8);


  /* Set Decimal Constant values */
  dc_4 = &kc_4;
  cob_decimal_init (dc_4);
  cob_decimal_set_field (dc_4, (cob_field *)&c_4);

  dc_3 = &kc_3;
  cob_decimal_init (dc_3);
  cob_decimal_set_field (dc_3, (cob_field *)&c_3);

  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_4);
  dc_4 = NULL;
  cob_decimal_clear (dc_3);
  dc_3 = NULL;
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'TIMEUTIL' */

/* Initialize module structure for TIMEUTIL */
static void TIMEUTIL_module_init (cob_module *module)
{
  module->module_name = "TIMEUTIL";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())TIMEUTIL;
  module->module_cancel.funcptr = (void *(*)())TIMEUTIL_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

