/* Generated by           cobc 3.2.0 */
/* Generated from         uci.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

/* Program local variables for 'MOVE2UCI' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */

/* Last USING parameters for possible later lookup */
static unsigned char    *last_b_63;
static unsigned char    *last_b_69;

/* Call parameters */
cob_field        *cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_55[8] __attribute__((aligned));    /* FILES */
static cob_u8_t    b_56[8] __attribute__((aligned));    /* RANKS */
static cob_u8_t    b_57[2] __attribute__((aligned));    /* F-FILE */
static cob_u8_t    b_58[2] __attribute__((aligned));    /* F-RANK */
static cob_u8_t    b_59[2] __attribute__((aligned));    /* T-FILE */
static cob_u8_t    b_60[2] __attribute__((aligned));    /* T-RANK */
static cob_u8_t    b_61[2] __attribute__((aligned));    /* FROM-SQ */
static cob_u8_t    b_62[2] __attribute__((aligned));    /* TO-SQ */

/* End of local data storage */


/* Fields (local) */
static cob_field f_57    = {2, b_57, &a_2};    /* F-FILE */
static cob_field f_58    = {2, b_58, &a_2};    /* F-RANK */
static cob_field f_59    = {2, b_59, &a_2};    /* T-FILE */
static cob_field f_60    = {2, b_60, &a_2};    /* T-RANK */
static cob_field f_61    = {2, b_61, &a_2};    /* FROM-SQ */
static cob_field f_62    = {2, b_62, &a_2};    /* TO-SQ */

/* End of fields */

