/* Generated by           cobc 3.2.0 */
/* Generated from         uci.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */


/* Module path */
static const char        *cob_module_path = NULL;

/* Number of call parameters */
static int        cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =    {0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_2 =    {0x11,   4,   0, 0x0041, NULL};


/* Constants */
static const cob_field c_1    = {2, (cob_u8_ptr)"16", &a_1};


static COB_INLINE COB_A_INLINE int
cob_cmp_s16 (const void *p, const cob_s64_t n)
{
    short    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 2);
    return (val < n) ? -1 : (val > n);
}


/* Decimal constants */
static    cob_decimal    kc_1;
static    cob_decimal    *dc_1 = NULL;

