/* Generated by           cobc 3.2.0 */
/* Generated from         uci.cob */
/* Generated at           Mar 30 2026 05:30:21 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free -frecursive -Wall attack.cob board.cob eval.cob fen.cob main.cob makemove.cob movegen.cob perft.cob search.cob time.cob uci.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE        "uci.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 05:30:21"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        53021

/* Global variables */
#include "uci.c.h"

/* Function prototypes */

COB_EXT_EXPORT int        MOVE2UCI (cob_u8_t *, cob_u8_t *);
static int        MOVE2UCI_ (const int, cob_u8_t *, cob_u8_t *);
static void        MOVE2UCI_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MOVE2UCI' */

/* ENTRY 'MOVE2UCI' */

int
MOVE2UCI (cob_u8_t *b_63, cob_u8_t *b_69)
{
  cob_u8_t *cob_parm_63 = NULL;    /* linkage for L-MOVE */
  cob_u8_t *cob_parm_69 = NULL;    /* linkage for L-OUT */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
      cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
      cob_call_params = 2;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_63 = b_63;
  }
  if (cob_call_params > 1) {
    cob_parm_69 = b_69;
  }

  return MOVE2UCI_ (0, cob_parm_63, cob_parm_69);
}

static int
MOVE2UCI_ (const int entry, cob_u8_t *b_63, cob_u8_t *b_69)
{
  /* Program local variables */
  #include "uci.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (1, &d_0);

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_63 = b_63;
  last_b_69 = b_69;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 29        : Entry     MOVE2UCI                : uci.cob */
  l_2:;

  /* Line: 29        : MOVE               : uci.cob */
  memset (b_69, 32, 8);

  /* Line: 31        : MOVE               : uci.cob */
  memmove (b_61, b_63, 2);

  /* Line: 32        : MOVE               : uci.cob */
  memmove (b_62, b_63 + 2, 2);

  /* Line: 34        : IF                 : uci.cob */
  if ((((((int)cob_cmp_s16 (b_61, 0LL) == 0) && 
      ((int)cob_cmp_s16 (b_62, 0LL) == 0)) && 
      ((int)cob_cmp_s16 (b_63 + 4, 0LL) == 0)) && 
      ((int)cob_cmp_s16 (b_63 + 6, 0LL) == 0)))
  {

    /* Line: 35        : MOVE               : uci.cob */
    memcpy (b_69 + 0LL, "0000    ", 4);

    /* Line: 36        : GOBACK             : uci.cob */
    goto exit_program;
  }

  /* Line: 39        : COMPUTE            : uci.cob */
  cob_decimal_set_field (d_0, cob_intr_mod (&f_61, (cob_field *)&c_1));
  cob_decimal_get_field (d_0, &f_57, 0);

  /* Line: 40        : DIVIDE             : uci.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_61)));
  cob_decimal_div (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_58, 0);

  /* Line: 41        : COMPUTE            : uci.cob */
  cob_decimal_set_field (d_0, cob_intr_mod (&f_62, (cob_field *)&c_1));
  cob_decimal_get_field (d_0, &f_59, 0);

  /* Line: 42        : DIVIDE             : uci.cob */
  cob_decimal_set_llint (d_0, (*(short *)(b_62)));
  cob_decimal_div (d_0, dc_1);
  cob_decimal_get_field (d_0, &f_60, 0);

  /* Line: 44        : MOVE               : uci.cob */
  *(b_69 + 0LL) = *(b_55 + ((cob_s64_t)(((*(short *)(b_57)) + 1)) - 1));

  /* Line: 45        : MOVE               : uci.cob */
  *(b_69 + 1LL) = *(b_56 + ((cob_s64_t)(((*(short *)(b_58)) + 1)) - 1));

  /* Line: 46        : MOVE               : uci.cob */
  *(b_69 + 2LL) = *(b_55 + ((cob_s64_t)(((*(short *)(b_59)) + 1)) - 1));

  /* Line: 47        : MOVE               : uci.cob */
  *(b_69 + 3LL) = *(b_56 + ((cob_s64_t)(((*(short *)(b_60)) + 1)) - 1));

  /* Line: 49        : IF                 : uci.cob */
  if (((int)cob_cmp_s16 (b_63 + 4, 0LL) != 0))
  {

    /* Line: 50        : EVALUATE           : uci.cob */

    /* Line: 51        : WHEN               : uci.cob */

    if (((int)cob_cmp_s16 (b_63 + 4, 1LL) == 0))
    {

      /* Line: 51        : MOVE               : uci.cob */
      memcpy (b_69 + 4LL, "q       ", 1);
      goto l_5;
    }

    /* Line: 52        : WHEN               : uci.cob */

    if (((int)cob_cmp_s16 (b_63 + 4, 2LL) == 0))
    {

      /* Line: 52        : MOVE               : uci.cob */
      memcpy (b_69 + 4LL, "r       ", 1);
      goto l_5;
    }

    /* Line: 53        : WHEN               : uci.cob */

    if (((int)cob_cmp_s16 (b_63 + 4, 3LL) == 0))
    {

      /* Line: 53        : MOVE               : uci.cob */
      memcpy (b_69 + 4LL, "b       ", 1);
      goto l_5;
    }

    /* Line: 54        : WHEN               : uci.cob */

    if (((int)cob_cmp_s16 (b_63 + 4, 4LL) == 0))
    {

      /* Line: 54        : MOVE               : uci.cob */
      memcpy (b_69 + 4LL, "n       ", 1);
      goto l_5;
    }

    /* WHEN OTHER */

    /* Line: 55        : MOVE               : uci.cob */
    memcpy (b_69 + 4LL, "q       ", 1);

    /* End EVALUATE */
    l_5:;
  }

  /* Line: 59        : GOBACK             : uci.cob */
  goto exit_program;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  MOVE2UCI_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field FILES */
  memcpy (b_55, "abcdefgh", 8);

  /* initialize field RANKS */
  memcpy (b_56, "12345678", 8);

  /* initialize field F-FILE */
  memset (b_57, 0x0, 2);

  /* initialize field F-RANK */
  memset (b_58, 0x0, 2);

  /* initialize field T-FILE */
  memset (b_59, 0x0, 2);

  /* initialize field T-RANK */
  memset (b_60, 0x0, 2);

  /* initialize field FROM-SQ */
  memset (b_61, 0x0, 2);

  /* initialize field TO-SQ */
  memset (b_62, 0x0, 2);


  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'MOVE2UCI' */

/* Initialize module structure for MOVE2UCI */
static void MOVE2UCI_module_init (cob_module *module)
{
  module->module_name = "MOVE2UCI";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MOVE2UCI;
  module->module_cancel.funcptr = (void *(*)())MOVE2UCI_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 2;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

