/* Generated by           cobc 3.2.0 */
/* Generated from         doom.cob */
/* Generated at           Mar 30 2026 06:49:28 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free doom.cob */

/* Program local variables for 'COBOL-DOOM' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;
cob_decimal    *d_2 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union    call_enable_raw_mode;
static cob_call_union    call_get_terminal_size;
static cob_call_union    call_show_title_c;
static cob_call_union    call_get_time_ms;
static cob_call_union    call_read_key;
static cob_call_union    call_show_death_c;
static cob_call_union    call_show_win_c;
static cob_call_union    call_set_intermission_data;
static cob_call_union    call_show_intermission_c;
static cob_call_union    call_frame_sleep;
static cob_call_union    call_compute_cos;
static cob_call_union    call_compute_sin;
static cob_call_union    call_check_los_c;
static cob_call_union    call_set_hud_health;
static cob_call_union    call_set_hud_ammo;
static cob_call_union    call_set_hud_score;
static cob_call_union    call_set_hud_enemies;
static cob_call_union    call_set_hud_weapon;
static cob_call_union    call_set_hud_damage;
static cob_call_union    call_set_hud_flash;
static cob_call_union    call_set_hud_level;
static cob_call_union    call_set_hud_armor;
static cob_call_union    call_set_hud_sprint;
static cob_call_union    call_set_num_enemies;
static cob_call_union    call_set_enemy_data;
static cob_call_union    call_set_num_pickups;
static cob_call_union    call_set_pickup_data;
static cob_call_union    call_render_frame;
static cob_call_union    call_disable_raw_mode;

/* Local cob_field items */
cob_field        f0;
cob_field        f1;
cob_field        f2;
cob_field        f3;


/* Call parameters */
cob_field        *cob_procedure_params[9];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_17[4] __attribute__((aligned));    /* SCR-WIDTH */
static cob_u8_t    b_18[4] __attribute__((aligned));    /* SCR-HEIGHT */
static cob_u8_t    b_19[4] __attribute__((aligned));    /* PLAYER-X */
static cob_u8_t    b_20[4] __attribute__((aligned));    /* PLAYER-Y */
static cob_u8_t    b_21[4] __attribute__((aligned));    /* PLAYER-ANGLE */
static cob_u8_t    b_22[4] __attribute__((aligned));    /* PLAYER-HEALTH */
static cob_u8_t    b_23[4] __attribute__((aligned));    /* PLAYER-ARMOR */
static cob_u8_t    b_24[4] __attribute__((aligned));    /* PLAYER-AMMO */
static cob_u8_t    b_25[4] __attribute__((aligned));    /* PLAYER-SCORE */
static cob_u8_t    b_26[4] __attribute__((aligned));    /* PLAYER-ALIVE */
static cob_u8_t    b_27[4] __attribute__((aligned));    /* CURRENT-WEAPON */
static cob_u8_t    b_28[4] __attribute__((aligned));    /* DAMAGE-FLASH */
static cob_u8_t    b_29[4] __attribute__((aligned));    /* SHOOT-COOLDOWN */
static cob_u8_t    b_30[4] __attribute__((aligned));    /* SHOOT-FLASH */
static cob_u8_t    b_31[4] __attribute__((aligned));    /* CURRENT-LEVEL */
static cob_u8_t    b_32[4] __attribute__((aligned));    /* IS-SPRINTING */
static cob_u8_t    b_33[4] __attribute__((aligned));    /* DIFFICULTY */
static cob_u8_t    b_34[4] __attribute__((aligned));    /* MOVE-DX */
static cob_u8_t    b_35[4] __attribute__((aligned));    /* MOVE-DY */
static cob_u8_t    b_36[4] __attribute__((aligned));    /* NEW-X */
static cob_u8_t    b_37[4] __attribute__((aligned));    /* NEW-Y */
static cob_u8_t    b_38[4] __attribute__((aligned));    /* CHECK-MAP-X */
static cob_u8_t    b_39[4] __attribute__((aligned));    /* CHECK-MAP-Y */
static cob_u8_t    b_40[4] __attribute__((aligned));    /* MOVE-SPEED */
static cob_u8_t    b_41[4] __attribute__((aligned));    /* TURN-SPEED */
static cob_u8_t    b_42[4] __attribute__((aligned));    /* EFFECTIVE-SPEED */
static cob_u8_t    b_43[4] __attribute__((aligned));    /* FOV */
static cob_u8_t    b_44[4] __attribute__((aligned));    /* MAP-WIDTH */
static cob_u8_t    b_45[4] __attribute__((aligned));    /* MAP-HEIGHT */
static cob_u8_t    b_46[576] __attribute__((aligned));    /* MAP-DATA */
static cob_u8_t    b_72[576] __attribute__((aligned));    /* L1-MAP-DATA */
static cob_u8_t    b_98[576] __attribute__((aligned));    /* L2-MAP-DATA */
static cob_u8_t    b_124[576] __attribute__((aligned));    /* L3-MAP-DATA */
static cob_u8_t    b_150[4] __attribute__((aligned));    /* MAX-ENEMIES */
static cob_u8_t    b_151[4] __attribute__((aligned));    /* ENEMY-COUNT */
static cob_u8_t    b_152[4] __attribute__((aligned));    /* ALIVE-ENEMIES */
static cob_u8_t    b_153[280] __attribute__((aligned));    /* ENEMY-TABLE */
static cob_u8_t    b_162[4] __attribute__((aligned));    /* MAX-PICKUPS */
static cob_u8_t    b_163[4] __attribute__((aligned));    /* PICKUP-COUNT */
static cob_u8_t    b_164[320] __attribute__((aligned));    /* PICKUP-TABLE */
static cob_u8_t    b_170[4] __attribute__((aligned));    /* GAME-RUNNING */
static cob_u8_t    b_171[4] __attribute__((aligned));    /* KEY-PRESSED */
static cob_u8_t    b_172[4] __attribute__((aligned));    /* FRAME-COUNT */
static cob_u8_t    b_173[8] __attribute__((aligned));    /* CURRENT-TIME */
static cob_u8_t    b_174[8] __attribute__((aligned));    /* LAST-FRAME-TIME */
static cob_u8_t    b_175[4] __attribute__((aligned));    /* DELTA-TIME */
static cob_u8_t    b_176[4] __attribute__((aligned));    /* GAME-STATE */
static cob_u8_t    b_177[4] __attribute__((aligned));    /* LEVEL-KILLS */
static cob_u8_t    b_178[4] __attribute__((aligned));    /* LEVEL-TOTAL-KILLS */
static cob_u8_t    b_179[4] __attribute__((aligned));    /* LEVEL-ITEMS */
static cob_u8_t    b_180[4] __attribute__((aligned));    /* LEVEL-TOTAL-ITEMS */
static cob_u8_t    b_181[8] __attribute__((aligned));    /* LEVEL-START-TIME */
static cob_u8_t    b_182[4] __attribute__((aligned));    /* LEVEL-TIME-SECS */
static cob_u8_t    b_183[4] __attribute__((aligned));    /* SIN-RESULT */
static cob_u8_t    b_184[4] __attribute__((aligned));    /* COS-RESULT */
static cob_u8_t    b_185[4] __attribute__((aligned));    /* ANGLE-PARAM */
static cob_u8_t    b_186[4] __attribute__((aligned));    /* WS-I */
static cob_u8_t    b_187[4] __attribute__((aligned));    /* WS-DIST */
static cob_u8_t    b_188[4] __attribute__((aligned));    /* WS-DX */
static cob_u8_t    b_189[4] __attribute__((aligned));    /* WS-DY */
static cob_u8_t    b_190[4] __attribute__((aligned));    /* WS-ENEMY-ANGLE */
static cob_u8_t    b_191[4] __attribute__((aligned));    /* WS-ANGLE-DIFF */
static cob_u8_t    b_192[4] __attribute__((aligned));    /* WS-DAMAGE */
static cob_u8_t    b_193[4] __attribute__((aligned));    /* ACTUAL-DAMAGE */
static cob_u8_t    b_194[4] __attribute__((aligned));    /* ARMOR-ABSORB */
static cob_u8_t    b_195[4] __attribute__((aligned));    /* LOS-RESULT */
static cob_u8_t    b_196[1] __attribute__((aligned));    /* MAP-CELL */
static cob_u8_t    b_197[4] __attribute__((aligned));    /* MAP-INDEX */
static cob_u8_t    b_198[4] __attribute__((aligned));    /* C-COLS */
static cob_u8_t    b_199[4] __attribute__((aligned));    /* C-ROWS */
static cob_u8_t    b_200[4] __attribute__((aligned));    /* ES-IDX */
static cob_u8_t    b_201[4] __attribute__((aligned));    /* ES-X */
static cob_u8_t    b_202[4] __attribute__((aligned));    /* ES-Y */
static cob_u8_t    b_203[4] __attribute__((aligned));    /* ES-ALIVE */
static cob_u8_t    b_204[4] __attribute__((aligned));    /* ES-TYPE */
static cob_u8_t    b_205[4] __attribute__((aligned));    /* ES-HP */
static cob_u8_t    b_206[4] __attribute__((aligned));    /* PS-IDX */
static cob_u8_t    b_207[4] __attribute__((aligned));    /* PS-X */
static cob_u8_t    b_208[4] __attribute__((aligned));    /* PS-Y */
static cob_u8_t    b_209[4] __attribute__((aligned));    /* PS-TYPE */
static cob_u8_t    b_210[4] __attribute__((aligned));    /* PS-ACTIVE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17    = {4, b_17, &a_6};    /* SCR-WIDTH */
static cob_field f_18    = {4, b_18, &a_6};    /* SCR-HEIGHT */
static cob_field f_19    = {4, b_19, &a_6};    /* PLAYER-X */
static cob_field f_20    = {4, b_20, &a_6};    /* PLAYER-Y */
static cob_field f_21    = {4, b_21, &a_6};    /* PLAYER-ANGLE */
static cob_field f_22    = {4, b_22, &a_6};    /* PLAYER-HEALTH */
static cob_field f_23    = {4, b_23, &a_6};    /* PLAYER-ARMOR */
static cob_field f_24    = {4, b_24, &a_6};    /* PLAYER-AMMO */
static cob_field f_25    = {4, b_25, &a_6};    /* PLAYER-SCORE */
static cob_field f_26    = {4, b_26, &a_6};    /* PLAYER-ALIVE */
static cob_field f_27    = {4, b_27, &a_6};    /* CURRENT-WEAPON */
static cob_field f_28    = {4, b_28, &a_6};    /* DAMAGE-FLASH */
static cob_field f_29    = {4, b_29, &a_6};    /* SHOOT-COOLDOWN */
static cob_field f_30    = {4, b_30, &a_6};    /* SHOOT-FLASH */
static cob_field f_31    = {4, b_31, &a_6};    /* CURRENT-LEVEL */
static cob_field f_32    = {4, b_32, &a_6};    /* IS-SPRINTING */
static cob_field f_33    = {4, b_33, &a_6};    /* DIFFICULTY */
static cob_field f_34    = {4, b_34, &a_6};    /* MOVE-DX */
static cob_field f_35    = {4, b_35, &a_6};    /* MOVE-DY */
static cob_field f_36    = {4, b_36, &a_6};    /* NEW-X */
static cob_field f_37    = {4, b_37, &a_6};    /* NEW-Y */
static cob_field f_38    = {4, b_38, &a_6};    /* CHECK-MAP-X */
static cob_field f_39    = {4, b_39, &a_6};    /* CHECK-MAP-Y */
static cob_field f_40    = {4, b_40, &a_6};    /* MOVE-SPEED */
static cob_field f_41    = {4, b_41, &a_6};    /* TURN-SPEED */
static cob_field f_42    = {4, b_42, &a_6};    /* EFFECTIVE-SPEED */
static cob_field f_43    = {4, b_43, &a_6};    /* FOV */
static cob_field f_44    = {4, b_44, &a_6};    /* MAP-WIDTH */
static cob_field f_45    = {4, b_45, &a_6};    /* MAP-HEIGHT */
static cob_field f_71    = {576, b_46, &a_10};    /* MAP-LINEAR */
static cob_field f_151    = {4, b_151, &a_6};    /* ENEMY-COUNT */
static cob_field f_152    = {4, b_152, &a_6};    /* ALIVE-ENEMIES */
static cob_field f_163    = {4, b_163, &a_6};    /* PICKUP-COUNT */
static cob_field f_170    = {4, b_170, &a_6};    /* GAME-RUNNING */
static cob_field f_171    = {4, b_171, &a_6};    /* KEY-PRESSED */
static cob_field f_172    = {4, b_172, &a_6};    /* FRAME-COUNT */
static cob_field f_173    = {8, b_173, &a_8};    /* CURRENT-TIME */
static cob_field f_174    = {8, b_174, &a_8};    /* LAST-FRAME-TIME */
static cob_field f_175    = {4, b_175, &a_6};    /* DELTA-TIME */
static cob_field f_176    = {4, b_176, &a_6};    /* GAME-STATE */
static cob_field f_177    = {4, b_177, &a_6};    /* LEVEL-KILLS */
static cob_field f_178    = {4, b_178, &a_6};    /* LEVEL-TOTAL-KILLS */
static cob_field f_179    = {4, b_179, &a_6};    /* LEVEL-ITEMS */
static cob_field f_180    = {4, b_180, &a_6};    /* LEVEL-TOTAL-ITEMS */
static cob_field f_181    = {8, b_181, &a_8};    /* LEVEL-START-TIME */
static cob_field f_182    = {4, b_182, &a_6};    /* LEVEL-TIME-SECS */
static cob_field f_183    = {4, b_183, &a_6};    /* SIN-RESULT */
static cob_field f_184    = {4, b_184, &a_6};    /* COS-RESULT */
static cob_field f_185    = {4, b_185, &a_6};    /* ANGLE-PARAM */
static cob_field f_186    = {4, b_186, &a_6};    /* WS-I */
static cob_field f_187    = {4, b_187, &a_6};    /* WS-DIST */
static cob_field f_188    = {4, b_188, &a_6};    /* WS-DX */
static cob_field f_189    = {4, b_189, &a_6};    /* WS-DY */
static cob_field f_190    = {4, b_190, &a_6};    /* WS-ENEMY-ANGLE */
static cob_field f_191    = {4, b_191, &a_6};    /* WS-ANGLE-DIFF */
static cob_field f_192    = {4, b_192, &a_6};    /* WS-DAMAGE */
static cob_field f_193    = {4, b_193, &a_6};    /* ACTUAL-DAMAGE */
static cob_field f_194    = {4, b_194, &a_6};    /* ARMOR-ABSORB */
static cob_field f_195    = {4, b_195, &a_6};    /* LOS-RESULT */
static cob_field f_197    = {4, b_197, &a_6};    /* MAP-INDEX */
static cob_field f_198    = {4, b_198, &a_5};    /* C-COLS */
static cob_field f_199    = {4, b_199, &a_5};    /* C-ROWS */
static cob_field f_200    = {4, b_200, &a_6};    /* ES-IDX */
static cob_field f_201    = {4, b_201, &a_6};    /* ES-X */
static cob_field f_202    = {4, b_202, &a_6};    /* ES-Y */
static cob_field f_203    = {4, b_203, &a_6};    /* ES-ALIVE */
static cob_field f_204    = {4, b_204, &a_6};    /* ES-TYPE */
static cob_field f_205    = {4, b_205, &a_6};    /* ES-HP */
static cob_field f_206    = {4, b_206, &a_6};    /* PS-IDX */
static cob_field f_207    = {4, b_207, &a_6};    /* PS-X */
static cob_field f_208    = {4, b_208, &a_6};    /* PS-Y */
static cob_field f_209    = {4, b_209, &a_6};    /* PS-TYPE */
static cob_field f_210    = {4, b_210, &a_6};    /* PS-ACTIVE */

/* End of fields */

