/* Generated by           cobc 3.2.0 */
/* Generated from         doom.cob */
/* Generated at           Mar 30 2026 06:49:28 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -free doom.cob */


/* Module path */
static const char        *cob_module_path = NULL;

/* Number of call parameters */
static int        cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =    {0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =    {0x10,   5,   0, 0x1000, NULL};
static const cob_field_attr a_3 =    {0x10,   4,   0, 0x1000, NULL};
static const cob_field_attr a_4 =    {0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_5 =    {0x11,   8,   0, 0x0041, NULL};
static const cob_field_attr a_6 =    {0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_7 =    {0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_8 =    {0x11,  18,   0, 0x0041, NULL};
static const cob_field_attr a_9 =    {0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_10 =    {0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1    = {1, (cob_u8_ptr)"2", &a_1};
static const cob_field c_2    = {1, (cob_u8_ptr)"3", &a_1};
static const cob_field c_3    = {5, (cob_u8_ptr)"10000", &a_2};
static const cob_field c_4    = {4, (cob_u8_ptr)"9000", &a_3};
static const cob_field c_5    = {3, (cob_u8_ptr)"120", &a_4};
static const cob_field c_6    = {3, (cob_u8_ptr)"100", &a_4};
static const cob_field c_7    = {1, (cob_u8_ptr)"1", &a_1};
static const cob_field c_8    = {4, (cob_u8_ptr)"1000", &a_3};
static const cob_field c_9    = {1, (cob_u8_ptr)"4", &a_1};
static const cob_field c_10    = {3, (cob_u8_ptr)"200", &a_4};
static const cob_field c_11    = {2, (cob_u8_ptr)"70", &a_7};
static const cob_field c_12    = {1, (cob_u8_ptr)"0", &a_1};
static const cob_field c_13    = {3, (cob_u8_ptr)"250", &a_4};
static const cob_field c_14    = {3, (cob_u8_ptr)"150", &a_4};
static const cob_field c_15    = {4, (cob_u8_ptr)"4500", &a_3};
static const cob_field c_16    = {2, (cob_u8_ptr)"10", &a_7};
static const cob_field c_17    = {3, (cob_u8_ptr)"800", &a_4};
static const cob_field c_18    = {3, (cob_u8_ptr)"400", &a_4};
static const cob_field c_19    = {2, (cob_u8_ptr)"30", &a_7};
static const cob_field c_20    = {4, (cob_u8_ptr)"1400", &a_3};
static const cob_field c_21    = {3, (cob_u8_ptr)"350", &a_4};
static const cob_field c_22    = {3, (cob_u8_ptr)"900", &a_4};
static const cob_field c_23    = {4, (cob_u8_ptr)"1150", &a_3};
static const cob_field c_24    = {2, (cob_u8_ptr)"60", &a_7};
static const cob_field c_25    = {4, (cob_u8_ptr)"1100", &a_3};
static const cob_field c_26    = {3, (cob_u8_ptr)"500", &a_4};
static const cob_field c_27    = {4, (cob_u8_ptr)"1600", &a_3};
static const cob_field c_28    = {4, (cob_u8_ptr)"1800", &a_3};
static const cob_field c_29    = {3, (cob_u8_ptr)"850", &a_4};
static const cob_field c_30    = {4, (cob_u8_ptr)"2050", &a_3};
static const cob_field c_31    = {3, (cob_u8_ptr)"600", &a_4};
static const cob_field c_32    = {4, (cob_u8_ptr)"1550", &a_3};
static const cob_field c_33    = {4, (cob_u8_ptr)"2000", &a_3};
static const cob_field c_34    = {4, (cob_u8_ptr)"2200", &a_3};
static const cob_field c_35    = {3, (cob_u8_ptr)"450", &a_4};
static const cob_field c_36    = {4, (cob_u8_ptr)"2100", &a_3};
static const cob_field c_37    = {4, (cob_u8_ptr)"1500", &a_3};
static const cob_field c_38    = {3, (cob_u8_ptr)"700", &a_4};
static const cob_field c_39    = {3, (cob_u8_ptr)"650", &a_4};
static const cob_field c_40    = {4, (cob_u8_ptr)"1900", &a_3};
static const cob_field c_41    = {3, (cob_u8_ptr)"300", &a_4};
static const cob_field c_42    = {4, (cob_u8_ptr)"1850", &a_3};
static const cob_field c_43    = {2, (cob_u8_ptr)"50", &a_7};
static const cob_field c_44    = {2, (cob_u8_ptr)"80", &a_7};
static const cob_field c_45    = {1, (cob_u8_ptr)".", &a_9};
static const cob_field c_46    = {1, (cob_u8_ptr)"8", &a_1};
static const cob_field c_47    = {1, (cob_u8_ptr)"6", &a_1};
static const cob_field c_48    = {2, (cob_u8_ptr)"15", &a_7};
static const cob_field c_49    = {2, (cob_u8_ptr)"40", &a_7};
static const cob_field c_50    = {2, (cob_u8_ptr)"20", &a_7};
static const cob_field c_51    = {1, (cob_u8_ptr)" ", &a_9};
static const cob_field c_52    = {30, (cob_u8_ptr)"Thanks for playing COBOL-DOOM!", &a_9};
static const cob_field c_53    = {13, (cob_u8_ptr)"Final Score: ", &a_9};
static const cob_field c_54    = {2, (cob_u8_ptr)"22", &a_7};
static const cob_field c_55    = {2, (cob_u8_ptr)"25", &a_7};
static const cob_field c_56    = {4, (cob_u8_ptr)"6600", &a_3};
static const cob_field c_57    = {2, (cob_u8_ptr)"24", &a_7};


static COB_INLINE COB_A_INLINE int
cob_cmp_s32 (const void *p, const cob_s64_t n)
{
    int    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 4);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_add_s32 (void *p, const int val)
{
    void    *x;
    int    n;
    x = &n;
    optim_memcpy (x, p, 4);
    n += val;
    optim_memcpy (p, x, 4);
}


static COB_INLINE COB_A_INLINE void
cob_sub_s32 (void *p, const int val)
{
    void    *x;
    int    n;
    x = &n;
    optim_memcpy (x, p, 4);
    n -= val;
    optim_memcpy (p, x, 4);
}


/* Decimal constants */
static    cob_decimal    kc_1;
static    cob_decimal    *dc_1 = NULL;
static    cob_decimal    kc_2;
static    cob_decimal    *dc_2 = NULL;
static    cob_decimal    kc_3;
static    cob_decimal    *dc_3 = NULL;
static    cob_decimal    kc_4;
static    cob_decimal    *dc_4 = NULL;
static    cob_decimal    kc_5;
static    cob_decimal    *dc_5 = NULL;
static    cob_decimal    kc_6;
static    cob_decimal    *dc_6 = NULL;
static    cob_decimal    kc_7;
static    cob_decimal    *dc_7 = NULL;
static    cob_decimal    kc_8;
static    cob_decimal    *dc_8 = NULL;
static    cob_decimal    kc_9;
static    cob_decimal    *dc_9 = NULL;

