/* Generated by           cobc 3.2.0 */
/* Generated from         flappy.cob */
/* Generated at           Mar 30 2026 13:57:52 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -x -free -fstatic-call -I cobol -o flappy.c flappy.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE        "flappy.cob"
#define  COB_PACKAGE_VERSION        "3.2"
#define  COB_PATCH_LEVEL        0
#define  COB_MODULE_FORMATTED_DATE    "Mar 30 2026 13:57:52"
#define  COB_MODULE_DATE        20260330
#define  COB_MODULE_TIME        135752

/* Global variables */
#include "flappy.c.h"

/* Function prototypes */

static int        flappy ();
static int        flappy_ (const int);
static void        flappy_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (flappy ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'flappy' */

/* ENTRY 'flappy' */

static int
flappy ()
{
  return flappy_ (0);
}

static int
flappy_ (const int entry)
{
  /* Program local variables */
  #include "flappy.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
      if (entry == -10)
          goto P_dump;
      if (entry == -20)
          goto P_clear_decimal;
      goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
      return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
      goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (3, &d_0, &d_1, &d_2);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 73        : Entry     flappy                  : flappy.cob */
  l_2:;

  /* Line: 73        : SET                : flappy.cob */
  {
    void *temp_ptr;
    temp_ptr = 0;
    memcpy(b_17, &temp_ptr, sizeof(temp_ptr));
  }

  /* Line: 74        : SET                : flappy.cob */
  {
    void *temp_ptr;
    temp_ptr = 0;
    memcpy(b_18, &temp_ptr, sizeof(temp_ptr));
  }

  /* Line: 76        : CALL               : flappy.cob */
  {
    int ret;

    cob_glob_ptr->cob_call_params = 0;
    cob_glob_ptr->cob_stmt_exception = 0;
    ret = cpg_init ();
    cob_set_int (&f_45, ret);
  }

  /* Line: 77        : IF                 : flappy.cob */
  if (((int)cob_cmp_s32 (b_45, 0LL) != 0))
  {

    /* Line: 78        : CALL               : flappy.cob */
    cob_procedure_params[0] = &f_51;
    cob_procedure_params[1] = (cob_field *)&c_4;
    cob_glob_ptr->cob_call_params = 2;
    cob_glob_ptr->cob_stmt_exception = 0;
    b_2 = cpg_get_error (b_51, (cob_u64_t)256LL);

    /* Line: 79        : DISPLAY            : flappy.cob */
    cob_display (0, 1, 2, &c_5, &f_51);

    /* Line: 80        : STOP RUN           : flappy.cob */
    cob_stop_run (b_2);
  }

  /* Line: 83        : CALL               : flappy.cob */
  {
    int ret;

    cob_procedure_params[0] = &f_50;
    cob_procedure_params[1] = (cob_field *)&c_6;
    cob_procedure_params[2] = &f_52;
    cob_procedure_params[3] = &f_53;
    cob_procedure_params[4] = &f_17;
    cob_procedure_params[5] = &f_18;
    cob_glob_ptr->cob_call_params = 6;
    cob_glob_ptr->cob_stmt_exception = 0;
    ret = cpg_create_window_and_renderer (b_50, (cob_u64_t)0LL, (cob_u64_t)((*(int *)(b_52))), (cob_u64_t)((*(int *)(b_53))), b_17, b_18);
    cob_set_int (&f_45, ret);
  }

  /* Line: 91        : IF                 : flappy.cob */
  if (((int)cob_cmp_s32 (b_45, 0LL) != 0))
  {

    /* Line: 92        : CALL               : flappy.cob */
    cob_procedure_params[0] = &f_51;
    cob_procedure_params[1] = (cob_field *)&c_4;
    cob_glob_ptr->cob_call_params = 2;
    cob_glob_ptr->cob_stmt_exception = 0;
    b_2 = cpg_get_error (b_51, (cob_u64_t)256LL);

    /* Line: 93        : DISPLAY            : flappy.cob */
    cob_display (0, 1, 2, &c_7, &f_51);

    /* Line: 94        : CALL               : flappy.cob */
    cob_glob_ptr->cob_call_params = 0;
    cob_glob_ptr->cob_stmt_exception = 0;
    b_2 = cpg_quit ();

    /* Line: 95        : STOP RUN           : flappy.cob */
    cob_stop_run (b_2);
  }

  /* Line: 98        : COMPUTE            : flappy.cob */
  cob_decimal_set_llint (d_0, (*(int *)(b_53)));
  cob_decimal_set_llint (d_1, (*(int *)(b_54)));
  cob_decimal_sub (d_0, d_1);
  cob_decimal_get_field (d_0, &f_55, 0);

  /* Line: 100       : CALL               : flappy.cob */
  {
    int ret;

    cob_glob_ptr->cob_call_params = 0;
    cob_glob_ptr->cob_stmt_exception = 0;
    ret = cpg_ticks ();
    cob_set_int (&f_82, ret);
  }

  /* Line: 101       : COMPUTE            : flappy.cob */
  cob_decimal_set_field (d_0, cob_intr_random (1, &f_82));
  cob_decimal_get_field (d_0, &f_83, 0);

  /* Line: 103       : PERFORM            : flappy.cob */
  /* PERFORM RESET-GAME */
  frame_ptr++;
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_18;
  goto l_5;
  l_18:
  frame_ptr--;

  /* Line: 105       : PERFORM            : flappy.cob */
  for (;;)
  {
    /* Line: 105       : UNTIL              : flappy.cob */
    if (((int)(int)(*(b_46) - (unsigned char)'N') == 0))
      break;

    /* Line: 106       : CALL               : flappy.cob */
    {
      int ret;

      cob_glob_ptr->cob_call_params = 0;
      cob_glob_ptr->cob_stmt_exception = 0;
      ret = cpg_ticks ();
      cob_set_int (&f_57, ret);
    }

    /* Line: 108       : PERFORM            : flappy.cob */
    /* PERFORM HANDLE-EVENTS */
    frame_ptr++;
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_19;
    goto l_7;
    l_19:
    frame_ptr--;

    /* Line: 109       : IF                 : flappy.cob */
    if (((int)cob_cmp_numdisp (b_47, 1, 0LL, 0) == 0))
    {

      /* Line: 110       : PERFORM            : flappy.cob */
      /* PERFORM UPDATE-GAME */
      frame_ptr++;
      frame_ptr->perform_through = 10;
      frame_ptr->return_address_ptr = &&l_20;
      goto l_10;
      l_20:
      frame_ptr--;
    }

    /* Line: 112       : PERFORM            : flappy.cob */
    /* PERFORM RENDER */
    frame_ptr++;
    frame_ptr->perform_through = 17;
    frame_ptr->return_address_ptr = &&l_21;
    goto l_17;
    l_21:
    frame_ptr--;

    /* Line: 114       : CALL               : flappy.cob */
    {
      int ret;

      cob_glob_ptr->cob_call_params = 0;
      cob_glob_ptr->cob_stmt_exception = 0;
      ret = cpg_ticks ();
      cob_set_int (&f_58, ret);
    }

    /* Line: 115       : COMPUTE            : flappy.cob */
    cob_decimal_set_llint (d_0, (*(int *)(b_58)));
    cob_decimal_set_llint (d_1, (*(int *)(b_57)));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_59, 0);

    /* Line: 116       : IF                 : flappy.cob */
    if ((((int)cob_cmp_s32 (b_59, (*(int *)(b_56))) < 0) && 
        ((int)cob_cmp_s32 (b_59, 0LL) >= 0)))
    {

      /* Line: 117       : COMPUTE            : flappy.cob */
      cob_decimal_set_llint (d_0, (*(int *)(b_56)));
      cob_decimal_set_llint (d_1, (*(int *)(b_59)));
      cob_decimal_sub (d_0, d_1);
      cob_decimal_get_field (d_0, &f_60, 0);

      /* Line: 118       : CALL               : flappy.cob */
      cob_procedure_params[0] = &f_60;
      cob_glob_ptr->cob_call_params = 1;
      cob_glob_ptr->cob_stmt_exception = 0;
      b_2 = cpg_delay ((cob_u64_t)((*(int *)(b_60))));
    }
  }

  /* Line: 122       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_destroy_renderer (b_18);

  /* Line: 123       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_17;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_destroy_window (b_17);

  /* Line: 124       : CALL               : flappy.cob */
  cob_glob_ptr->cob_call_params = 0;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_quit ();

  /* Line: 125       : STOP RUN           : flappy.cob */
  cob_stop_run (b_2);

  /* Line: 127       : Paragraph RESET-GAME              : flappy.cob */
  l_5:;

  /* Line: 128       : MOVE               : flappy.cob */
  cob_move ((cob_field *)&c_6, &f_79);

  /* Line: 129       : MOVE               : flappy.cob */
  cob_move ((cob_field *)&c_6, &f_64);

  /* Line: 130       : MOVE               : flappy.cob */
  cob_move ((cob_field *)&c_8, &f_61);

  /* Line: 131       : COMPUTE            : flappy.cob */
  cob_decimal_set_llint (d_0, (*(int *)(b_53)));
  cob_decimal_div (d_0, dc_1);
  cob_decimal_sub (d_0, dc_2);
  cob_decimal_get_field (d_0, &f_62, 0);

  /* Line: 133       : PERFORM            : flappy.cob */
  cob_move ((cob_field *)&c_3, &f_77);
  for (;;)
  {
    /* Line: 133       : UNTIL              : flappy.cob */
    if (((int)cob_cmp_s32 (b_77, (*(int *)(b_67))) > 0))
      break;

    /* Line: 134       : COMPUTE            : flappy.cob */
    cob_decimal_set_llint (d_0, (*(int *)(b_52)));
    cob_decimal_set_llint (d_1, (*(int *)(b_77)));
    cob_decimal_sub (d_1, dc_3);
    cob_decimal_set_llint (d_2, (*(int *)(b_70)));
    cob_decimal_mul (d_1, d_2);
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3), 0);

    /* Line: 135       : MOVE               : flappy.cob */
    cob_move ((cob_field *)&c_6, COB_SET_FLD (f0, 1, b_72 + 8 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_9));

    /* Line: 136       : PERFORM            : flappy.cob */
    /* PERFORM RANDOMIZE-GAP */
    frame_ptr++;
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_22;
    goto l_6;
    l_22:
    frame_ptr--;
    /* Line: 133       : VARYING            : flappy.cob */
    cob_add_s32 (b_77, 1);
  }

  /* Line: 139       : SET                : flappy.cob */
  *(b_47) = 48;

  /* Line: 140       : PERFORM            : flappy.cob */
  /* PERFORM UPDATE-TITLE */
  frame_ptr++;
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_23;
  goto l_16;
  l_23:
  frame_ptr--;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 143       : Paragraph RANDOMIZE-GAP           : flappy.cob */
  l_6:;

  /* Line: 144       : COMPUTE            : flappy.cob */
  cob_decimal_set_llint (d_0, (*(int *)(b_55)));
  cob_decimal_set_llint (d_1, (*(int *)(b_69)));
  cob_decimal_sub (d_0, d_1);
  cob_decimal_set_llint (d_1, (*(int *)(b_84)));
  cob_decimal_sub (d_0, d_1);
  cob_decimal_get_field (d_0, &f_85, 0);

  /* Line: 145       : IF                 : flappy.cob */
  if (((int)cob_cmp_s32 (b_85, (*(int *)(b_84))) < 0))
  {

    /* Line: 146       : MOVE               : flappy.cob */
    memcpy (b_85, b_84, 4);
  }

  /* Line: 148       : COMPUTE            : flappy.cob */
  cob_decimal_set_llint (d_0, (*(int *)(b_85)));
  cob_decimal_set_llint (d_1, (*(int *)(b_84)));
  cob_decimal_sub (d_0, d_1);
  cob_decimal_get_field (d_0, &f_86, 0);

  /* Line: 150       : COMPUTE            : flappy.cob */
  cob_decimal_set_field (d_0, cob_intr_random (0));
  cob_decimal_get_field (d_0, &f_83, 0);

  /* Line: 151       : COMPUTE            : flappy.cob */
  cob_decimal_set_field (d_0, cob_intr_integer (cob_intr_binop (&f_83, '*', cob_intr_binop (&f_86, '+', (cob_field *)&c_3))));
  cob_decimal_get_field (d_0, &f_87, 0);

  /* Line: 152       : COMPUTE            : flappy.cob */
  cob_decimal_set_llint (d_0, (*(int *)(b_84)));
  cob_decimal_set_llint (d_1, (*(int *)(b_87)));
  cob_decimal_add (d_0, d_1);
  cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_72 + 4 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3), 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 155       : Paragraph HANDLE-EVENTS           : flappy.cob */
  l_7:;

  /* Line: 156       : PERFORM            : flappy.cob */

  /* Line: 157       : CALL               : flappy.cob */
  {
    int ret;

    cob_procedure_params[0] = &f_20;
    cob_glob_ptr->cob_call_params = 1;
    cob_glob_ptr->cob_stmt_exception = 0;
    ret = cpg_poll_event (b_20);
    cob_set_int (&f_45, ret);
  }

  /* Line: 158       : IF                 : flappy.cob */
  if (((int)cob_cmp_s32 (b_45, 0LL) == 0))
  {

    /* Line: 159       : EXIT PERFORM       : flappy.cob */
    goto l_8;
  }

  /* Line: 162       : IF                 : flappy.cob */
  if (((int)cob_cmp_s32 (b_20, 256LL) == 0))
  {

    /* Line: 163       : MOVE               : flappy.cob */
    *(b_46) = 78;
  }

  /* Line: 166       : IF                 : flappy.cob */
  if (((int)cob_cmp_s32 (b_20, 768LL) == 0))
  {

    /* Line: 167       : IF                 : flappy.cob */
    if (((int)cob_cmp_s32 (b_20 + 4, 27LL) == 0))
    {

      /* Line: 168       : MOVE               : flappy.cob */
      *(b_46) = 78;
    }

    /* Line: 171       : IF                 : flappy.cob */
    if ((((int)cob_cmp_s32 (b_20 + 4, 32LL) == 0) || 
        ((int)cob_cmp_s32 (b_20 + 4, 1073741906LL) == 0)))
    {

      /* Line: 172       : PERFORM            : flappy.cob */
      /* PERFORM ACTION-FLAP-OR-RESTART */
      frame_ptr++;
      frame_ptr->perform_through = 9;
      frame_ptr->return_address_ptr = &&l_24;
      goto l_9;
      l_24:
      frame_ptr--;
    }
  }

  /* Line: 176       : IF                 : flappy.cob */
  if (((int)cob_cmp_s32 (b_20, 1025LL) == 0))
  {

    /* Line: 177       : IF                 : flappy.cob */
    if (((int)cob_cmp_s32 (b_20 + 24, 1LL) == 0))
    {

      /* Line: 178       : PERFORM            : flappy.cob */
      /* PERFORM ACTION-FLAP-OR-RESTART */
      frame_ptr++;
      frame_ptr->perform_through = 9;
      frame_ptr->return_address_ptr = &&l_25;
      goto l_9;
      l_25:
      frame_ptr--;
    }
  }

  /* Implicit EXIT label */
  l_8:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 184       : Paragraph ACTION-FLAP-OR-RESTART  : flappy.cob */
  l_9:;

  /* Line: 185       : IF                 : flappy.cob */
  if (((int)cob_cmp_numdisp (b_47, 1, 0LL, 0) == 0))
  {

    /* Line: 186       : MOVE               : flappy.cob */
    memcpy (b_64, b_66, 4);
  }
  else
  {
    /* ELSE */

    /* Line: 188       : PERFORM            : flappy.cob */
    /* PERFORM RESET-GAME */
    frame_ptr++;
    frame_ptr->perform_through = 5;
    frame_ptr->return_address_ptr = &&l_26;
    goto l_5;
    l_26:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 192       : Paragraph UPDATE-GAME             : flappy.cob */
  l_10:;

  /* Line: 193       : ADD                : flappy.cob */
  cob_add_s32 (b_64, (*(int *)(b_65)));

  /* Line: 194       : ADD                : flappy.cob */
  cob_add_s32 (b_62, (*(int *)(b_64)));

  /* Line: 196       : IF                 : flappy.cob */
  if (((int)cob_cmp_s32 (b_62, 0LL) < 0))
  {

    /* Line: 197       : MOVE               : flappy.cob */
    cob_move ((cob_field *)&c_6, &f_62);

    /* Line: 198       : MOVE               : flappy.cob */
    cob_move ((cob_field *)&c_6, &f_64);
  }

  /* Line: 201       : IF                 : flappy.cob */
  if (((int)(
  cob_decimal_set_llint (d_0, (*(int *)(b_62))),
  cob_decimal_set_llint (d_2, (*(int *)(b_63))),
  cob_decimal_add (d_0, d_2),
  cob_decimal_set_llint (d_1, (*(int *)(b_55))),
  cob_decimal_cmp (d_0, d_1)) >= 0))
  {

    /* Line: 202       : PERFORM            : flappy.cob */
    /* PERFORM GAME-OVER */
    frame_ptr++;
    frame_ptr->perform_through = 15;
    frame_ptr->return_address_ptr = &&l_27;
    goto l_15;
    l_27:
    frame_ptr--;

    /* Line: 203       : EXIT PARAGRAPH     : flappy.cob */
    goto l_11;
  }

  /* Line: 206       : PERFORM            : flappy.cob */
  /* PERFORM MOVE-PIPES */
  frame_ptr++;
  frame_ptr->perform_through = 12;
  frame_ptr->return_address_ptr = &&l_28;
  goto l_12;
  l_28:
  frame_ptr--;

  /* Line: 207       : PERFORM            : flappy.cob */
  /* PERFORM CHECK-SCORE */
  frame_ptr++;
  frame_ptr->perform_through = 13;
  frame_ptr->return_address_ptr = &&l_29;
  goto l_13;
  l_29:
  frame_ptr--;

  /* Line: 208       : PERFORM            : flappy.cob */
  /* PERFORM CHECK-COLLISIONS */
  frame_ptr++;
  frame_ptr->perform_through = 14;
  frame_ptr->return_address_ptr = &&l_30;
  goto l_14;
  l_30:
  frame_ptr--;

  /* Implicit EXIT label */
  l_11:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 211       : Paragraph MOVE-PIPES              : flappy.cob */
  l_12:;

  /* Line: 212       : PERFORM            : flappy.cob */
  cob_move ((cob_field *)&c_3, &f_77);
  for (;;)
  {
    /* Line: 212       : UNTIL              : flappy.cob */
    if (((int)cob_cmp_s32 (b_77, (*(int *)(b_67))) > 0))
      break;

    /* Line: 213       : SUBTRACT           : flappy.cob */
    cob_sub_s32 (b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), (*(int *)(b_71)));
    /* Line: 212       : VARYING            : flappy.cob */
    cob_add_s32 (b_77, 1);
  }

  /* Line: 216       : MOVE               : flappy.cob */
  cob_move ((cob_field *)&c_9, &f_78);

  /* Line: 217       : PERFORM            : flappy.cob */
  cob_move ((cob_field *)&c_3, &f_77);
  for (;;)
  {
    /* Line: 217       : UNTIL              : flappy.cob */
    if (((int)cob_cmp_s32 (b_77, (*(int *)(b_67))) > 0))
      break;

    /* Line: 218       : IF                 : flappy.cob */
    if (((int)cob_cmp_s32 (b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), (*(int *)(b_78))) > 0))
    {

      /* Line: 219       : MOVE               : flappy.cob */
      memcpy (b_78, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), 4);
    }
    /* Line: 217       : VARYING            : flappy.cob */
    cob_add_s32 (b_77, 1);
  }

  /* Line: 223       : PERFORM            : flappy.cob */
  cob_move ((cob_field *)&c_3, &f_77);
  for (;;)
  {
    /* Line: 223       : UNTIL              : flappy.cob */
    if (((int)cob_cmp_s32 (b_77, (*(int *)(b_67))) > 0))
      break;

    /* Line: 224       : IF                 : flappy.cob */
    if (((int)(
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3))),
    cob_decimal_set_llint (d_2, (*(int *)(b_68))),
    cob_decimal_add (d_0, d_2),
    cob_decimal_set_llint (d_1, 0LL),
    cob_decimal_cmp (d_0, d_1)) < 0))
    {

      /* Line: 225       : COMPUTE            : flappy.cob */
      cob_decimal_set_llint (d_0, (*(int *)(b_78)));
      cob_decimal_set_llint (d_1, (*(int *)(b_70)));
      cob_decimal_add (d_0, d_1);
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3), 0);

      /* Line: 226       : MOVE               : flappy.cob */
      cob_move ((cob_field *)&c_6, COB_SET_FLD (f0, 1, b_72 + 8 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_9));

      /* Line: 227       : PERFORM            : flappy.cob */
      /* PERFORM RANDOMIZE-GAP */
      frame_ptr++;
      frame_ptr->perform_through = 6;
      frame_ptr->return_address_ptr = &&l_31;
      goto l_6;
      l_31:
      frame_ptr--;

      /* Line: 228       : MOVE               : flappy.cob */
      memcpy (b_78, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), 4);
    }
    /* Line: 223       : VARYING            : flappy.cob */
    cob_add_s32 (b_77, 1);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 233       : Paragraph CHECK-SCORE             : flappy.cob */
  l_13:;

  /* Line: 234       : PERFORM            : flappy.cob */
  cob_move ((cob_field *)&c_3, &f_77);
  for (;;)
  {
    /* Line: 234       : UNTIL              : flappy.cob */
    if (((int)cob_cmp_s32 (b_77, (*(int *)(b_67))) > 0))
      break;

    /* Line: 235       : IF                 : flappy.cob */
    if (((int)cob_cmp_u8 (b_72 + 8 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), 0LL) == 0))
    {

      /* Line: 236       : IF                 : flappy.cob */
      if (((int)(
      cob_decimal_set_llint (d_0, (*(int *)(b_61))),
      cob_decimal_set_llint (d_1, cob_get_llint (COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3))),
      cob_decimal_set_llint (d_2, (*(int *)(b_68))),
      cob_decimal_add (d_1, d_2),
      cob_decimal_cmp (d_0, d_1)) > 0))
      {

        /* Line: 237       : ADD                : flappy.cob */
        cob_add_s32 (b_79, 1);

        /* Line: 238       : MOVE               : flappy.cob */
        cob_move ((cob_field *)&c_3, COB_SET_FLD (f0, 1, b_72 + 8 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_9));

        /* Line: 239       : PERFORM            : flappy.cob */
        /* PERFORM UPDATE-TITLE */
        frame_ptr++;
        frame_ptr->perform_through = 16;
        frame_ptr->return_address_ptr = &&l_32;
        goto l_16;
        l_32:
        frame_ptr--;
      }
    }
    /* Line: 234       : VARYING            : flappy.cob */
    cob_add_s32 (b_77, 1);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 13)
    goto *frame_ptr->return_address_ptr;

  /* Line: 245       : Paragraph CHECK-COLLISIONS        : flappy.cob */
  l_14:;

  /* Line: 246       : MOVE               : flappy.cob */
  *(b_94) = 78;

  /* Line: 248       : COMPUTE            : flappy.cob */
  cob_decimal_set_llint (d_0, (*(int *)(b_61)));
  cob_decimal_set_llint (d_1, (*(int *)(b_63)));
  cob_decimal_add (d_0, d_1);
  cob_decimal_get_field (d_0, &f_88, 0);

  /* Line: 249       : COMPUTE            : flappy.cob */
  cob_decimal_set_llint (d_0, (*(int *)(b_62)));
  cob_decimal_set_llint (d_1, (*(int *)(b_63)));
  cob_decimal_add (d_0, d_1);
  cob_decimal_get_field (d_0, &f_89, 0);

  /* Line: 251       : PERFORM            : flappy.cob */
  cob_move ((cob_field *)&c_3, &f_77);
  for (;;)
  {
    /* Line: 251       : UNTIL              : flappy.cob */
    if (((int)cob_cmp_s32 (b_77, (*(int *)(b_67))) > 0))
      break;

    /* Line: 252       : COMPUTE            : flappy.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3)));
    cob_decimal_set_llint (d_1, (*(int *)(b_68)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_90, 0);

    /* Line: 253       : MOVE               : flappy.cob */
    memcpy (b_91, b_72 + 4 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), 4);

    /* Line: 254       : COMPUTE            : flappy.cob */
    cob_decimal_set_llint (d_0, cob_get_llint (COB_SET_FLD (f0, 4, b_72 + 4 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3)));
    cob_decimal_set_llint (d_1, (*(int *)(b_69)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_92, 0);

    /* Line: 255       : COMPUTE            : flappy.cob */
    cob_decimal_set_llint (d_0, (*(int *)(b_55)));
    cob_decimal_set_llint (d_1, (*(int *)(b_92)));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_93, 0);

    /* Line: 257       : IF                 : flappy.cob */
    if ((((((int)cob_cmp_s32 (b_61, (*(int *)(b_90))) < 0) && 
        ((int)cob_cmp_s32 (b_88, cob_get_llint (COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3))) > 0)) && 
        ((int)cob_cmp_s32 (b_62, (*(int *)(b_91))) < 0)) && 
        ((int)cob_cmp_s32 (b_89, 0LL) > 0)))
    {

      /* Line: 261       : MOVE               : flappy.cob */
      *(b_94) = 89;
    }

    /* Line: 264       : IF                 : flappy.cob */
    if ((((((int)cob_cmp_s32 (b_61, (*(int *)(b_90))) < 0) && 
        ((int)cob_cmp_s32 (b_88, cob_get_llint (COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3))) > 0)) && 
        ((int)(
    cob_decimal_set_llint (d_0, (*(int *)(b_62))),
    cob_decimal_set_llint (d_1, (*(int *)(b_92))),
    cob_decimal_set_llint (d_2, (*(int *)(b_93))),
    cob_decimal_add (d_1, d_2),
    cob_decimal_cmp (d_0, d_1)) < 0)) && 
        ((int)cob_cmp_s32 (b_89, (*(int *)(b_92))) > 0)))
    {

      /* Line: 268       : MOVE               : flappy.cob */
      *(b_94) = 89;
    }
    /* Line: 251       : VARYING            : flappy.cob */
    cob_add_s32 (b_77, 1);
  }

  /* Line: 272       : IF                 : flappy.cob */
  if (((int)(int)(*(b_94) - (unsigned char)'Y') == 0))
  {

    /* Line: 273       : PERFORM            : flappy.cob */
    /* PERFORM GAME-OVER */
    frame_ptr++;
    frame_ptr->perform_through = 15;
    frame_ptr->return_address_ptr = &&l_33;
    goto l_15;
    l_33:
    frame_ptr--;
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address_ptr;

  /* Line: 277       : Paragraph GAME-OVER               : flappy.cob */
  l_15:;

  /* Line: 278       : SET                : flappy.cob */
  *(b_47) = 49;

  /* Line: 279       : PERFORM            : flappy.cob */
  /* PERFORM UPDATE-TITLE */
  frame_ptr++;
  frame_ptr->perform_through = 16;
  frame_ptr->return_address_ptr = &&l_34;
  goto l_16;
  l_34:
  frame_ptr--;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Line: 282       : Paragraph UPDATE-TITLE            : flappy.cob */
  l_16:;

  /* Line: 283       : MOVE               : flappy.cob */
  cob_move (&f_79, &f_80);

  /* Line: 284       : MOVE               : flappy.cob */
  cob_move (cob_intr_trim (0, 0, &f_80, 0), &f_81);

  /* Line: 286       : IF                 : flappy.cob */
  if (((int)cob_cmp_numdisp (b_47, 1, 0LL, 0) == 0))
  {

    /* Line: 287       : STRING             : flappy.cob */
    cob_string_init (&f_50, NULL);
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_10);
    cob_string_delimited (NULL);
    cob_string_append (&f_81);
    cob_string_finish ();
  }
  else
  {
    /* ELSE */

    /* Line: 292       : STRING             : flappy.cob */
    cob_string_init (&f_50, NULL);
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_11);
    cob_string_delimited (NULL);
    cob_string_append (&f_81);
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_12);
    cob_string_finish ();
  }

  /* Line: 299       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_17;
  cob_procedure_params[1] = &f_50;
  cob_procedure_params[2] = (cob_field *)&c_13;
  cob_glob_ptr->cob_call_params = 3;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_set_window_title (b_17, b_50, (cob_u64_t)128LL);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 16)
    goto *frame_ptr->return_address_ptr;

  /* Line: 305       : Paragraph RENDER                  : flappy.cob */
  l_17:;

  /* Line: 307       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_procedure_params[1] = (cob_field *)&c_14;
  cob_procedure_params[2] = (cob_field *)&c_15;
  cob_procedure_params[3] = (cob_field *)&c_16;
  cob_procedure_params[4] = (cob_field *)&c_17;
  cob_glob_ptr->cob_call_params = 5;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_set_draw_color (b_18, (cob_u64_t)135LL, (cob_u64_t)206LL, (cob_u64_t)235LL, (cob_u64_t)255LL);

  /* Line: 309       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_clear (b_18);

  /* Line: 312       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_procedure_params[1] = (cob_field *)&c_18;
  cob_procedure_params[2] = (cob_field *)&c_19;
  cob_procedure_params[3] = (cob_field *)&c_20;
  cob_procedure_params[4] = (cob_field *)&c_17;
  cob_glob_ptr->cob_call_params = 5;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_set_draw_color (b_18, (cob_u64_t)20LL, (cob_u64_t)180LL, (cob_u64_t)75LL, (cob_u64_t)255LL);

  /* Line: 314       : PERFORM            : flappy.cob */
  cob_move ((cob_field *)&c_3, &f_77);
  for (;;)
  {
    /* Line: 314       : UNTIL              : flappy.cob */
    if (((int)cob_cmp_s32 (b_77, (*(int *)(b_67))) > 0))
      break;

    /* Line: 315       : MOVE               : flappy.cob */
    memcpy (b_91, b_72 + 4 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), 4);

    /* Line: 316       : COMPUTE            : flappy.cob */
    cob_decimal_set_llint (d_0, (*(int *)(b_91)));
    cob_decimal_set_llint (d_1, (*(int *)(b_69)));
    cob_decimal_add (d_0, d_1);
    cob_decimal_get_field (d_0, &f_92, 0);

    /* Line: 317       : COMPUTE            : flappy.cob */
    cob_decimal_set_llint (d_0, (*(int *)(b_55)));
    cob_decimal_set_llint (d_1, (*(int *)(b_92)));
    cob_decimal_sub (d_0, d_1);
    cob_decimal_get_field (d_0, &f_93, 0);

    /* Line: 319       : CALL               : flappy.cob */
    cob_procedure_params[0] = &f_18;
    cob_procedure_params[1] = COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3);
    cob_procedure_params[2] = (cob_field *)&c_6;
    cob_procedure_params[3] = &f_68;
    cob_procedure_params[4] = &f_91;
    cob_glob_ptr->cob_call_params = 5;
    cob_glob_ptr->cob_stmt_exception = 0;
    b_2 = cpg_fill_rect (b_18, (cob_u64_t)(cob_get_int (COB_SET_FLD (f1, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3))), (cob_u64_t)0LL, (cob_u64_t)((*(int *)(b_68))), (cob_u64_t)((*(int *)(b_91))));

    /* Line: 324       : CALL               : flappy.cob */
    cob_procedure_params[0] = &f_18;
    cob_procedure_params[1] = COB_SET_FLD (f0, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3);
    cob_procedure_params[2] = &f_92;
    cob_procedure_params[3] = &f_68;
    cob_procedure_params[4] = &f_93;
    cob_glob_ptr->cob_call_params = 5;
    cob_glob_ptr->cob_stmt_exception = 0;
    b_2 = cpg_fill_rect (b_18, (cob_u64_t)(cob_get_int (COB_SET_FLD (f1, 4, b_72 + 9LL * ((cob_s64_t)((*(int *)(b_77))) - 1), &a_3))), (cob_u64_t)((*(int *)(b_92))), (cob_u64_t)((*(int *)(b_68))), (cob_u64_t)((*(int *)(b_93))));
    /* Line: 314       : VARYING            : flappy.cob */
    cob_add_s32 (b_77, 1);
  }

  /* Line: 332       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_procedure_params[1] = (cob_field *)&c_21;
  cob_procedure_params[2] = (cob_field *)&c_22;
  cob_procedure_params[3] = (cob_field *)&c_23;
  cob_procedure_params[4] = (cob_field *)&c_17;
  cob_glob_ptr->cob_call_params = 5;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_set_draw_color (b_18, (cob_u64_t)140LL, (cob_u64_t)95LL, (cob_u64_t)40LL, (cob_u64_t)255LL);

  /* Line: 334       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_procedure_params[1] = (cob_field *)&c_6;
  cob_procedure_params[2] = &f_55;
  cob_procedure_params[3] = &f_52;
  cob_procedure_params[4] = &f_54;
  cob_glob_ptr->cob_call_params = 5;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_fill_rect (b_18, (cob_u64_t)0LL, (cob_u64_t)((*(int *)(b_55))), (cob_u64_t)((*(int *)(b_52))), (cob_u64_t)((*(int *)(b_54))));

  /* Line: 339       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_procedure_params[1] = (cob_field *)&c_24;
  cob_procedure_params[2] = (cob_field *)&c_25;
  cob_procedure_params[3] = (cob_field *)&c_18;
  cob_procedure_params[4] = (cob_field *)&c_17;
  cob_glob_ptr->cob_call_params = 5;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_set_draw_color (b_18, (cob_u64_t)250LL, (cob_u64_t)220LL, (cob_u64_t)20LL, (cob_u64_t)255LL);

  /* Line: 341       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_procedure_params[1] = &f_61;
  cob_procedure_params[2] = &f_62;
  cob_procedure_params[3] = &f_63;
  cob_procedure_params[4] = &f_63;
  cob_glob_ptr->cob_call_params = 5;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_fill_rect (b_18, (cob_u64_t)((*(int *)(b_61))), (cob_u64_t)((*(int *)(b_62))), (cob_u64_t)((*(int *)(b_63))), (cob_u64_t)((*(int *)(b_63))));

  /* Line: 345       : CALL               : flappy.cob */
  cob_procedure_params[0] = &f_18;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  b_2 = cpg_present (b_18);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
      module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
      cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  flappy_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field CPG-WINDOW */
  memset (b_17, 0x0, 8);

  /* initialize field CPG-RENDERER */
  memset (b_18, 0x0, 8);

  /* initialize field CPG-TEXTURE */
  memset (b_19, 0x0, 8);

  /* initialize field CPG-EVENT */
  memset (b_20, 0x0, 32);

  /* initialize field WS-RC */
  cob_move ((cob_field *)&c_6, &f_45);

  /* initialize field WS-RUNNING */
  *(cob_u8_ptr)(b_46) = (unsigned char)'Y';

  /* initialize field WS-STATE */
  *(b_47) = 48;

  /* initialize field WS-TITLE */
  memset (b_50, (unsigned char)' ', 128);

  /* initialize field WS-ERR */
  memset (b_51, (unsigned char)' ', 256);

  /* initialize field WS-WIN-W */
  cob_move ((cob_field *)&c_26, &f_52);

  /* initialize field WS-WIN-H */
  cob_move ((cob_field *)&c_27, &f_53);

  /* initialize field WS-GROUND-H */
  cob_move ((cob_field *)&c_28, &f_54);

  /* initialize field WS-GROUND-Y */
  cob_move ((cob_field *)&c_6, &f_55);

  /* initialize field WS-FRAME-TARGET-MS */
  cob_move ((cob_field *)&c_29, &f_56);

  /* initialize field WS-FRAME-START */
  cob_move ((cob_field *)&c_6, &f_57);

  /* initialize field WS-FRAME-END */
  cob_move ((cob_field *)&c_6, &f_58);

  /* initialize field WS-FRAME-ELAPSED */
  cob_move ((cob_field *)&c_6, &f_59);

  /* initialize field WS-SLEEP-MS */
  cob_move ((cob_field *)&c_6, &f_60);

  /* initialize field WS-BIRD-X */
  cob_move ((cob_field *)&c_8, &f_61);

  /* initialize field WS-BIRD-Y */
  cob_move ((cob_field *)&c_30, &f_62);

  /* initialize field WS-BIRD-S */
  cob_move ((cob_field *)&c_31, &f_63);

  /* initialize field WS-BIRD-VY */
  cob_move ((cob_field *)&c_6, &f_64);

  /* initialize field WS-GRAVITY */
  cob_move ((cob_field *)&c_3, &f_65);

  /* initialize field WS-FLAP-V */
  cob_move ((cob_field *)&c_32, &f_66);

  /* initialize field WS-PIPE-N */
  cob_move ((cob_field *)&c_33, &f_67);

  /* initialize field WS-PIPE-W */
  cob_move ((cob_field *)&c_34, &f_68);

  /* initialize field WS-PIPE-GAP */
  cob_move ((cob_field *)&c_35, &f_69);

  /* initialize field WS-PIPE-SPACING */
  cob_move ((cob_field *)&c_36, &f_70);

  /* initialize field WS-PIPE-SPEED */
  cob_move ((cob_field *)&c_33, &f_71);

  /* initialize WS-PIPE: init first record */
  {
    /* initialize field WS-PIPE-X */
    cob_move ((cob_field *)&c_6, COB_SET_FLD (f0, 4, b_72, &a_3));
    /* initialize field WS-PIPE-GAP-Y */
    cob_move ((cob_field *)&c_8, COB_SET_FLD (f0, 4, b_72 + 4, &a_3));
    /* initialize field WS-PIPE-SCORED */
    cob_move ((cob_field *)&c_6, COB_SET_FLD (f0, 1, b_72 + 8, &a_9));
    /* initialize WS-PIPE: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_72;
      memcpy (b_ptr +      9, b_ptr,      9);    /* WS-PIPE:     2 thru 2 */
      memcpy (b_ptr +     18, b_ptr,      9);    /* WS-PIPE:     3 thru 3 */
    }
  }

  /* initialize field WS-I */
  cob_move ((cob_field *)&c_6, &f_77);

  /* initialize field WS-RIGHTMOST-X */
  cob_move ((cob_field *)&c_6, &f_78);

  /* initialize field WS-SCORE */
  cob_move ((cob_field *)&c_6, &f_79);

  /* initialize field WS-SCORE-DISP */
  cob_move (&cob_all_zero, &f_80);

  /* initialize field WS-SCORE-TXT */
  memset (b_81, (unsigned char)' ', 8);

  /* initialize field WS-SEED */
  cob_move ((cob_field *)&c_6, &f_82);

  /* initialize field WS-RAND */
  cob_move ((cob_field *)&c_6, &f_83);

  /* initialize field WS-GAP-PAD */
  cob_move ((cob_field *)&c_2, &f_84);

  /* initialize field WS-GAP-MAX */
  cob_move ((cob_field *)&c_6, &f_85);

  /* initialize field WS-GAP-RANGE */
  cob_move ((cob_field *)&c_6, &f_86);

  /* initialize field WS-GAP-VAL */
  cob_move ((cob_field *)&c_6, &f_87);

  /* initialize field WS-BIRD-R */
  cob_move ((cob_field *)&c_6, &f_88);

  /* initialize field WS-BIRD-B */
  cob_move ((cob_field *)&c_6, &f_89);

  /* initialize field WS-PIPE-R */
  cob_move ((cob_field *)&c_6, &f_90);

  /* initialize field WS-TOP-H */
  cob_move ((cob_field *)&c_6, &f_91);

  /* initialize field WS-BOT-Y */
  cob_move ((cob_field *)&c_6, &f_92);

  /* initialize field WS-BOT-H */
  cob_move ((cob_field *)&c_6, &f_93);

  /* initialize field WS-COLLIDE */
  *(cob_u8_ptr)(b_94) = (unsigned char)'N';


  /* Set Decimal Constant values */
  dc_3 = &kc_3;
  cob_decimal_init (dc_3);
  cob_decimal_set_field (dc_3, (cob_field *)&c_3);

  dc_2 = &kc_2;
  cob_decimal_init (dc_2);
  cob_decimal_set_field (dc_2, (cob_field *)&c_2);

  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
      return 0;
  if (module && module->module_active)
      cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_3);
  dc_3 = NULL;
  cob_decimal_clear (dc_2);
  dc_2 = NULL;
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'flappy' */

/* Initialize module structure for flappy */
static void flappy_module_init (cob_module *module)
{
  module->module_name = "flappy";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())flappy;
  module->module_cancel.funcptr = (void *(*)())flappy_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

