/* Generated by           cobc 3.2.0 */
/* Generated from         flappy.cob */
/* Generated at           Mar 30 2026 13:57:52 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -x -free -fstatic-call -I cobol -o flappy.c flappy.cob */


/* Module path */
static const char        *cob_module_path = NULL;

/* Number of call parameters */
static int        cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
    {'Z', 7},
    {'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =    {0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =    {0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_3 =    {0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_4 =    {0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =    {0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_6 =    {0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_7 =    {0x11,  17,   0, 0x0080, NULL};
static const cob_field_attr a_8 =    {0x14,  34,  17, 0x0201, NULL};
static const cob_field_attr a_9 =    {0x11,   1,   0, 0x0040, NULL};
static const cob_field_attr a_10 =    {0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_11 =    {0x10,   6,   0, 0x0007, NULL};
static const cob_field_attr a_12 =    {0x24,   7,   0, 0x0000, p_1};
static const cob_field_attr a_13 =    {0x10,   2,   0, 0x0007, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1    = {1, (cob_u8_ptr)"2", &a_1};
static const cob_field c_2    = {2, (cob_u8_ptr)"60", &a_2};
static const cob_field c_3    = {1, (cob_u8_ptr)"1", &a_1};
static const cob_field c_4    = {3, (cob_u8_ptr)"256", &a_5};
static const cob_field c_5    = {17, (cob_u8_ptr)"cpg_init failed: ", &a_6};
static const cob_field c_6    = {1, (cob_u8_ptr)"0", &a_1};
static const cob_field c_7    = {24, (cob_u8_ptr)"window/renderer failed: ", &a_6};
static const cob_field c_8    = {3, (cob_u8_ptr)"120", &a_5};
static const cob_field c_9    = {7, (cob_u8_ptr)"-999999", &a_11};
static const cob_field c_10    = {20, (cob_u8_ptr)"FlappyCOBOL  Score: ", &a_6};
static const cob_field c_11    = {18, (cob_u8_ptr)"GAME OVER  Score: ", &a_6};
static const cob_field c_12    = {20, (cob_u8_ptr)"  (SPACE to restart)", &a_6};
static const cob_field c_13    = {3, (cob_u8_ptr)"128", &a_5};
static const cob_field c_14    = {3, (cob_u8_ptr)"135", &a_5};
static const cob_field c_15    = {3, (cob_u8_ptr)"206", &a_5};
static const cob_field c_16    = {3, (cob_u8_ptr)"235", &a_5};
static const cob_field c_17    = {3, (cob_u8_ptr)"255", &a_5};
static const cob_field c_18    = {2, (cob_u8_ptr)"20", &a_2};
static const cob_field c_19    = {3, (cob_u8_ptr)"180", &a_5};
static const cob_field c_20    = {2, (cob_u8_ptr)"75", &a_2};
static const cob_field c_21    = {3, (cob_u8_ptr)"140", &a_5};
static const cob_field c_22    = {2, (cob_u8_ptr)"95", &a_2};
static const cob_field c_23    = {2, (cob_u8_ptr)"40", &a_2};
static const cob_field c_24    = {3, (cob_u8_ptr)"250", &a_5};
static const cob_field c_25    = {3, (cob_u8_ptr)"220", &a_5};
static const cob_field c_26    = {3, (cob_u8_ptr)"480", &a_5};
static const cob_field c_27    = {3, (cob_u8_ptr)"640", &a_5};
static const cob_field c_28    = {2, (cob_u8_ptr)"90", &a_2};
static const cob_field c_29    = {2, (cob_u8_ptr)"16", &a_2};
static const cob_field c_30    = {3, (cob_u8_ptr)"260", &a_5};
static const cob_field c_31    = {2, (cob_u8_ptr)"22", &a_2};
static const cob_field c_32    = {3, (cob_u8_ptr)"-12", &a_13};
static const cob_field c_33    = {1, (cob_u8_ptr)"3", &a_1};
static const cob_field c_34    = {2, (cob_u8_ptr)"68", &a_2};
static const cob_field c_35    = {3, (cob_u8_ptr)"170", &a_5};
static const cob_field c_36    = {3, (cob_u8_ptr)"230", &a_5};

static cob_field cob_all_zero    = {1, (cob_u8_ptr)"0", &cob_all_attr};


static COB_INLINE COB_A_INLINE int
cob_cmp_u8 (const void *p, const cob_s64_t n)
{
    if (unlikely(n < 0)) {
        return 1;
    }
    return (*(const unsigned char *)p < n) ? -1 : (*(const unsigned char *)p > n);
}


static COB_INLINE COB_A_INLINE int
cob_cmp_s32 (const void *p, const cob_s64_t n)
{
    int    val;
    void    *x;
    x = &val;
    optim_memcpy (x, p, 4);
    return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_add_s32 (void *p, const int val)
{
    void    *x;
    int    n;
    x = &n;
    optim_memcpy (x, p, 4);
    n += val;
    optim_memcpy (p, x, 4);
}


static COB_INLINE COB_A_INLINE void
cob_sub_s32 (void *p, const int val)
{
    void    *x;
    int    n;
    x = &n;
    optim_memcpy (x, p, 4);
    n -= val;
    optim_memcpy (p, x, 4);
}


/* Decimal constants */
static    cob_decimal    kc_1;
static    cob_decimal    *dc_1 = NULL;
static    cob_decimal    kc_2;
static    cob_decimal    *dc_2 = NULL;
static    cob_decimal    kc_3;
static    cob_decimal    *dc_3 = NULL;

