/* Generated by           cobc 3.2.0 */
/* Generated from         flappy.cob */
/* Generated at           Mar 30 2026 13:57:52 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -x -free -fstatic-call -I cobol -o flappy.c flappy.cob */

/* Program local variables for 'flappy' */

/* Module initialization indicator */
static unsigned int    initialized = 0;

/* Module structure pointer */
static cob_module    *module = NULL;

/* Global variable pointer */
cob_global        *cob_glob_ptr;

/* Decimal structures */
cob_decimal    *d_0 = NULL;
cob_decimal    *d_1 = NULL;
cob_decimal    *d_2 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char    *b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char    *b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char    *b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char    *b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char    *b_13 = NULL;  /* XML-NTEXT */
static unsigned char    *b_14 = NULL;  /* XML-TEXT */

/* Define external subroutines being called statically */
#ifndef cpg_init
extern int cpg_init ();
#endif
#ifndef cpg_get_error
extern int cpg_get_error ();
#endif
#ifndef cpg_create_window_and_renderer
extern int cpg_create_window_and_renderer ();
#endif
#ifndef cpg_quit
extern int cpg_quit ();
#endif
#ifndef cpg_ticks
extern int cpg_ticks ();
#endif
#ifndef cpg_delay
extern int cpg_delay ();
#endif
#ifndef cpg_destroy_renderer
extern int cpg_destroy_renderer ();
#endif
#ifndef cpg_destroy_window
extern int cpg_destroy_window ();
#endif
#ifndef cpg_poll_event
extern int cpg_poll_event ();
#endif
#ifndef cpg_set_window_title
extern int cpg_set_window_title ();
#endif
#ifndef cpg_set_draw_color
extern int cpg_set_draw_color ();
#endif
#ifndef cpg_clear
extern int cpg_clear ();
#endif
#ifndef cpg_fill_rect
extern int cpg_fill_rect ();
#endif
#ifndef cpg_present
extern int cpg_present ();
#endif

/* Local cob_field items */
cob_field        f0;
cob_field        f1;


/* Call parameters */
cob_field        *cob_procedure_params[6];

/* Perform frame stack */
struct cob_frame    *frame_ptr;
struct cob_frame    frame_stack[255];


/* Data storage */
static int    b_2;    /* RETURN-CODE */
static cob_u8_t    b_17[8] __attribute__((aligned));    /* CPG-WINDOW */
static cob_u8_t    b_18[8] __attribute__((aligned));    /* CPG-RENDERER */
static cob_u8_t    b_19[8] __attribute__((aligned));    /* CPG-TEXTURE */
static cob_u8_t    b_20[32] __attribute__((aligned));    /* CPG-EVENT */
static cob_u8_t    b_45[4] __attribute__((aligned));    /* WS-RC */
static cob_u8_t    b_46[1] __attribute__((aligned));    /* WS-RUNNING */
static cob_u8_t    b_47[1] __attribute__((aligned));    /* WS-STATE */
static cob_u8_t    b_50[128] __attribute__((aligned));    /* WS-TITLE */
static cob_u8_t    b_51[256] __attribute__((aligned));    /* WS-ERR */
static cob_u8_t    b_52[4] __attribute__((aligned));    /* WS-WIN-W */
static cob_u8_t    b_53[4] __attribute__((aligned));    /* WS-WIN-H */
static cob_u8_t    b_54[4] __attribute__((aligned));    /* WS-GROUND-H */
static cob_u8_t    b_55[4] __attribute__((aligned));    /* WS-GROUND-Y */
static cob_u8_t    b_56[4] __attribute__((aligned));    /* WS-FRAME-TARGET-MS */
static cob_u8_t    b_57[4] __attribute__((aligned));    /* WS-FRAME-START */
static cob_u8_t    b_58[4] __attribute__((aligned));    /* WS-FRAME-END */
static cob_u8_t    b_59[4] __attribute__((aligned));    /* WS-FRAME-ELAPSED */
static cob_u8_t    b_60[4] __attribute__((aligned));    /* WS-SLEEP-MS */
static cob_u8_t    b_61[4] __attribute__((aligned));    /* WS-BIRD-X */
static cob_u8_t    b_62[4] __attribute__((aligned));    /* WS-BIRD-Y */
static cob_u8_t    b_63[4] __attribute__((aligned));    /* WS-BIRD-S */
static cob_u8_t    b_64[4] __attribute__((aligned));    /* WS-BIRD-VY */
static cob_u8_t    b_65[4] __attribute__((aligned));    /* WS-GRAVITY */
static cob_u8_t    b_66[4] __attribute__((aligned));    /* WS-FLAP-V */
static cob_u8_t    b_67[4] __attribute__((aligned));    /* WS-PIPE-N */
static cob_u8_t    b_68[4] __attribute__((aligned));    /* WS-PIPE-W */
static cob_u8_t    b_69[4] __attribute__((aligned));    /* WS-PIPE-GAP */
static cob_u8_t    b_70[4] __attribute__((aligned));    /* WS-PIPE-SPACING */
static cob_u8_t    b_71[4] __attribute__((aligned));    /* WS-PIPE-SPEED */
static cob_u8_t    b_72[27] __attribute__((aligned));    /* WS-PIPES */
static cob_u8_t    b_77[4] __attribute__((aligned));    /* WS-I */
static cob_u8_t    b_78[4] __attribute__((aligned));    /* WS-RIGHTMOST-X */
static cob_u8_t    b_79[4] __attribute__((aligned));    /* WS-SCORE */
static cob_u8_t    b_80[7] __attribute__((aligned));    /* WS-SCORE-DISP */
static cob_u8_t    b_81[8] __attribute__((aligned));    /* WS-SCORE-TXT */
static cob_u8_t    b_82[4] __attribute__((aligned));    /* WS-SEED */
static cob_u8_t    b_83[8] __attribute__((aligned));    /* WS-RAND */
static cob_u8_t    b_84[4] __attribute__((aligned));    /* WS-GAP-PAD */
static cob_u8_t    b_85[4] __attribute__((aligned));    /* WS-GAP-MAX */
static cob_u8_t    b_86[4] __attribute__((aligned));    /* WS-GAP-RANGE */
static cob_u8_t    b_87[4] __attribute__((aligned));    /* WS-GAP-VAL */
static cob_u8_t    b_88[4] __attribute__((aligned));    /* WS-BIRD-R */
static cob_u8_t    b_89[4] __attribute__((aligned));    /* WS-BIRD-B */
static cob_u8_t    b_90[4] __attribute__((aligned));    /* WS-PIPE-R */
static cob_u8_t    b_91[4] __attribute__((aligned));    /* WS-TOP-H */
static cob_u8_t    b_92[4] __attribute__((aligned));    /* WS-BOT-Y */
static cob_u8_t    b_93[4] __attribute__((aligned));    /* WS-BOT-H */
static cob_u8_t    b_94[1] __attribute__((aligned));    /* WS-COLLIDE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17    = {8, b_17, &a_7};    /* CPG-WINDOW */
static cob_field f_18    = {8, b_18, &a_7};    /* CPG-RENDERER */
static cob_field f_20    = {32, b_20, &a_10};    /* CPG-EVENT */
static cob_field f_45    = {4, b_45, &a_3};    /* WS-RC */
static cob_field f_50    = {128, b_50, &a_4};    /* WS-TITLE */
static cob_field f_51    = {256, b_51, &a_4};    /* WS-ERR */
static cob_field f_52    = {4, b_52, &a_3};    /* WS-WIN-W */
static cob_field f_53    = {4, b_53, &a_3};    /* WS-WIN-H */
static cob_field f_54    = {4, b_54, &a_3};    /* WS-GROUND-H */
static cob_field f_55    = {4, b_55, &a_3};    /* WS-GROUND-Y */
static cob_field f_56    = {4, b_56, &a_3};    /* WS-FRAME-TARGET-MS */
static cob_field f_57    = {4, b_57, &a_3};    /* WS-FRAME-START */
static cob_field f_58    = {4, b_58, &a_3};    /* WS-FRAME-END */
static cob_field f_59    = {4, b_59, &a_3};    /* WS-FRAME-ELAPSED */
static cob_field f_60    = {4, b_60, &a_3};    /* WS-SLEEP-MS */
static cob_field f_61    = {4, b_61, &a_3};    /* WS-BIRD-X */
static cob_field f_62    = {4, b_62, &a_3};    /* WS-BIRD-Y */
static cob_field f_63    = {4, b_63, &a_3};    /* WS-BIRD-S */
static cob_field f_64    = {4, b_64, &a_3};    /* WS-BIRD-VY */
static cob_field f_65    = {4, b_65, &a_3};    /* WS-GRAVITY */
static cob_field f_66    = {4, b_66, &a_3};    /* WS-FLAP-V */
static cob_field f_67    = {4, b_67, &a_3};    /* WS-PIPE-N */
static cob_field f_68    = {4, b_68, &a_3};    /* WS-PIPE-W */
static cob_field f_69    = {4, b_69, &a_3};    /* WS-PIPE-GAP */
static cob_field f_70    = {4, b_70, &a_3};    /* WS-PIPE-SPACING */
static cob_field f_71    = {4, b_71, &a_3};    /* WS-PIPE-SPEED */
static cob_field f_77    = {4, b_77, &a_3};    /* WS-I */
static cob_field f_78    = {4, b_78, &a_3};    /* WS-RIGHTMOST-X */
static cob_field f_79    = {4, b_79, &a_3};    /* WS-SCORE */
static cob_field f_80    = {7, b_80, &a_12};    /* WS-SCORE-DISP */
static cob_field f_81    = {8, b_81, &a_4};    /* WS-SCORE-TXT */
static cob_field f_82    = {4, b_82, &a_3};    /* WS-SEED */
static cob_field f_83    = {8, b_83, &a_8};    /* WS-RAND */
static cob_field f_84    = {4, b_84, &a_3};    /* WS-GAP-PAD */
static cob_field f_85    = {4, b_85, &a_3};    /* WS-GAP-MAX */
static cob_field f_86    = {4, b_86, &a_3};    /* WS-GAP-RANGE */
static cob_field f_87    = {4, b_87, &a_3};    /* WS-GAP-VAL */
static cob_field f_88    = {4, b_88, &a_3};    /* WS-BIRD-R */
static cob_field f_89    = {4, b_89, &a_3};    /* WS-BIRD-B */
static cob_field f_90    = {4, b_90, &a_3};    /* WS-PIPE-R */
static cob_field f_91    = {4, b_91, &a_3};    /* WS-TOP-H */
static cob_field f_92    = {4, b_92, &a_3};    /* WS-BOT-Y */
static cob_field f_93    = {4, b_93, &a_3};    /* WS-BOT-H */

/* End of fields */

